// Proves the fidelity evaluator's math: rows generated BY the exact port must
// evaluate to perfect fidelity; perturbed rows must degrade measurably.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { evaluateFidelity } from '../scores/v12Fidelity.mjs';
import { scoreV12Owner } from '../scores/v12Baseline.mjs';

function syntheticRow(i) {
  const owner = scoreV12Owner({
    tax_delinquent_count: i % 3 === 0 ? 1 : 0,
    oldest_tax_delinquent_year: i % 3 === 0 ? 2021 + (i % 4) : 0,
    portfolio_total_value: 100000 + i * 7000,
    portfolio_total_equity: 20000 + i * 5000,
    portfolio_total_loan_balance: 40000 + i * 1000,
    best_buying_power: '', best_income: '', best_net_asset: '',
    seller_tags_text: i % 4 === 0 ? 'Vacant Home; Absentee Owner' : '',
    last_sale_doc_type: i % 5 === 0 ? 'Quit Claim Deed' : 'Warranty Deed',
    max_ownership_years: (i % 30), distress_marker_count: 0,
    is_absentee: i % 2 === 0, active_lien_count: i % 7 === 0 ? 1 : 0,
    property_count: 1 + (i % 6), best_contact_score: (i * 13) % 100, best_phone_score: (i * 29) % 100,
  });
  return {
    master_key: `mk${i}`,
    priority_score: owner.priority_score, priority_tier: owner.priority_tier,
    follow_up_cadence: owner.follow_up_cadence,
    financial_pressure_score: owner.financial_pressure_score,
    urgency_score: owner.urgency_score, contactability_score: owner.contactability_score,
    portfolio_total_value: owner.portfolio_total_value, portfolio_total_equity: owner.portfolio_total_equity,
    portfolio_total_loan_balance: owner.portfolio_total_loan_balance,
    tax_delinquent_count: owner.tax_delinquent_count, oldest_tax_delinquent_year: owner.oldest_tax_delinquent_year,
    active_lien_count: owner.active_lien_count, property_count: owner.property_count,
    seller_tags_text: owner.seller_tags_text, last_sale_doc_type: owner.last_sale_doc_type,
    max_ownership_years: owner.max_ownership_years,
    owner_location_text: owner.is_absentee ? 'Absentee Owner' : 'Owner Occupied',
  };
}

test('evaluator: port-generated rows -> perfect priority/tier/cadence fidelity', () => {
  const rows = Array.from({ length: 200 }, (_, i) => syntheticRow(i));
  const rep = evaluateFidelity(rows);
  assert.equal(rep.rows_with_historical_scores, 200);
  assert.equal(rep.exact_recompute.priority.exact_match_rate, 1);
  assert.equal(rep.exact_recompute.priority.mean_absolute_error, 0);
  assert.equal(rep.exact_recompute.priority.rank_correlation_spearman, 1);
  assert.equal(rep.exact_recompute.tier_exact_match_rate, 1);
  assert.equal(rep.exact_recompute.cadence_exact_match_rate, 1);
  assert.equal(rep.mismatch_examples.length, 0);
});

test('evaluator: perturbed historical scores are detected with examples and error stats', () => {
  const rows = Array.from({ length: 100 }, (_, i) => syntheticRow(i));
  for (let i = 0; i < 20; i += 1) rows[i].priority_score += 7;  // simulate drifted history
  const rep = evaluateFidelity(rows);
  assert.equal(rep.exact_recompute.priority.exact_match_rate, 0.8);
  assert.ok(rep.exact_recompute.priority.mean_absolute_error > 1);
  assert.ok(rep.mismatch_examples.length > 0);
  assert.ok(rep.mismatch_examples[0].inputs);
});

test('evaluator: urgency bound logic holds on port-generated rows (marker count 0 case)', () => {
  const rows = Array.from({ length: 60 }, (_, i) => syntheticRow(i));
  const rep = evaluateFidelity(rows);
  assert.ok(rep.partial_recompute.urgency_within_marker_bounds_rate >= 0.95);
});
