import type { CommandCenterReferenceDataset } from './types'

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60_000).toISOString()

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 3_600_000).toISOString()

const daysAgo = (days: number) => new Date(Date.now() - days * 86_400_000).toISOString()

export const referenceCommandCenterData: CommandCenterReferenceDataset = {
  markets: [
    {
      id: 'm-dallas',
      slug: 'dallas',
      name: 'Dallas',
      stateCode: 'TX',
      label: 'Dallas, TX',
      lat: 32.7767,
      lng: -96.797,
      heat: 'hot',
      campaignStatus: 'live',
      scanLabel: 'SCAN ACTIVE',
      activeProperties: 2487,
      totalOutbound: 1624,
      outboundToday: 1624,
      repliesToday: 89,
      hotLeads: 26,
      pipelineValue: 3160000,
      deliverability: 97.3,
      healthScore: 93,
      activeCampaigns: 4,
      replyRate: 5.5,
      positiveRate: 41.2,
      optOutRate: 0.9,
      pendingFollowUps: 12,
      hourlyOutbound: [
        48, 46, 43, 40, 37, 42, 51, 55, 63, 67, 69, 71, 74, 77, 83, 88, 91, 95,
        90, 84, 79, 72, 61, 54,
      ],
      recentReplyRate: [3.8, 4.2, 4.5, 4.8, 5.1, 5.4, 5.6, 5.8],
      topZips: [
        { zip: '75217', outbound: 286, trend: '+' },
        { zip: '75228', outbound: 244, trend: '+' },
        { zip: '75243', outbound: 198, trend: '−' },
        { zip: '75150', outbound: 186, trend: '+' },
      ],
      pipelineDistribution: {
        new: 30,
        contacted: 24,
        responding: 20,
        negotiating: 16,
        underContract: 10,
      },
      lastSweepIso: minutesAgo(6),
      operationalRisk: 'nominal',
      capacityStrain: 72,
    },
    {
      id: 'm-houston',
      slug: 'houston',
      name: 'Houston',
      stateCode: 'TX',
      label: 'Houston, TX',
      lat: 29.7604,
      lng: -95.3698,
      heat: 'hot',
      campaignStatus: 'live',
      scanLabel: 'SCAN ACTIVE',
      activeProperties: 3121,
      totalOutbound: 1902,
      outboundToday: 1902,
      repliesToday: 104,
      hotLeads: 31,
      pipelineValue: 4020000,
      deliverability: 96.8,
      healthScore: 91,
      activeCampaigns: 5,
      replyRate: 5.9,
      positiveRate: 43.4,
      optOutRate: 1.1,
      pendingFollowUps: 15,
      hourlyOutbound: [
        52, 48, 45, 41, 39, 44, 53, 58, 66, 72, 78, 81, 85, 87, 92, 97, 101, 104,
        102, 96, 88, 79, 70, 63,
      ],
      recentReplyRate: [4.1, 4.5, 4.8, 5.2, 5.4, 5.7, 6.1, 6.4],
      topZips: [
        { zip: '77084', outbound: 302, trend: '+' },
        { zip: '77095', outbound: 276, trend: '+' },
        { zip: '77083', outbound: 224, trend: '+' },
        { zip: '77072', outbound: 199, trend: '−' },
      ],
      pipelineDistribution: {
        new: 28,
        contacted: 25,
        responding: 21,
        negotiating: 15,
        underContract: 11,
      },
      lastSweepIso: minutesAgo(4),
      operationalRisk: 'nominal',
      capacityStrain: 79,
    },
    {
      id: 'm-atlanta',
      slug: 'atlanta',
      name: 'Atlanta',
      stateCode: 'GA',
      label: 'Atlanta, GA',
      lat: 33.749,
      lng: -84.388,
      heat: 'warm',
      campaignStatus: 'warning',
      scanLabel: 'FOLLOW-UP BETA',
      activeProperties: 2276,
      totalOutbound: 1518,
      outboundToday: 1518,
      repliesToday: 81,
      hotLeads: 22,
      pipelineValue: 2890000,
      deliverability: 95.6,
      healthScore: 88,
      activeCampaigns: 4,
      replyRate: 5.3,
      positiveRate: 39.8,
      optOutRate: 1.4,
      pendingFollowUps: 19,
      hourlyOutbound: [
        44, 42, 39, 36, 33, 37, 45, 52, 58, 62, 64, 68, 71, 74, 76, 79, 82, 84,
        80, 75, 69, 63, 57, 49,
      ],
      recentReplyRate: [3.6, 3.9, 4.1, 4.4, 4.7, 4.9, 5.1, 5.2],
      topZips: [
        { zip: '30318', outbound: 241, trend: '+' },
        { zip: '30349', outbound: 214, trend: '−' },
        { zip: '30331', outbound: 196, trend: '+' },
        { zip: '30281', outbound: 171, trend: '+' },
      ],
      pipelineDistribution: {
        new: 31,
        contacted: 26,
        responding: 19,
        negotiating: 14,
        underContract: 10,
      },
      lastSweepIso: minutesAgo(11),
      operationalRisk: 'elevated',
      capacityStrain: 84,
    },
    {
      id: 'm-minneapolis',
      slug: 'minneapolis',
      name: 'Minneapolis',
      stateCode: 'MN',
      label: 'Minneapolis, MN',
      lat: 44.9778,
      lng: -93.265,
      heat: 'warm',
      campaignStatus: 'live',
      scanLabel: 'QUALIFIER ALPHA',
      activeProperties: 1439,
      totalOutbound: 962,
      outboundToday: 962,
      repliesToday: 57,
      hotLeads: 17,
      pipelineValue: 1840000,
      deliverability: 94.8,
      healthScore: 86,
      activeCampaigns: 3,
      replyRate: 5.9,
      positiveRate: 45.6,
      optOutRate: 0.7,
      pendingFollowUps: 8,
      hourlyOutbound: [
        29, 28, 26, 25, 23, 26, 30, 34, 39, 42, 45, 47, 49, 51, 53, 55, 59, 63,
        61, 58, 52, 48, 41, 36,
      ],
      recentReplyRate: [4.2, 4.6, 4.9, 5.1, 5.5, 5.9, 6.2, 6.6],
      topZips: [
        { zip: '55408', outbound: 158, trend: '+' },
        { zip: '55411', outbound: 136, trend: '+' },
        { zip: '55412', outbound: 121, trend: '+' },
        { zip: '55407', outbound: 114, trend: '−' },
      ],
      pipelineDistribution: {
        new: 27,
        contacted: 24,
        responding: 23,
        negotiating: 16,
        underContract: 10,
      },
      lastSweepIso: minutesAgo(8),
      operationalRisk: 'nominal',
      capacityStrain: 61,
    },
    {
      id: 'm-phoenix',
      slug: 'phoenix',
      name: 'Phoenix',
      stateCode: 'AZ',
      label: 'Phoenix, AZ',
      lat: 33.4484,
      lng: -112.074,
      heat: 'steady',
      campaignStatus: 'paused',
      scanLabel: 'FOLLOW-UP BETA',
      activeProperties: 2011,
      totalOutbound: 1328,
      outboundToday: 1328,
      repliesToday: 69,
      hotLeads: 19,
      pipelineValue: 2470000,
      deliverability: 93.2,
      healthScore: 83,
      activeCampaigns: 3,
      replyRate: 5.2,
      positiveRate: 38.9,
      optOutRate: 1.7,
      pendingFollowUps: 17,
      hourlyOutbound: [
        36, 34, 32, 31, 30, 33, 38, 42, 47, 51, 54, 57, 59, 61, 64, 66, 68, 70,
        67, 63, 58, 53, 46, 39,
      ],
      recentReplyRate: [3.3, 3.7, 3.9, 4.2, 4.5, 4.8, 4.9, 5.1],
      topZips: [
        { zip: '85041', outbound: 188, trend: '+' },
        { zip: '85033', outbound: 173, trend: '−' },
        { zip: '85009', outbound: 148, trend: '+' },
        { zip: '85301', outbound: 133, trend: '−' },
      ],
      pipelineDistribution: {
        new: 33,
        contacted: 23,
        responding: 19,
        negotiating: 14,
        underContract: 11,
      },
      lastSweepIso: minutesAgo(17),
      operationalRisk: 'moderate',
      capacityStrain: 69,
    },
  ],
  properties: [
    {
      id: 'p-minneapolis-oak',
      marketId: 'm-minneapolis',
      address: '3847 Oak Street',
      city: 'Minneapolis',
      stateCode: 'MN',
      zip: '55408',
      lat: 44.9492,
      lng: -93.2982,
      ownerName: 'Patricia Johnson',
      ownerType: 'absentee',
      propertyType: 'SFR',
      sentiment: 'hot',
      pipelineStage: 'negotiating',
      currentIntent: 'High Intent Seller',
      estimatedValue: 165000,
      offerAmount: 138000,
      pipelineDays: 11,
      outboundAttempts: 6,
      lastOutboundIso: hoursAgo(1),
      lastInboundIso: minutesAgo(14),
      aiSummary:
        'Owner expressed strong interest in selling due to relocation timeline. Cash offer preferred, wants to close within 14 days, and needs clean proof of comps before signing.',
      heatFactors: ['Cash-preferred seller', '14-day close window', 'Comp dispute — nearly unlocked'],
      urgencyScore: 91,
      opportunityScore: 88,
      actionConfidence: 82,
      conversationTemperature: 84,
      stageMomentum: 'accelerating',
      riskSummary: 'Comp variance is the sole remaining blocker — resolve before next touch or risk stall.',
      riskFlags: ['Comp variance ±8% — send updated package before next touch'],
      objectionsDetected: ['Price too low', 'Wants to see comparable sales'],
      recommendedAction:
        'Send revised comp package with speed-premium positioning, then offer a same-day call to lock the closing window.',
      messages: [
        {
          id: 'msg-p1-1',
          direction: 'outbound',
          message:
            'Hi Patricia, I noticed your property at 3847 Oak St. Would you consider a cash offer? We can close in 14 days.',
          timestampIso: daysAgo(3),
          aiGenerated: true,
        },
        {
          id: 'msg-p1-2',
          direction: 'inbound',
          message: 'How much are you thinking?',
          timestampIso: daysAgo(3),
        },
        {
          id: 'msg-p1-3',
          direction: 'outbound',
          message:
            'Based on the current market, we could offer $138,000 cash. No repairs needed and we cover closing costs.',
          timestampIso: daysAgo(1),
          aiGenerated: true,
        },
      ],
    },
    {
      id: 'p-dallas-grove',
      marketId: 'm-dallas',
      address: '912 Grove View Lane',
      city: 'Dallas',
      stateCode: 'TX',
      zip: '75217',
      lat: 32.7082,
      lng: -96.709,
      ownerName: 'David Anderson',
      ownerType: 'tax-delinquent',
      propertyType: 'Duplex',
      sentiment: 'warm',
      pipelineStage: 'contacted',
      currentIntent: 'Tax Delinquent',
      estimatedValue: 214000,
      offerAmount: 176000,
      pipelineDays: 7,
      outboundAttempts: 4,
      lastOutboundIso: hoursAgo(2),
      lastInboundIso: hoursAgo(6),
      aiSummary:
        'Owner engaged after the second touch and confirmed tax pressure is driving urgency. Price expectations remain flexible if closing certainty is high.',
      heatFactors: ['Tax deadline applying real pressure', 'Certainty-first posture confirmed', 'No-list preference signaled'],
      urgencyScore: 74,
      opportunityScore: 71,
      actionConfidence: 76,
      conversationTemperature: 62,
      stageMomentum: 'accelerating',
      riskSummary: 'Title review not started — narrow window before tax deadline closes the urgency window.',
      riskFlags: ['Title review not yet initiated', 'Follow-up window is narrow — act before delinquency date'],
      objectionsDetected: ['Needs proof of closing speed'],
      recommendedAction:
        'Move this lead to a certainty-first offer sequence and escalate title review before the next touch.',
      messages: [
        {
          id: 'msg-p2-1',
          direction: 'outbound',
          message:
            'David, we can make this simple: cash purchase, no repairs, and a closing date that works around your tax deadline.',
          timestampIso: daysAgo(2),
          aiGenerated: true,
        },
        {
          id: 'msg-p2-2',
          direction: 'inbound',
          message: 'If you can close quickly, I want to hear the number.',
          timestampIso: daysAgo(2),
        },
      ],
    },
    {
      id: 'p-houston-briar',
      marketId: 'm-houston',
      address: '2215 Briar Creek Drive',
      city: 'Houston',
      stateCode: 'TX',
      zip: '77084',
      lat: 29.8536,
      lng: -95.6849,
      ownerName: 'William Moore',
      ownerType: 'owner-occupied',
      propertyType: 'SFR',
      sentiment: 'warm',
      pipelineStage: 'responding',
      currentIntent: 'Tired Landlord',
      estimatedValue: 284000,
      offerAmount: 239000,
      pipelineDays: 13,
      outboundAttempts: 7,
      lastOutboundIso: minutesAgo(42),
      lastInboundIso: hoursAgo(4),
      aiSummary:
        'Owner is exhausted by maintenance issues and has asked for a clean close with minimal walkthrough friction. Tone is pragmatic rather than emotional.',
      heatFactors: ['No-listing preference confirmed', 'Tenant-free close explicitly requested', 'Pragmatic — not price-driven'],
      urgencyScore: 68,
      opportunityScore: 64,
      actionConfidence: 71,
      conversationTemperature: 58,
      stageMomentum: 'steady',
      riskSummary: 'Tenant access issue could delay title inspection and stall momentum.',
      riskFlags: ['Tenant access needed for title inspection'],
      objectionsDetected: ['Wants to avoid open market listing'],
      recommendedAction:
        'Offer a no-showing close path and introduce a same-week inspection slot to keep momentum high.',
      messages: [
        {
          id: 'msg-p3-1',
          direction: 'outbound',
          message:
            'We can buy the property as-is and skip the listing process entirely. Would a direct close this month help?',
          timestampIso: daysAgo(1),
          aiGenerated: true,
        },
        {
          id: 'msg-p3-2',
          direction: 'inbound',
          message: 'No showings is important. I do not want tenants involved.',
          timestampIso: hoursAgo(4),
        },
      ],
    },
    {
      id: 'p-atlanta-maple',
      marketId: 'm-atlanta',
      address: '78 Maple Ridge Court',
      city: 'Atlanta',
      stateCode: 'GA',
      zip: '30318',
      lat: 33.8032,
      lng: -84.4464,
      ownerName: 'Elizabeth Taylor',
      ownerType: 'estate',
      propertyType: 'Multi-Family',
      sentiment: 'warm',
      pipelineStage: 'responding',
      currentIntent: 'Relocating',
      estimatedValue: 348000,
      offerAmount: 296000,
      pipelineDays: 9,
      outboundAttempts: 5,
      lastOutboundIso: hoursAgo(3),
      lastInboundIso: hoursAgo(10),
      aiSummary:
        'Seller is coordinating a relocation timeline and wants certainty more than top-dollar pricing. Family stakeholders still need reassurance about the process.',
      heatFactors: ['Relocation timeline driving urgency', 'Certainty over spread — confirmed', 'Written steps requested — compliance signal'],
      urgencyScore: 62,
      opportunityScore: 59,
      actionConfidence: 68,
      conversationTemperature: 52,
      stageMomentum: 'steady',
      riskSummary: 'Multi-stakeholder process extends every step — written confirmation loop is still open.',
      riskFlags: ['Multi-stakeholder sign-off required', 'Written confirmation loop still open — do not skip'],
      objectionsDetected: ['Needs family alignment', 'Wants written next steps'],
      recommendedAction:
        'Send a clear two-step close outline and position the offer as a low-friction relocation exit.',
      messages: [
        {
          id: 'msg-p4-1',
          direction: 'outbound',
          message:
            'Elizabeth, we can structure a flexible close that lines up with your move and keeps the process simple for your family.',
          timestampIso: daysAgo(2),
          aiGenerated: true,
        },
        {
          id: 'msg-p4-2',
          direction: 'inbound',
          message: 'Send me the steps in writing and I will review it tonight.',
          timestampIso: hoursAgo(10),
        },
      ],
    },
    {
      id: 'p-phoenix-saguaro',
      marketId: 'm-phoenix',
      address: '4412 Saguaro Mesa Way',
      city: 'Phoenix',
      stateCode: 'AZ',
      zip: '85041',
      lat: 33.3944,
      lng: -112.0861,
      ownerName: 'Linda Wilson',
      ownerType: 'estate',
      propertyType: 'Vacant Land',
      sentiment: 'neutral',
      pipelineStage: 'responding',
      currentIntent: 'Inheritance',
      estimatedValue: 119000,
      offerAmount: 94000,
      pipelineDays: 18,
      outboundAttempts: 8,
      lastOutboundIso: hoursAgo(9),
      lastInboundIso: daysAgo(1),
      aiSummary:
        'Inherited parcel remains a low-priority asset for the seller. Interest is real but urgency is soft, and the current hold-up is trust in valuation accuracy.',
      heatFactors: ['Inherited asset — low emotional attachment', 'Open to offer in principle', 'Valuation objection surfaced — addressable'],
      urgencyScore: 38,
      opportunityScore: 41,
      actionConfidence: 55,
      conversationTemperature: 32,
      stageMomentum: 'stalling',
      riskSummary: 'Over-touch risk is real here — pause outreach and re-enter only with a valuation-backed offer.',
      riskFlags: ['Urgency soft — do not over-touch', 'Valuation trust gap unresolved', '3-day cooling window before re-entry recommended'],
      objectionsDetected: ['Needs valuation validation', 'Slow urgency'],
      recommendedAction:
        'Pause high-frequency outreach, then re-enter with a valuation-backed offer and a concise title-readiness note.',
      messages: [
        {
          id: 'msg-p5-1',
          direction: 'outbound',
          message:
            'Linda, we can make a direct offer on the inherited lot and handle the paperwork without putting it on the open market.',
          timestampIso: daysAgo(4),
          aiGenerated: true,
        },
        {
          id: 'msg-p5-2',
          direction: 'inbound',
          message: 'I am open to an offer, but I need to understand how you got your number.',
          timestampIso: daysAgo(1),
        },
      ],
    },
  ],
  agents: [
    {
      id: 'a-qualifier-alpha',
      name: 'Qualifier Alpha',
      specialty: 'Intent Classification',
      status: 'active',
      handledToday: 84,
      avgResponseMinutes: 1.9,
      successRate: 78,
      load: 66,
      marketId: 'm-minneapolis',
      focusLeadId: 'p-minneapolis-oak',
      activityLabel: 'AI routed hot lead to acquisition team',
      aiSummary:
        'Patricia Johnson crossed the high-intent threshold after message-two and is now sitting in a negotiation-ready band with strong close potential.',
    },
    {
      id: 'a-follow-up-beta',
      name: 'Follow-Up Beta',
      specialty: 'Auto-Response',
      status: 'watching',
      handledToday: 126,
      avgResponseMinutes: 2.4,
      successRate: 72,
      load: 81,
      marketId: 'm-atlanta',
      focusLeadId: 'p-atlanta-maple',
      activityLabel: 'Sent day-3 follow-up to 24 sellers',
      aiSummary:
        'Atlanta follow-up cadence is still productive, but opt-out pressure is climbing. Current recommendation is to lower day-three send velocity by one tier.',
    },
    {
      id: 'a-objection-handler',
      name: 'Objection Handler',
      specialty: 'AI Analysis',
      status: 'active',
      handledToday: 39,
      avgResponseMinutes: 3.6,
      successRate: 81,
      load: 58,
      marketId: 'm-minneapolis',
      focusLeadId: 'p-minneapolis-oak',
      activityLabel: 'Handling price objection in Minneapolis',
      aiSummary:
        'Current objection stack is price-first with comps as the unlock. Recommended messaging pattern is market-proof first, speed proof second, then offer anchor.',
    },
    {
      id: 'a-appointment-setter',
      name: 'Appointment Setter',
      specialty: 'Call',
      status: 'queued',
      handledToday: 17,
      avgResponseMinutes: 4.8,
      successRate: 64,
      load: 47,
      marketId: 'm-houston',
      focusLeadId: 'p-houston-briar',
      activityLabel: 'Booked call with Houston seller for 2pm',
      aiSummary:
        'Houston seller is responsive but time-sensitive. Appointment flow should stay concise and anchored to certainty rather than price exploration.',
    },
    {
      id: 'a-offer-negotiator',
      name: 'Offer Negotiator',
      specialty: 'Counter Received',
      status: 'active',
      handledToday: 11,
      avgResponseMinutes: 6.1,
      successRate: 69,
      load: 54,
      marketId: 'm-atlanta',
      focusLeadId: 'p-atlanta-maple',
      activityLabel: 'Counter-offer generated for Atlanta deal',
      aiSummary:
        'Atlanta relocation lead is still movable if we tighten the close timeline language and keep the next touch focused on certainty over spread.',
    },
  ],
  alerts: [
    {
      id: 'al-1',
      marketId: 'm-houston',
      severity: 'critical',
      priority: 'P0',
      title: 'Hot lead not contacted — 18-minute gap',
      detail: 'High-intent seller crossed the reply threshold but has not received the next touch. Conversion risk rises sharply after 20 minutes.',
      metricLabel: 'Queue age',
      metricValue: '18m',
      timestampIso: minutesAgo(18),
    },
    {
      id: 'al-2',
      marketId: 'm-dallas',
      severity: 'warning',
      priority: 'P2',
      title: 'Outbound queue above safe operating window',
      detail: 'Dallas send queue is 14% above target depth. Follow-up lag is expanding and delivery windows are at risk if not cleared within the hour.',
      metricLabel: 'Backlog',
      metricValue: '+14%',
      timestampIso: minutesAgo(24),
    },
    {
      id: 'al-3',
      marketId: 'm-atlanta',
      severity: 'warning',
      priority: 'P2',
      title: 'Opt-out rate breached operational guardrail',
      detail: 'Atlanta opt-out rate moved above the 1.2% compliance ceiling during the last send block. Continued sends may trigger carrier-level suppression.',
      metricLabel: 'Opt-out',
      metricValue: '1.4%',
      timestampIso: minutesAgo(31),
    },
    {
      id: 'al-4',
      marketId: 'm-atlanta',
      severity: 'critical',
      priority: 'P1',
      title: 'Carrier rejection surge — Atlanta segments degraded',
      detail: 'Carrier filtering elevated on two Atlanta segments after 10:00 AM. 22% of sends in the affected window are not reaching recipients. Route review required.',
      metricLabel: 'Rejects',
      metricValue: '+22%',
      timestampIso: minutesAgo(42),
    },
    {
      id: 'al-5',
      marketId: 'm-phoenix',
      severity: 'warning',
      priority: 'P3',
      title: 'Phoenix nurture track — 3-day messaging staleness',
      detail: 'Phoenix campaign has not been refreshed against current seller objection patterns. Stale messaging erodes response quality over time.',
      metricLabel: 'Idle',
      metricValue: '3.2d',
      timestampIso: hoursAgo(2),
    },
    {
      id: 'al-6',
      marketId: 'm-phoenix',
      severity: 'info',
      priority: 'P3',
      title: 'Reply rate drifting below portfolio baseline',
      detail: 'Phoenix engagement trending 0.8 points below portfolio average. Still within recoverable range — monitor for another 24 hours before intervention.',
      metricLabel: 'Reply rate',
      metricValue: '5.1%',
      timestampIso: hoursAgo(3),
    },
  ],
  activities: [
    {
      id: 'ev-1',
      marketId: 'm-minneapolis',
      kind: 'ai',
      severity: 'info',
      title: 'AI routed hot lead to acquisition team',
      detail: 'Qualifier Alpha escalated Patricia Johnson after a strong inbound signal.',
      timestampIso: minutesAgo(8),
    },
    {
      id: 'ev-2',
      marketId: 'm-minneapolis',
      kind: 'conversation',
      severity: 'info',
      title: 'AI generated response for objection handling',
      detail: 'Objection Handler drafted a comps-first reply for the Minneapolis seller.',
      timestampIso: minutesAgo(12),
    },
    {
      id: 'ev-3',
      marketId: 'm-houston',
      kind: 'conversation',
      severity: 'info',
      title: 'Booked call with Houston seller for 2pm',
      detail: 'Appointment Setter confirmed a same-day call window and seller intent remains warm.',
      timestampIso: minutesAgo(19),
    },
    {
      id: 'ev-4',
      marketId: 'm-atlanta',
      kind: 'deal',
      severity: 'warning',
      title: 'Counter-offer generated for Atlanta deal',
      detail: 'Offer Negotiator prepared a certainty-led revision for the relocating seller.',
      timestampIso: minutesAgo(27),
    },
    {
      id: 'ev-5',
      marketId: 'm-atlanta',
      kind: 'alert',
      severity: 'critical',
      title: 'Carrier rejection spike',
      detail: 'Atlanta routing degraded during the last batch and monitoring has elevated.',
      timestampIso: minutesAgo(42),
    },
    {
      id: 'ev-6',
      marketId: 'm-dallas',
      kind: 'system',
      severity: 'warning',
      title: 'Send queue backlog',
      detail: 'Dallas queue depth is above operating target and follow-up backlog expanded.',
      timestampIso: minutesAgo(50),
    },
    {
      id: 'ev-7',
      marketId: 'm-houston',
      kind: 'deal',
      severity: 'info',
      title: 'Clean title confirmed',
      detail: 'Houston file cleared title review and is ready for next-stage negotiation.',
      timestampIso: hoursAgo(2),
    },
    {
      id: 'ev-8',
      marketId: 'm-dallas',
      kind: 'deal',
      severity: 'info',
      title: 'Deal advanced to Under Contract',
      detail: 'Dallas lead moved into contract prep after proof-of-funds was acknowledged.',
      timestampIso: hoursAgo(3),
    },
    {
      id: 'ev-9',
      marketId: 'm-atlanta',
      kind: 'deal',
      severity: 'info',
      title: 'Closing set for Friday at 2pm',
      detail: 'Atlanta seller approved the target window and closing coordination is live.',
      timestampIso: hoursAgo(6),
    },
    {
      id: 'ev-10',
      marketId: 'm-phoenix',
      kind: 'system',
      severity: 'warning',
      title: 'Campaign stale',
      detail: 'Phoenix nurture path needs refreshed intent messaging before the next send window.',
      timestampIso: hoursAgo(9),
    },
  ],
  systemHealth: [
    {
      id: 'outbound-queue',
      label: 'Queue',
      status: 'warning',
      value: '71 pending',
      detail: 'Dallas send queue 14% above target',
      lastUpdatedIso: minutesAgo(1),
    },
    {
      id: 'routing',
      label: 'Routing',
      status: 'degraded',
      value: '+22% rejects',
      detail: 'Atlanta carrier spike active',
      lastUpdatedIso: minutesAgo(2),
    },
    {
      id: 'reply-engine',
      label: 'Reply Engine',
      status: 'healthy',
      value: '5.5% rate',
      detail: 'All markets nominal',
      lastUpdatedIso: minutesAgo(4),
    },
    {
      id: 'ai-agents',
      label: 'AI Agents',
      status: 'healthy',
      value: '3/5 active',
      detail: 'All priority handles covered',
      lastUpdatedIso: minutesAgo(8),
    },
    {
      id: 'number-health',
      label: 'Numbers',
      status: 'healthy',
      value: '96.1% del.',
      detail: 'No carrier suppression detected',
      lastUpdatedIso: minutesAgo(6),
    },
    {
      id: 'data-sync',
      label: 'Data Sync',
      status: 'healthy',
      value: 'Live',
      detail: 'Last sweep 4m ago',
      lastUpdatedIso: minutesAgo(4),
    },
  ],
  mapLinks: [
    { id: 'ln-1', fromMarketId: 'm-phoenix', toMarketId: 'm-dallas', volume: 18 },
    { id: 'ln-2', fromMarketId: 'm-dallas', toMarketId: 'm-houston', volume: 24 },
    { id: 'ln-3', fromMarketId: 'm-dallas', toMarketId: 'm-atlanta', volume: 16 },
    { id: 'ln-4', fromMarketId: 'm-minneapolis', toMarketId: 'm-dallas', volume: 11 },
    { id: 'ln-5', fromMarketId: 'm-houston', toMarketId: 'm-atlanta', volume: 13 },
  ],
  inboxThreads: [
    {
      id: 'inbox-1',
      leadId: 'p-minneapolis-oak',
      marketId: 'm-minneapolis',
      ownerName: 'Patricia Johnson',
      subject: 'RE: Cash Offer — 3847 Oak Street',
      preview: 'I need to see comparable sales before committing to anything.',
      status: 'unread',
      priority: 'urgent',
      sentiment: 'hot',
      messageCount: 4,
      lastMessageIso: minutesAgo(14),
      unreadCount: 1,
      aiDraft: 'Patricia, here is the updated comp package for your area. Three recent sales within 0.3 miles support our valuation. Happy to jump on a call today.',
      labels: ['hot-lead', 'negotiation'],
    },
    {
      id: 'inbox-2',
      leadId: 'p-dallas-grove',
      marketId: 'm-dallas',
      ownerName: 'David Anderson',
      subject: 'Tax deadline question',
      preview: 'If you can close quickly, I want to hear the number.',
      status: 'unread',
      priority: 'high',
      sentiment: 'warm',
      messageCount: 3,
      lastMessageIso: hoursAgo(6),
      unreadCount: 1,
      aiDraft: 'David, we can absolutely close before your tax deadline. Here is our firm offer with a guarantee on the timeline.',
      labels: ['tax-delinquent', 'time-sensitive'],
    },
    {
      id: 'inbox-3',
      leadId: 'p-houston-briar',
      marketId: 'm-houston',
      ownerName: 'William Moore',
      subject: 'RE: No-showing close path',
      preview: 'No showings is important. I do not want tenants involved.',
      status: 'read',
      priority: 'normal',
      sentiment: 'warm',
      messageCount: 3,
      lastMessageIso: hoursAgo(4),
      unreadCount: 0,
      aiDraft: 'William, understood completely — we will handle the inspection without disturbing your tenants. Here is the timeline.',
      labels: ['tired-landlord'],
    },
    {
      id: 'inbox-4',
      leadId: 'p-atlanta-maple',
      marketId: 'm-atlanta',
      ownerName: 'Elizabeth Taylor',
      subject: 'Written steps requested',
      preview: 'Send me the steps in writing and I will review it tonight.',
      status: 'read',
      priority: 'normal',
      sentiment: 'warm',
      messageCount: 3,
      lastMessageIso: hoursAgo(10),
      unreadCount: 0,
      aiDraft: null,
      labels: ['relocating', 'multi-stakeholder'],
    },
    {
      id: 'inbox-5',
      leadId: 'p-phoenix-saguaro',
      marketId: 'm-phoenix',
      ownerName: 'Linda Wilson',
      subject: 'RE: Direct offer on inherited lot',
      preview: 'I am open to an offer, but I need to understand how you got your number.',
      status: 'replied',
      priority: 'low',
      sentiment: 'neutral',
      messageCount: 3,
      lastMessageIso: daysAgo(1),
      unreadCount: 0,
      aiDraft: null,
      labels: ['inheritance', 'valuation-gap'],
    },
  ],
  buyerProfiles: [
    {
      id: 'buyer-1',
      name: 'Riverside Capital Partners',
      marketIds: ['m-dallas', 'm-houston'],
      intent: 'active',
      budget: 5000000,
      targetPropertyTypes: ['SFR', 'Duplex'],
      targetZips: ['75217', '75228', '77084', '77095'],
      matchScore: 94,
      lastActivityIso: hoursAgo(2),
      acquisitionsYTD: 23,
      avgDaysToClose: 12,
      preApproved: true,
      notes: 'Aggressive buyer, prefers bulk packages, fast close. Currently looking for 10+ units in DFW and Houston metro.',
    },
    {
      id: 'buyer-2',
      name: 'Oakwood Holdings LLC',
      marketIds: ['m-atlanta', 'm-minneapolis'],
      intent: 'active',
      budget: 3200000,
      targetPropertyTypes: ['Multi-Family', 'Duplex'],
      targetZips: ['30318', '30349', '55408', '55411'],
      matchScore: 87,
      lastActivityIso: hoursAgo(8),
      acquisitionsYTD: 14,
      avgDaysToClose: 18,
      preApproved: true,
      notes: 'Focus on multi-family value-add. Willing to take on light rehab. Strong track record in Southeast markets.',
    },
    {
      id: 'buyer-3',
      name: 'DesertView Investments',
      marketIds: ['m-phoenix'],
      intent: 'passive',
      budget: 1800000,
      targetPropertyTypes: ['Vacant Land', 'SFR'],
      targetZips: ['85041', '85033', '85009'],
      matchScore: 72,
      lastActivityIso: daysAgo(3),
      acquisitionsYTD: 6,
      avgDaysToClose: 24,
      preApproved: false,
      notes: 'Selective buyer focused on Phoenix metro only. Needs valuation documentation before making offers.',
    },
    {
      id: 'buyer-4',
      name: 'Metro Flip Group',
      marketIds: ['m-dallas', 'm-houston', 'm-atlanta'],
      intent: 'watching',
      budget: 2400000,
      targetPropertyTypes: ['SFR'],
      targetZips: ['75217', '77084', '30318'],
      matchScore: 68,
      lastActivityIso: daysAgo(7),
      acquisitionsYTD: 9,
      avgDaysToClose: 21,
      preApproved: true,
      notes: 'Fix-and-flip operator. Paused buying temporarily due to contractor availability. Expected back Q2.',
    },
  ],
  titleRecords: [
    {
      id: 'title-1',
      leadId: 'p-minneapolis-oak',
      marketId: 'm-minneapolis',
      address: '3847 Oak Street, Minneapolis, MN 55408',
      ownerName: 'Patricia Johnson',
      status: 'review',
      closingPhase: 'title-ordered',
      titleCompany: 'Northern Title & Escrow',
      scheduledCloseIso: null,
      daysInPhase: 3,
      earnestDeposit: 5000,
      purchasePrice: 138000,
      issues: ['Comp variance under review'],
      lastUpdatedIso: hoursAgo(4),
    },
    {
      id: 'title-2',
      leadId: 'p-dallas-grove',
      marketId: 'm-dallas',
      address: '912 Grove View Lane, Dallas, TX 75217',
      ownerName: 'David Anderson',
      status: 'pending',
      closingPhase: 'title-ordered',
      titleCompany: 'Lone Star Title Co.',
      scheduledCloseIso: null,
      daysInPhase: 2,
      earnestDeposit: 3500,
      purchasePrice: 176000,
      issues: ['Title review not yet initiated', 'Tax lien clearance needed'],
      lastUpdatedIso: hoursAgo(6),
    },
    {
      id: 'title-3',
      leadId: 'p-houston-briar',
      marketId: 'm-houston',
      address: '2215 Briar Creek Drive, Houston, TX 77084',
      ownerName: 'William Moore',
      status: 'clear',
      closingPhase: 'closing-scheduled',
      titleCompany: 'Gulf Coast Title',
      scheduledCloseIso: daysAgo(-3),
      daysInPhase: 5,
      earnestDeposit: 7500,
      purchasePrice: 239000,
      issues: [],
      lastUpdatedIso: hoursAgo(2),
    },
    {
      id: 'title-4',
      leadId: 'p-atlanta-maple',
      marketId: 'm-atlanta',
      address: '78 Maple Ridge Court, Atlanta, GA 30318',
      ownerName: 'Elizabeth Taylor',
      status: 'issue',
      closingPhase: 'title-ordered',
      titleCompany: 'Peach State Title',
      scheduledCloseIso: null,
      daysInPhase: 4,
      earnestDeposit: 10000,
      purchasePrice: 296000,
      issues: ['Multi-stakeholder sign-off required', 'Estate documentation incomplete'],
      lastUpdatedIso: hoursAgo(10),
    },
  ],
  autopilotEvents: [
    {
      id: 'ap-1',
      action: 'escalate',
      marketId: 'm-houston',
      leadId: 'p-houston-briar',
      title: 'Hot lead escalated to acquisition queue',
      detail: 'Reply sentiment crossed the high-intent threshold. Moved to priority follow-up lane.',
      confidence: 94,
      approved: true,
      timestampIso: minutesAgo(3),
    },
    {
      id: 'ap-2',
      action: 'send',
      marketId: 'm-minneapolis',
      leadId: 'p-minneapolis-oak',
      title: 'Comp package auto-generated and queued',
      detail: 'AI generated a valuation-backed comp package for Patricia Johnson based on detected price objection.',
      confidence: 88,
      approved: false,
      timestampIso: minutesAgo(7),
    },
    {
      id: 'ap-3',
      action: 'pause',
      marketId: 'm-phoenix',
      leadId: 'p-phoenix-saguaro',
      title: 'Outreach paused — cooling window active',
      detail: 'Low urgency score triggered a 3-day cooling period. Re-entry scheduled with valuation-backed messaging.',
      confidence: 82,
      approved: true,
      timestampIso: minutesAgo(15),
    },
    {
      id: 'ap-4',
      action: 'match',
      marketId: 'm-dallas',
      leadId: 'p-dallas-grove',
      title: 'Buyer match: Riverside Capital Partners',
      detail: 'Dallas duplex matches buyer criteria. Match score 94%. Buyer has budget and is pre-approved.',
      confidence: 91,
      approved: false,
      timestampIso: minutesAgo(22),
    },
    {
      id: 'ap-5',
      action: 'alert',
      marketId: 'm-atlanta',
      leadId: null,
      title: 'Market pressure warning — Atlanta opt-out rising',
      detail: 'System detected opt-out rate crossing the 1.2% compliance ceiling. Recommending send velocity reduction.',
      confidence: 96,
      approved: true,
      timestampIso: minutesAgo(31),
    },
    {
      id: 'ap-6',
      action: 'schedule',
      marketId: 'm-houston',
      leadId: 'p-houston-briar',
      title: 'Closing call auto-scheduled',
      detail: 'AI detected closing readiness signals and scheduled a confirmation call with the seller for tomorrow 2pm.',
      confidence: 79,
      approved: false,
      timestampIso: minutesAgo(40),
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      kind: 'autopilot',
      severity: 'critical',
      title: 'Hot lead waiting — 18min queue gap',
      detail: 'Houston hot lead has not received follow-up. Auto-escalation triggered.',
      read: false,
      actionLabel: 'View Lead',
      actionRoute: '/dashboard/live',
      timestampIso: minutesAgo(2),
    },
    {
      id: 'notif-2',
      kind: 'deal',
      severity: 'info',
      title: 'Title cleared — Houston file ready',
      detail: 'Briar Creek Drive title is clean. Closing can proceed.',
      read: false,
      actionLabel: 'View Title',
      actionRoute: '/title',
      timestampIso: minutesAgo(8),
    },
    {
      id: 'notif-3',
      kind: 'autopilot',
      severity: 'warning',
      title: 'Buyer match pending approval',
      detail: 'Riverside Capital Partners matched to Dallas duplex. Confidence 94%.',
      read: false,
      actionLabel: 'Review Match',
      actionRoute: '/buyer',
      timestampIso: minutesAgo(22),
    },
    {
      id: 'notif-4',
      kind: 'alert',
      severity: 'warning',
      title: 'Atlanta carrier rejection spike',
      detail: '22% of sends in affected window are not reaching recipients.',
      read: true,
      actionLabel: 'View Alerts',
      actionRoute: '/alerts',
      timestampIso: minutesAgo(42),
    },
    {
      id: 'notif-5',
      kind: 'inbox',
      severity: 'info',
      title: 'New reply from Patricia Johnson',
      detail: 'Minneapolis seller responded about comparable sales.',
      read: true,
      actionLabel: 'Open Thread',
      actionRoute: '/inbox',
      timestampIso: minutesAgo(14),
    },
  ],
  watchlists: [
    {
      id: 'watch-1',
      type: 'lead',
      targetId: 'p-minneapolis-oak',
      label: 'Patricia Johnson — Hot negotiation',
      notes: 'Comp dispute near resolution. Watch for close signal.',
      addedIso: daysAgo(2),
      alertOnChange: true,
    },
    {
      id: 'watch-2',
      type: 'market',
      targetId: 'm-atlanta',
      label: 'Atlanta — Elevated risk',
      notes: 'Carrier issues and opt-out pressure. Monitor daily.',
      addedIso: daysAgo(1),
      alertOnChange: true,
    },
    {
      id: 'watch-3',
      type: 'zip',
      targetId: '75217',
      label: 'Dallas 75217 — Top ZIP',
      notes: 'Highest outbound volume ZIP. Tracking conversion trends.',
      addedIso: daysAgo(5),
      alertOnChange: false,
    },
    {
      id: 'watch-4',
      type: 'agent',
      targetId: 'a-follow-up-beta',
      label: 'Follow-Up Beta — Load watch',
      notes: 'Agent load at 81%. Watch for capacity breach.',
      addedIso: daysAgo(3),
      alertOnChange: true,
    },
  ],
}
