-- -----------------------------------------------------------------------------
-- ops_notifications
--
-- Dedup table for system-triggered proactive Discord ops alerts.
-- notification_key ensures each unique signal generates at most one alert
-- per dedup window.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ops_notifications (
  id                  bigserial PRIMARY KEY,
  notification_key    text        NOT NULL,
  notification_type   text        NOT NULL,
  severity            text        NOT NULL DEFAULT 'info',
  campaign_key        text,
  title               text        NOT NULL,
  message             text,
  metrics             jsonb,
  recommended_action  text,
  discord_channel_id  text,
  discord_message_id  text,
  status              text        NOT NULL DEFAULT 'pending',
  dispatched_at       timestamptz,
  expires_at          timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ops_notifications_key
  ON public.ops_notifications (notification_key);

CREATE INDEX IF NOT EXISTS idx_ops_notifications_status
  ON public.ops_notifications (status);

CREATE INDEX IF NOT EXISTS idx_ops_notifications_created_at
  ON public.ops_notifications (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ops_notifications_campaign_key
  ON public.ops_notifications (campaign_key)
  WHERE campaign_key IS NOT NULL;

COMMENT ON TABLE  public.ops_notifications IS 'Dedup log for system-triggered proactive Discord ops alerts.';
COMMENT ON COLUMN public.ops_notifications.notification_key IS 'Unique dedup key — upsert target, one row per signal per window.';
COMMENT ON COLUMN public.ops_notifications.notification_type IS 'Type tag: campaign_scale | campaign_pause | hot_lead | system_health | etc.';
COMMENT ON COLUMN public.ops_notifications.severity IS 'info | warning | critical';
COMMENT ON COLUMN public.ops_notifications.status IS 'pending | dispatched | acknowledged | expired';
COMMENT ON COLUMN public.ops_notifications.expires_at IS 'ISO timestamp after which the notification is considered stale.';

-- -----------------------------------------------------------------------------
-- campaign_approval_requests
--
-- Tracks proactive scale/pause approvals initiated by the ops check.
-- Actions are approval-gated before any campaign mutations occur.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.campaign_approval_requests (
  id              bigserial PRIMARY KEY,
  request_key     text        NOT NULL,
  request_type    text        NOT NULL,
  campaign_key    text        NOT NULL,
  campaign_id     text,
  market          text,
  asset           text,
  strategy        text,
  current_cap     integer,
  proposed_cap    integer,
  reason          text,
  metrics         jsonb,
  status          text        NOT NULL DEFAULT 'pending',
  requester       text,
  approved_by     text,
  approved_at     timestamptz,
  rejected_by     text,
  rejected_at     timestamptz,
  expires_at      timestamptz,
  notification_id bigint REFERENCES public.ops_notifications (id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_campaign_approval_requests_key
  ON public.campaign_approval_requests (request_key);

CREATE INDEX IF NOT EXISTS idx_campaign_approval_requests_status
  ON public.campaign_approval_requests (status);

CREATE INDEX IF NOT EXISTS idx_campaign_approval_requests_campaign_key
  ON public.campaign_approval_requests (campaign_key);

CREATE INDEX IF NOT EXISTS idx_campaign_approval_requests_created_at
  ON public.campaign_approval_requests (created_at DESC);

COMMENT ON TABLE  public.campaign_approval_requests IS 'Approval-gated campaign scale/pause requests generated by proactive ops checks.';
COMMENT ON COLUMN public.campaign_approval_requests.request_key IS 'Unique dedup key for the approval request.';
COMMENT ON COLUMN public.campaign_approval_requests.request_type IS 'scale | pause | hold | inspect';
COMMENT ON COLUMN public.campaign_approval_requests.status IS 'pending | approved | rejected | expired | cancelled';
COMMENT ON COLUMN public.campaign_approval_requests.expires_at IS 'ISO timestamp after which the request can no longer be actioned.';

-- -----------------------------------------------------------------------------
-- ops_recommendations
--
-- Stores individual campaign health recommendations produced by analyzeCampaignHealth.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ops_recommendations (
  id                  bigserial PRIMARY KEY,
  campaign_key        text        NOT NULL,
  recommendation_type text        NOT NULL,
  reason              text,
  confidence          numeric(4,3),
  metrics             jsonb,
  actioned            boolean     NOT NULL DEFAULT false,
  actioned_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ops_recommendations_campaign_key
  ON public.ops_recommendations (campaign_key);

CREATE INDEX IF NOT EXISTS idx_ops_recommendations_created_at
  ON public.ops_recommendations (created_at DESC);

COMMENT ON TABLE  public.ops_recommendations IS 'Campaign health recommendations from proactive ops analysis.';

-- -----------------------------------------------------------------------------
-- discord_action_audit
--
-- Immutable log of every button-press that triggers a proactive ops action.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.discord_action_audit (
  id              bigserial PRIMARY KEY,
  request_key     text,
  action_type     text        NOT NULL,
  actor_user_id   text,
  actor_username  text,
  guild_id        text,
  channel_id      text,
  message_id      text,
  outcome         text        NOT NULL,
  details         jsonb,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_discord_action_audit_request_key
  ON public.discord_action_audit (request_key)
  WHERE request_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_discord_action_audit_created_at
  ON public.discord_action_audit (created_at DESC);

COMMENT ON TABLE  public.discord_action_audit IS 'Immutable audit log for button-press actions on proactive ops notifications.';
COMMENT ON COLUMN public.discord_action_audit.action_type IS 'campaign_scale | campaign_pause | hold | inspect';
COMMENT ON COLUMN public.discord_action_audit.outcome IS 'approved | rejected | held | inspected | expired | unauthorized';
