export type InboxSavedFilterPreset =
  | 'archived'
  // Sidebar sub-views, exactly like 'archived'. Every category chip routes its
  // click through viewToPreset -> applySavedPreset, so a view with no preset
  // silently resolves to 'all_messages' and the chip appears to do nothing.
  | 'snoozed'
  | 'scheduled'
  | 'my_priority'
  | 'new_inbounds'
  | 'offer_needed'
  | 'review_required'
  | 'wrong_numbers'
  | 'suppressed'
  | 'language_focus'
  | 'high_motivation'
  | 'starred'
  | 'pinned'
  | 'unassigned'
  | 'all_messages'
  | 'waiting'
  | 'inbound_only'
  | 'outbound_only'
  | 'needs_reply'
  | 'auto_replied'
  | 'auto_reply_failed'
  | 'positive_hot'
  | 'offer_requested'
  | 'opt_out'
  | 'manual_review'
  | 'missing_context'
  | 'all_inbound'
  | 'inbound_all'
