/**
 * Client-side mirror of apps/api/src/lib/domain/inbox/inbox-filter-catalog.js
 * Ensures Advanced Map Filters always renders the full Inbox field set even if the catalog API is unreachable.
 */
import type { FilterCatalogField, FilterCatalogGroup } from './inbox-filter-api'

export const INBOX_FILTER_GROUPS: FilterCatalogGroup[] = [
  { id: 'conversation', label: 'Inbox & Conversation', icon: 'inbox' },
  { id: 'property', label: 'Property', icon: 'home' },
  { id: 'financials', label: 'Financials', icon: 'dollar' },
  { id: 'condition', label: 'Condition', icon: 'tool' },
  { id: 'distress', label: 'Distress & Flags', icon: 'alert' },
  { id: 'prospect', label: 'Prospect', icon: 'user' },
  { id: 'owner', label: 'Owner & Portfolio', icon: 'briefcase' },
  { id: 'phone', label: 'Phone & Delivery', icon: 'phone' },
  { id: 'email', label: 'Email & Eligibility', icon: 'mail' },
]

export const INBOX_FILTER_FIELDS: FilterCatalogField[] = [
  { key: 'inboxCategory', group: 'conversation', label: 'Inbox Category', type: 'select', optionsKey: 'inbox_categories' },
  { key: 'stage', group: 'conversation', label: 'Stage', type: 'select', optionsKey: 'stages' },
  { key: 'status', group: 'conversation', label: 'Universal Status', type: 'select', optionsKey: 'statuses' },
  { key: 'intent', group: 'conversation', label: 'Detected Intent', type: 'select', optionsKey: 'intents' },
  { key: 'leadTemperature', group: 'conversation', label: 'Lead Temperature', type: 'select', optionsKey: 'temperatures' },
  { key: 'isRead', group: 'conversation', label: 'Read Status', type: 'tri' },
  { key: 'isStarred', group: 'conversation', label: 'Starred', type: 'tri' },
  { key: 'isPinned', group: 'conversation', label: 'Pinned', type: 'tri' },
  { key: 'isArchived', group: 'conversation', label: 'Archived', type: 'tri' },
  { key: 'isSuppressed', group: 'conversation', label: 'Suppressed', type: 'tri' },
  { key: 'direction', group: 'conversation', label: 'Latest Direction', type: 'select', optionsKey: 'directions' },
  { key: 'deliveryStatus', group: 'conversation', label: 'Delivery Status', type: 'select', optionsKey: 'delivery_statuses' },
  { key: 'automationStatus', group: 'conversation', label: 'Automation Status', type: 'select', optionsKey: 'automation_statuses' },
  { key: 'messageCountMin', group: 'conversation', label: 'Message Count', type: 'numberRange' },
  { key: 'inboundCountMin', group: 'conversation', label: 'Inbound Count', type: 'numberRange' },
  { key: 'outboundCountMin', group: 'conversation', label: 'Outbound Count', type: 'numberRange' },
  { key: 'activityDateFrom', group: 'conversation', label: 'Last Activity', type: 'dateRange' },
  { key: 'lastInboundDateFrom', group: 'conversation', label: 'Last Inbound', type: 'dateRange' },
  { key: 'lastOutboundDateFrom', group: 'conversation', label: 'Last Outbound', type: 'dateRange' },
  { key: 'followUpAtFrom', group: 'conversation', label: 'Follow-Up Date', type: 'dateRange' },
  { key: 'hasSellerReply', group: 'conversation', label: 'Has Replied', type: 'tri' },

  { key: 'addressSearch', group: 'property', label: 'Address Search', type: 'text' },
  { key: 'city', group: 'property', label: 'City', type: 'select', optionsKey: 'cities' },
  { key: 'state', group: 'property', label: 'State', type: 'select', optionsKey: 'states' },
  { key: 'zip', group: 'property', label: 'ZIP', type: 'text' },
  { key: 'county', group: 'property', label: 'County', type: 'select', optionsKey: 'counties' },
  { key: 'market', group: 'property', label: 'Market', type: 'select', optionsKey: 'markets' },
  { key: 'marketRegion', group: 'property', label: 'Market Region', type: 'select', optionsKey: 'market_regions' },
  { key: 'propertyType', group: 'property', label: 'Property Type', type: 'select', optionsKey: 'property_types' },
  { key: 'propertyClass', group: 'property', label: 'Property Class', type: 'select', optionsKey: 'property_classes' },
  { key: 'unitsMin', group: 'property', label: 'Units', type: 'numberRange' },
  { key: 'bedsMin', group: 'property', label: 'Bedrooms', type: 'numberRange' },
  { key: 'bathsMin', group: 'property', label: 'Bathrooms', type: 'numberRange' },
  { key: 'sqftMin', group: 'property', label: 'Building Sq Ft', type: 'numberRange' },
  { key: 'lotSqftMin', group: 'property', label: 'Lot Sq Ft', type: 'numberRange' },
  { key: 'lotAcreageMin', group: 'property', label: 'Lot Acreage', type: 'numberRange' },
  { key: 'yearBuiltMin', group: 'property', label: 'Year Built', type: 'numberRange' },
  { key: 'effectiveYearBuiltMin', group: 'property', label: 'Effective Year Built', type: 'numberRange' },
  { key: 'ownershipYearsMin', group: 'property', label: 'Ownership Years', type: 'numberRange' },
  { key: 'lastSaleDateFrom', group: 'property', label: 'Last Sale Date', type: 'dateRange' },
  { key: 'lastSalePriceMin', group: 'property', label: 'Last Sale Price', type: 'numberRange' },
  { key: 'assessedValueMin', group: 'property', label: 'Assessed Value', type: 'numberRange' },
  { key: 'estimatedValueMin', group: 'property', label: 'Estimated Value', type: 'numberRange' },
  { key: 'arvMin', group: 'property', label: 'ARV', type: 'numberRange' },
  { key: 'cashOfferMin', group: 'property', label: 'Cash Offer', type: 'numberRange' },

  { key: 'equityAmountMin', group: 'financials', label: 'Equity Amount', type: 'numberRange' },
  { key: 'equityPercentMin', group: 'financials', label: 'Equity %', type: 'numberRange' },
  { key: 'totalLoanAmtMin', group: 'financials', label: 'Total Loan Amount', type: 'numberRange' },
  { key: 'mortgageBalanceMin', group: 'financials', label: 'Loan Balance', type: 'numberRange' },
  { key: 'loanPaymentMin', group: 'financials', label: 'Loan Payment', type: 'numberRange' },
  { key: 'taxAmtMin', group: 'financials', label: 'Tax Amount', type: 'numberRange' },
  { key: 'pastDueAmountMin', group: 'financials', label: 'Past Due Amount', type: 'numberRange' },
  { key: 'repairCostMin', group: 'financials', label: 'Estimated Repair Cost', type: 'numberRange' },
  { key: 'aiScoreMin', group: 'financials', label: 'AI Score', type: 'numberRange' },
  { key: 'finalAcquisitionScoreMin', group: 'financials', label: 'Final Acquisition Score', type: 'numberRange' },
  { key: 'dealStrengthScoreMin', group: 'financials', label: 'Deal Strength Score', type: 'numberRange' },
  { key: 'priorityScoreMin', group: 'financials', label: 'Priority Score', type: 'numberRange' },

  { key: 'buildingCondition', group: 'condition', label: 'Building Condition', type: 'select', optionsKey: 'building_conditions' },
  { key: 'buildingQuality', group: 'condition', label: 'Building Quality', type: 'select', optionsKey: 'building_qualities' },
  { key: 'rehabLevel', group: 'condition', label: 'Rehab Level', type: 'select', optionsKey: 'rehab_levels' },
  { key: 'constructionType', group: 'condition', label: 'Construction Type', type: 'select', optionsKey: 'construction_types' },
  { key: 'style', group: 'condition', label: 'Style', type: 'select', optionsKey: 'styles' },
  { key: 'storiesMin', group: 'condition', label: 'Stories', type: 'numberRange' },
  { key: 'basement', group: 'condition', label: 'Basement', type: 'select', optionsKey: 'basements' },
  { key: 'garage', group: 'condition', label: 'Garage', type: 'select', optionsKey: 'garages' },
  { key: 'airConditioning', group: 'condition', label: 'Air Conditioning', type: 'select', optionsKey: 'air_conditionings' },
  { key: 'heatingType', group: 'condition', label: 'Heating Type', type: 'select', optionsKey: 'heating_types' },
  { key: 'roofType', group: 'condition', label: 'Roof Type', type: 'select', optionsKey: 'roof_types' },
  { key: 'pool', group: 'condition', label: 'Pool', type: 'select', optionsKey: 'pools' },
  { key: 'zoning', group: 'condition', label: 'Zoning', type: 'select', optionsKey: 'zonings' },
  { key: 'floodZone', group: 'condition', label: 'Flood Zone', type: 'select', optionsKey: 'flood_zones' },

  { key: 'propertyFlags', group: 'distress', label: 'Property Flags', type: 'flags' },
  { key: 'taxDelinquent', group: 'distress', label: 'Tax Delinquent', type: 'tri' },
  { key: 'activeLien', group: 'distress', label: 'Active Lien', type: 'tri' },

  { key: 'prospectAgeMin', group: 'prospect', label: 'Prospect Age', type: 'numberRange' },
  { key: 'gender', group: 'prospect', label: 'Gender', type: 'select', optionsKey: 'genders' },
  { key: 'maritalStatus', group: 'prospect', label: 'Marital Status', type: 'select', optionsKey: 'marital_statuses' },
  { key: 'education', group: 'prospect', label: 'Education', type: 'select', optionsKey: 'educations' },
  { key: 'occupationGroup', group: 'prospect', label: 'Occupation Group', type: 'select', optionsKey: 'occupation_groups' },
  { key: 'occupation', group: 'prospect', label: 'Occupation', type: 'select', optionsKey: 'occupations' },
  { key: 'householdIncome', group: 'prospect', label: 'Household Income', type: 'select', optionsKey: 'household_incomes' },
  { key: 'netAssetValue', group: 'prospect', label: 'Net Asset Value', type: 'select', optionsKey: 'net_asset_values' },
  { key: 'buyingPowerMin', group: 'prospect', label: 'Buying Power', type: 'numberRange' },
  { key: 'language', group: 'prospect', label: 'Language', type: 'select', optionsKey: 'languages' },
  { key: 'likelyOwner', group: 'prospect', label: 'Likely Owner', type: 'tri' },
  { key: 'likelyRenting', group: 'prospect', label: 'Likely Renting', type: 'tri' },
  { key: 'prospectContactScoreMin', group: 'prospect', label: 'Contact Score', type: 'numberRange' },
  { key: 'prospectPhoneScoreMin', group: 'prospect', label: 'Phone Score', type: 'numberRange' },
  { key: 'personFlags', group: 'prospect', label: 'Person Flags', type: 'flags' },
  { key: 'smsEligible', group: 'prospect', label: 'SMS Eligible', type: 'tri' },
  { key: 'emailEligible', group: 'prospect', label: 'Email Eligible', type: 'tri' },

  { key: 'ownerName', group: 'owner', label: 'Owner Name', type: 'text' },
  { key: 'ownerType', group: 'owner', label: 'Owner Type', type: 'select', optionsKey: 'owner_types' },
  { key: 'corporateOwner', group: 'owner', label: 'Corporate Owner', type: 'tri' },
  { key: 'absenteeOwner', group: 'owner', label: 'Absentee Owner', type: 'tri' },
  { key: 'ownerMailingSearch', group: 'owner', label: 'Mailing Address', type: 'text' },
  { key: 'contactabilityScoreMin', group: 'owner', label: 'Contactability Score', type: 'numberRange' },
  { key: 'financialPressureScoreMin', group: 'owner', label: 'Financial Pressure', type: 'numberRange' },
  { key: 'urgencyScoreMin', group: 'owner', label: 'Urgency Score', type: 'numberRange' },
  { key: 'ownerPriorityScoreMin', group: 'owner', label: 'Owner Priority Score', type: 'numberRange' },
  { key: 'ownerPriorityTier', group: 'owner', label: 'Priority Tier', type: 'select', optionsKey: 'priority_tiers' },
  { key: 'portfolioValueMin', group: 'owner', label: 'Portfolio Value', type: 'numberRange' },
  { key: 'portfolioEquityMin', group: 'owner', label: 'Portfolio Equity', type: 'numberRange' },
  { key: 'portfolioLoanBalanceMin', group: 'owner', label: 'Portfolio Loan Balance', type: 'numberRange' },
  { key: 'portfolioUnitsMin', group: 'owner', label: 'Portfolio Units', type: 'numberRange' },
  { key: 'propertyCountMin', group: 'owner', label: 'Property Count', type: 'numberRange' },
  { key: 'taxDelinquentCountMin', group: 'owner', label: 'Tax Delinquent Count', type: 'numberRange' },
  { key: 'activeLienCountMin', group: 'owner', label: 'Active Lien Count', type: 'numberRange' },

  { key: 'phoneNumber', group: 'phone', label: 'Phone Number', type: 'text' },
  { key: 'phoneCarrier', group: 'phone', label: 'Phone Carrier', type: 'select', optionsKey: 'phone_carriers' },
  { key: 'wrongNumber', group: 'phone', label: 'Wrong Number', type: 'tri' },
  { key: 'contactWindow', group: 'phone', label: 'Contact Window', type: 'select', optionsKey: 'contact_windows' },
  { key: 'pendingQueueCountMin', group: 'phone', label: 'Pending Queue Count', type: 'numberRange' },

  { key: 'hasEmail', group: 'email', label: 'Has Email', type: 'tri' },
  { key: 'emailScoreMin', group: 'email', label: 'Email Score', type: 'numberRange' },
]

export const INBOX_FILTER_CATALOG = {
  source: 'inbox_command_center_v',
  groups: INBOX_FILTER_GROUPS,
  fields: INBOX_FILTER_FIELDS,
}

export const INBOX_FILTER_FIELD_COUNT = INBOX_FILTER_FIELDS.length