import type { NexusCoreState, OrbStateConfig } from '../types/orb';

export const ORB_STATES: Record<NexusCoreState, OrbStateConfig> = {
  idle: {
    label: 'Nexus Core',
    color: 'var(--nx-cyan)',
    pulseSpeed: 3,
    glowIntensity: 0.4,
    ringSpeed: 1,
    particleDensity: 5,
    scale: 1,
  },
  reply: {
    label: 'New Message',
    color: 'var(--nx-electric-blue)',
    pulseSpeed: 1,
    glowIntensity: 0.9,
    ringSpeed: 2.5,
    particleDensity: 20,
    scale: 1.2,
  },
  classify: {
    label: 'Classifying',
    color: 'var(--nx-teal)',
    pulseSpeed: 0.8,
    glowIntensity: 0.7,
    ringSpeed: 4,
    particleDensity: 15,
    scale: 1.1,
  },
  sending: {
    label: 'Transmitting',
    color: 'var(--nx-cyan)',
    pulseSpeed: 1.5,
    glowIntensity: 0.6,
    ringSpeed: 2,
    particleDensity: 25,
    scale: 1.05,
  },
  underwriting: {
    label: 'Underwriting',
    color: 'var(--nx-electric-blue)',
    pulseSpeed: 2,
    glowIntensity: 0.8,
    ringSpeed: 6,
    particleDensity: 12,
    scale: 1.15,
  },
  hot_lead: {
    label: 'Hot Lead Detected',
    color: 'var(--nx-gold)',
    pulseSpeed: 0.5,
    glowIntensity: 1.0,
    ringSpeed: 8,
    particleDensity: 30,
    scale: 1.3,
  },
  critical: {
    label: 'System Alert',
    color: 'var(--nx-red)',
    pulseSpeed: 0.3,
    glowIntensity: 1.0,
    ringSpeed: 12,
    particleDensity: 50,
    scale: 1.4,
  },
};
