/**
 * ANALYTICS 4.1 — the heat map's geography (pure; geometry and matching only,
 * never a number).
 *
 * Boundaries are the US Census cartographic boundaries from us-atlas@3
 * (`counties-albers-10m`), pre-projected to the SAME Albers USA 975 × 610
 * frame as Home's dot matrix and intel-geo's `project()`, generated by
 * scripts/generate-us-atlas-areas.mjs. States load with the map; a state's
 * counties load when it is opened (one small chunk per state).
 *
 * What is real and what is approximated:
 *   state, county   true polygons (Census, 1:10m)
 *   city            NO boundary source exists (not in us-atlas, not in the
 *                   database) — a city is drawn at the centre of its own
 *                   properties (server centroid), sized by its base
 *   ZIP             US Census ZCTA outlines (risk_private.geography_authoritative,
 *                   322 of the 376 ZIPs messaged in 120 days) read through the
 *                   Lab's /boundaries route → public.analytics_zip_boundaries
 *                   (owner-approved, RC 7.1). Until that function exists, and
 *                   for any ZIP it has no outline for, a ZIP is drawn at its
 *                   properties' centre, like a city — and the key says so
 */
import { clamp } from './intel-format'

export type AreaShape = { id: string; name: string; d: string; box: [number, number, number, number]; at: [number, number] }
export type StateShape = AreaShape & { abbr: string }

export type GeoLevel = 'nation' | 'state' | 'county' | 'city' | 'zip'
/** The drill: what each level breaks into. */
export const ATLAS_CHILD: Record<GeoLevel, 'state' | 'county' | 'city' | 'zip' | null> = { nation: 'state', state: 'county', county: 'city', city: 'zip', zip: null }
export const ATLAS_DIMS = ['state', 'county', 'city', 'zip'] as const
/** Every geography step a breadcrumb can hold (market is a canonical step reached from other lenses). */
export const GEO_SEGMENT_DIMS = ['state', 'market', 'county', 'city', 'zip'] as const
export const LEVEL_NOUN: Record<string, string> = { state: 'States', county: 'Counties', city: 'Cities', zip: 'ZIPs' }

/** The level the map is on: the deepest drill step present (market is a filter, not a level). */
export function atlasLevel(segment: Array<{ dim: string }>): GeoLevel {
  let level: GeoLevel = 'nation'
  for (const s of segment) if ((ATLAS_DIMS as readonly string[]).includes(s.dim)) level = s.dim as GeoLevel
  return level
}

/* ── loading (lazy, cached) ───────────────────────────────────────────── */

const STATE_FILE = import.meta.glob<{ default: StateShape[] }>('./atlas/us-states.json')
const COUNTY_FILES = import.meta.glob<{ default: AreaShape[] }>('./atlas/counties/*.json')
const cache = new Map<string, Promise<AreaShape[]>>()
export function loadStates(): Promise<StateShape[]> {
  const key = '__states'
  if (!cache.has(key)) {
    const load = Object.values(STATE_FILE)[0]
    cache.set(key, load ? load().then((m) => m.default) : Promise.resolve([]))
  }
  return cache.get(key) as Promise<StateShape[]>
}
export function loadCounties(abbr: string): Promise<AreaShape[]> {
  const key = abbr.toUpperCase()
  if (!cache.has(key)) {
    const load = COUNTY_FILES[`./atlas/counties/${key}.json`]
    cache.set(key, load ? load().then((m) => m.default) : Promise.resolve([]))
  }
  return cache.get(key) as Promise<AreaShape[]>
}

/* ── matching a canonical county name to a Census polygon ─────────────── */

/** "De Kalb" = "DeKalb", "Saint Louis" = "St. Louis", "Miami-Dade" = "Miami Dade". */
export function normCounty(name: string): string {
  return name.toLowerCase()
    .replace(/\b(county|parish|borough|census area|municipality)\b/g, '')
    .replace(/\bsaint\b/g, 'st')
    .replace(/[^a-z]/g, '')
}

/** Even-odd point-in-polygon over the generator's path data (M x,y L x,y … Z). */
export function pointInPath(d: string, x: number, y: number): boolean {
  let inside = false
  for (const ring of d.split('M').filter(Boolean)) {
    const pts = ring.replace(/Z/g, '').split('L').map((p) => p.split(',').map(Number))
    for (let i = 0, j = pts.length - 1; i < pts.length; j = i, i += 1) {
      const [xi, yi] = pts[i]
      const [xj, yj] = pts[j]
      if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi || 1e-12) + xi) inside = !inside
    }
  }
  return inside
}

/**
 * The polygon for a county row (key "Name|ST"). Names are matched after
 * normalising; when a state has two areas of one name (Baltimore city and
 * county; St. Louis city and county) "… City" picks the independent city
 * (FIPS 5xx), otherwise the row's own centroid decides (point in polygon).
 * Null when nothing matches — the row stays in the list, never misplaced.
 */
export function matchCounty(key: string, shapes: AreaShape[], at?: [number, number] | null): AreaShape | null {
  const name = key.split('|')[0] || ''
  const isCity = /\bcity\b/i.test(name)
  const n = normCounty(name)
  let cands = shapes.filter((s) => normCounty(s.name) === n)
  if (!cands.length && isCity) cands = shapes.filter((s) => normCounty(s.name) === normCounty(name.replace(/\bcity\b/i, '')))
  if (!cands.length) return null
  if (cands.length === 1) return cands[0]
  if (isCity) { const c = cands.find((s) => Number(s.id.slice(2)) >= 500); if (c) return c }
  if (at) { const hit = cands.find((s) => pointInPath(s.d, at[0], at[1])); if (hit) return hit }
  return cands.find((s) => Number(s.id.slice(2)) < 500) || cands[0]
}

/* ── the heat scale ───────────────────────────────────────────────────── */

/**
 * 0..1 heat for a value. Rates and medians are linear from zero to the
 * largest CREDIBLE value on show (areas under the sample floor never set the
 * scale); counts are square-root scaled so one large area doesn't flatten
 * the rest. Null (no base) has no heat.
 */
export function heatOf(value: number | null | undefined, peak: number, unit: string): number | null {
  if (value === null || value === undefined || !Number.isFinite(value)) return null
  if (!(peak > 0)) return 0
  const t = clamp(value / peak, 0, 1)
  return unit === 'count' ? Math.sqrt(t) : t
}
/** Quantise heat into `steps` classes so neighbouring areas read as distinct bands. */
export const heatClass = (t: number, steps = 6) => (t <= 0 ? 0 : Math.min(steps, Math.ceil(t * steps)) / steps)

/* ── the camera ───────────────────────────────────────────────────────── */

export type Box = { x: number; y: number; w: number; h: number }
export const FRAME = { width: 975, height: 610 } as const
const ASPECT = FRAME.width / FRAME.height
/** A box padded (fraction) and letterboxed to the frame's aspect; never smaller than `min` wide. */
export function frameBox(b: Box | null, pad = 0.08, min = 24): Box {
  if (!b || !Number.isFinite(b.x) || !(b.w >= 0)) return { x: 0, y: 0, w: FRAME.width, h: FRAME.height }
  let w = Math.max(min, b.w * (1 + pad * 2))
  let h = Math.max(min / ASPECT, b.h * (1 + pad * 2))
  if (w / h > ASPECT) h = w / ASPECT; else w = h * ASPECT
  const cx = b.x + b.w / 2
  const cy = b.y + b.h / 2
  return { x: cx - w / 2, y: cy - h / 2, w, h }
}
export function unionBox(boxes: Array<[number, number, number, number] | null | undefined>): Box | null {
  let x0 = Infinity; let y0 = Infinity; let x1 = -Infinity; let y1 = -Infinity
  for (const b of boxes) { if (!b) continue; x0 = Math.min(x0, b[0]); y0 = Math.min(y0, b[1]); x1 = Math.max(x1, b[2]); y1 = Math.max(y1, b[3]) }
  return Number.isFinite(x0) ? { x: x0, y: y0, w: x1 - x0, h: y1 - y0 } : null
}

/* ── centre marks that never hide each other ─────────────────────────── */

/**
 * Cities and ZIPs are drawn at the centre of their own properties; centres a
 * few blocks apart would stack into one blob. Overlapping marks are pushed
 * apart (pairwise, a few dozen passes, a gentle pull home) — the true centre
 * is kept (ox, oy) so the map can draw a leader to it. Deterministic.
 */
export function dodge<T extends { x: number; y: number; r: number }>(marks: T[], gap = 0, iters = 80): Array<T & { ox: number; oy: number }> {
  const out = marks.map((m) => ({ ...m, ox: m.x, oy: m.y }))
  for (let k = 0; k < iters; k += 1) {
    let moved = false
    for (let i = 0; i < out.length; i += 1) {
      for (let j = i + 1; j < out.length; j += 1) {
        const a = out[i]
        const b = out[j]
        let dx = b.x - a.x
        let dy = b.y - a.y
        let d = Math.hypot(dx, dy)
        const min = a.r + b.r + gap
        if (d >= min) continue
        if (d < 1e-9) { const t = (i * 2.399963 + j) % (Math.PI * 2); dx = Math.cos(t); dy = Math.sin(t); d = 1 } // golden-angle split for identical centres
        const push = (min - d) / 2
        const ux = dx / d
        const uy = dy / d
        a.x -= ux * push; a.y -= uy * push
        b.x += ux * push; b.y += uy * push
        moved = true
      }
    }
    for (const m of out) { m.x += (m.ox - m.x) * 0.015; m.y += (m.oy - m.y) * 0.015 }
    if (!moved) break
  }
  return out
}

/* ── ZIP outlines (US Census ZCTA, read through the Lab API) ──────────── */

export type GeoJsonOutline =
  | { type: 'Polygon'; coordinates: number[][][] }
  | { type: 'MultiPolygon'; coordinates: number[][][][] }
/** The Lab's /boundaries answer. `available: false` until the outline function exists (or when it fails). */
export type ZipOutlines = { available: boolean; reason?: string; source?: string; zips?: Record<string, GeoJsonOutline>; missing?: string[] }
type Projector = (lng: number, lat: number) => [number, number] | null

/**
 * A GeoJSON outline projected into the heat map's frame (the same Albers USA
 * projection the county polygons were generated in): SVG path data at
 * 0.001-unit precision (a ZIP is a fraction of a unit wide), its box, and an
 * area-weighted anchor. Rings that leave the projection or collapse are
 * dropped; nothing usable → null.
 */
export function outlineShape(geom: GeoJsonOutline | null | undefined, proj: Projector): { d: string; box: [number, number, number, number]; at: [number, number] } | null {
  if (!geom || !Array.isArray(geom.coordinates)) return null
  const polys: number[][][][] = geom.type === 'Polygon' ? [geom.coordinates] : geom.type === 'MultiPolygon' ? geom.coordinates : []
  let d = ''
  let x0 = Infinity; let y0 = Infinity; let x1 = -Infinity; let y1 = -Infinity
  let ax = 0; let ay = 0; let aw = 0
  for (const poly of polys) {
    poly.forEach((ring, ri) => {
      const pts: Array<[number, number]> = []
      for (const c of ring || []) {
        const xy = Array.isArray(c) ? proj(Number(c[0]), Number(c[1])) : null
        if (xy && Number.isFinite(xy[0]) && Number.isFinite(xy[1])) pts.push(xy)
      }
      if (pts.length < 3) return
      d += `M${pts.map(([x, y]) => `${x.toFixed(3)},${y.toFixed(3)}`).join('L')}Z`
      for (const [x, y] of pts) { if (x < x0) x0 = x; if (y < y0) y0 = y; if (x > x1) x1 = x; if (y > y1) y1 = y }
      if (ri !== 0) return
      let a2 = 0; let cx = 0; let cy = 0
      for (let i = 0, j = pts.length - 1; i < pts.length; j = i, i += 1) {
        const f = pts[j][0] * pts[i][1] - pts[i][0] * pts[j][1]
        a2 += f; cx += (pts[j][0] + pts[i][0]) * f; cy += (pts[j][1] + pts[i][1]) * f
      }
      if (Math.abs(a2) > 1e-12) { const w = Math.abs(a2); ax += (cx / (3 * a2)) * w; ay += (cy / (3 * a2)) * w; aw += w }
    })
  }
  if (!d) return null
  return { d, box: [x0, y0, x1, y1], at: aw ? [ax / aw, ay / aw] : [(x0 + x1) / 2, (y0 + y1) / 2] }
}

/**
 * Split the ZIP rows on show into outlined areas and centre marks, and say
 * which. The "approximated" statement survives exactly as long as one ZIP on
 * show is still drawn at its properties' centre.
 */
export function zipOutlineLayer<R extends { key: string }>(rows: R[], outlines: ZipOutlines | null | undefined, proj: Projector) {
  const areas: Array<{ row: R; d: string; box: [number, number, number, number]; at: [number, number] }> = []
  const rest: R[] = []
  const usable = outlines?.available ? outlines.zips || {} : null
  for (const r of rows) {
    const shape = usable ? outlineShape(usable[r.key], proj) : null
    if (shape) areas.push({ row: r, ...shape }); else rest.push(r)
  }
  const source = outlines?.source || 'US Census ZCTA'
  const note = !usable
    ? 'ZIPs have no outline available — drawn at the centre of their properties'
    : rest.length
      ? `ZIP outlines: ${source} · ${rest.length} without outline shown at property centre`
      : `ZIP outlines: ${source}`
  return { areas, rest, note, approximated: rest.length > 0 }
}
