#!/usr/bin/env python3
"""Generates the PROPOSED inferred-investor extension of the Market Intelligence summary:

  PROPOSED_20261005140000_market_intel_inferred_investor.sql           the migration
  PROPOSED_20261005140000_market_intel_inferred_investor_rollback.sql  restores the applied functions/view verbatim
  PROPOSED_20261005140000_market_intel_inferred_investor_pretest.sql   rollback-only DO block (RC 7.1 practice)

The applied summary migration (20261004150000_market_intel_geo_rollup.sql, identical to prod:
prosrc md5 checked 2026-10-05) is the base. Its view and three functions are PATCHED here by exact
string insertion, never retyped, so the extension cannot drift from what is live, and the rollback
re-creates the originals byte for byte. A unit test (market-intel-inferred.test.mjs) asserts the
generated files are current and that the SQL tier rule equals the JS rule (mi-inferred-investor.js).
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parents[3] / 'supabase/migrations'
base = (root / '20261004150000_market_intel_geo_rollup.sql').read_text()
STAMP = '20261005140000_market_intel_inferred_investor'


def block(pattern):
    m = re.search(pattern, base, re.S)
    assert m, pattern
    return m.group(0)


def fn(name):
    return block(r"create or replace function public\.%s\(.*?\n\$\$;\n" % re.escape(name))


def patch(text, old, new):
    assert text.count(old) == 1, old
    return text.replace(old, new)


view_orig = block(r"create or replace view public\.mi_rollup_sales_v as.*?\n where m\.sold_on is not null and upper\(btrim\(m\.state\)\) ~ '\^\[A-Z\]\{2\}\$';\n")
units_orig = fn('mi_rollup_units')
fp_orig = fn('mi_rollup_fingerprint')
run_orig = fn('mi_rollup_run_unit')

# 1. the view gains property_id as its LAST column (create or replace view may only append).
view_new = patch(view_orig, "a.asset in ('mf_2_4', 'mf_5_plus', 'mf_unknown') as is_mf\n",
                 "a.asset in ('mf_2_4', 'mf_5_plus', 'mf_unknown') as is_mf,\n       m.property_id\n")
# 2. units: the inferred units run inside the build (before finalize), cleanup right after it.
units_new = patch(units_orig, "select array['prepare', 'buyers']",
                  "select array['prepare', 'buyers', 'i:clusters', 'i:link:0', 'i:link:1', 'i:link:2', 'i:link:3', 'i:link:4', 'i:link:5', 'i:link:6', 'i:link:7', 'i:stacks']")
units_new = patch(units_new, "'m:zip', 'finalize', 'c:period'",
                  "'m:zip', 'i:g:nation', 'i:g:state', 'i:g:market', 'i:g:county', 'i:g:city', 'i:g:zip', 'i:validate', 'finalize', 'i:cleanup', 'c:period'")
# 3. fingerprint: an owner-snapshot change also rebuilds (the inferred tiers read it).
fp_new = patch(fp_orig, "'census', (select jsonb_build_array(count(*), max(vintage)) from public.exchange_market_fundamentals_cells))",
               "'census', (select jsonb_build_array(count(*), max(vintage)) from public.exchange_market_fundamentals_cells),\n"
               "    'owners', (select jsonb_build_array(count(*), max(last_observed_at)) from comp_private.comp_properties))")
# 4. run_unit dispatches 'i:' units to the inferred runner (one line, before any other work).
run_new = patch(run_orig, "  perform set_config('work_mem', '128MB', true);\n",
                "  perform set_config('work_mem', '128MB', true);\n"
                "  if v_kind = 'i' then return public.mi_infer_run_unit(p_build, p_unit, p_as_of); end if;\n")

# The tier rule. ONE definition; the unit test evaluates this exact text against classifyOwner().
TIER_CASE = """case
    when not p_corp and p_resident then 'no_signal'
    when p_corp and (p_oos or p_stack >= 2) then 'strong'
    when p_stack >= 3 and p_oos then 'strong'
    when p_stack >= 3 then 'likely'
    when p_trust and not p_corp then 'trust_estate'
    when p_corp then 'likely'
    when p_oos and p_stack = 2 then 'likely'
    when p_oos then 'absentee_only'
    else 'no_signal'
  end"""

TIERS = ['strong', 'likely', 'trust_estate', 'absentee_only', 'no_signal']
val_cols = ',\n  '.join(f'v_{t}_known integer not null, v_{t}_inv integer not null' for t in TIERS)
val_sel = ',\n            '.join(
    f"count(*) filter (where x.lk and x.buyer_known and x.tier = '{t}')::int as v_{t}_known, "
    f"count(*) filter (where x.lk and x.buyer_known and x.tier = '{t}' and x.is_investor)::int as v_{t}_inv" for t in TIERS)
val_names = ', '.join(f'v_{t}_known, v_{t}_inv' for t in TIERS)
val_sums = ',\n           '.join(f'sum(a.v_{t}_known) filter (where a.band <= p.maxband), sum(a.v_{t}_inv) filter (where a.band <= p.maxband)' for t in TIERS)
val_json = ',\n        '.join(f"'{t}', jsonb_build_object('recorded_investor', r.v_{t}_inv, 'recorded_other', r.v_{t}_known - r.v_{t}_inv)" for t in TIERS)

mig = f"""-- =============================================================================
-- Market Intelligence: INFERRED INVESTOR (owner-based), an extension of the market summary.
-- STATUS: PROPOSED — NOT APPLIED. GENERATED by apps/api/scripts/market-intel-make-inferred-migration.py;
-- do not edit by hand. Pretest: PROPOSED_{STAMP}_pretest.sql · Rollback: PROPOSED_{STAMP}_rollback.sql
-- Evidence (2026-10-05, read-only, prod): ~/.claude/jobs/c39b0175/tmp/market-intel/INFERRED_INVESTOR_EVIDENCE.txt
--   linked 598,841 of 665,288 sales (90.0%); validation on 36,343 linked sales that record a buyer:
--   precision 87.1%, recall 80.7% for strong+likely (unchanged by tier@2, which only moves 9,537 stack-only
--   individual/trust sales from strong to likely); trust 23.1%, absentee-only 3.3%, no signal 2.7%.
--   tier@2 counts: strong 95,776 · likely 60,997 · trust 1,881 · absentee-only 12,643 · no signal 427,544.
--   Measured read side: i:clusters 5.2 s; one quarter of i:link 20.6 s (+5 s inline clusters) → link split in 8.
-- APPLY PLAN (owner approval required; nothing here is applied):
--   1. Outside 05:00-08:59 / 09:15-11:59 UTC: run the _pretest (SET statement_timeout = '300s'); expect
--      'pretest ok', per-unit ms (each i:link must be < 15 s) and the national matrix ≈ the numbers above.
--   2. Apply this file (MCP apply_migration) outside the windows; no cron change (same 75 ticks).
--   3. The fingerprint now includes owner snapshots, so the next nightly tick starts build 2 with 65 units
--      (~ +3 min DB time). Until it is ready, MI keeps serving build 1; inferred metrics read 'unavailable'.
--   4. Verify: select notes->'inferred_investor' from mi_rollup_builds where status = 'ready';
--      GET op=status → inferred_investor.available = true.
--   5. Rollback: the _rollback file (restores the applied functions and view byte for byte).
-- =============================================================================
--
-- WHY. Recorded investor purchases need a deed that names the buyer (~6% of sales). For the
-- other sales the property's CURRENT owner of record is known. Brief §48: an LLC owner alone
-- does not make an investor purchase. So this is a SEPARATE metric, tiered, with its evidence,
-- and validated against the sales that DO name a buyer. It never changes investor_count.
--
-- RULES (mirrored in apps/api/src/lib/domain/market-intelligence/mi-inferred-investor.js):
--   LINK mi_owner_link@1: a sale inherits today's owner only if it is the property's most recent
--     sale, no canonical transfer exists > 45 days after it (closer events are the same
--     transaction's other recordings), and the owner snapshot was observed ≥ 30 days after it
--     (an earlier snapshot can still show the seller).
--   TIER mi_owner_tier@2 (public.mi_owner_tier): strong · likely · trust_estate · absentee_only ·
--     no_signal. Inferred investor = strong + likely.
--   STACK: properties whose owner receives the tax bill at the same normalised mailing address
--     (comp_properties.owner_mailing_identity_key_v1, a keyed hash). NOT proof of one legal owner.
--
-- OBJECTS (all new except the four patched below; service_role only, RLS on, no policies):
--   comp_private.mi_owner_mail_cluster  per build: mailing key → stack id + size (keys stay in comp_private)
--   public.mi_sale_owner_link           per build (current build only, intermediate): one row per sale
--   public.mi_geo_period_inferred       per build: geography × period × asset inferred counts + validation
--   public.mi_owner_stack               per build: stacks ≥ 3 with a linked sale (company label candidate)
--   public.mi_owner_stack_activity      per build: the linked sales in those stacks (for top stacks)
--   public.mi_owner_tier(...)           the tier rule
--   public.mi_infer_run_unit(...)       the 'i:' units
-- PATCHED (exact insertions into the applied text; the rollback restores the originals):
--   mi_rollup_sales_v      + property_id (last column)
--   mi_rollup_units()      + 18 'i:' units (65 units; the nightly window has 75 ticks)
--   mi_rollup_fingerprint()+ owner snapshot (count, max observed) so an owner refresh rebuilds
--   mi_rollup_run_unit()   + one dispatch line for 'i:' units
-- ISOLATION: an 'i:' unit that fails on its RETRY is recorded in notes.inferred_errors and skipped;
--   the core build still completes and the API shows the inferred metric as unavailable for that build.
-- =============================================================================

create table if not exists comp_private.mi_owner_mail_cluster (
  build_id  bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  mail_key  text not null,
  stack_id  integer not null,
  props_n   integer not null,
  corp_n    integer not null,
  oos_n     integer not null,
  trust_n   integer not null,
  primary key (build_id, mail_key)
);
create index if not exists mi_owner_mail_cluster_stack on comp_private.mi_owner_mail_cluster (build_id, stack_id);

create table if not exists public.mi_sale_owner_link (
  build_id    bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  comp_id     text not null,
  sold_on     date not null,
  state       text not null,
  zip         text,
  city_key    text,
  asset       text not null,
  is_mf       boolean not null,
  buyer_known boolean not null,
  is_investor boolean not null,
  buyer       text,              -- the MV's company buyer, kept only for sales inside a stack (label evidence)
  link        text not null check (link in ('linked', 'no_property', 'not_latest_sale', 'later_transfer', 'no_owner_record', 'owner_snapshot_before_sale')),
  tier        text check (tier in ('strong', 'likely', 'trust_estate', 'absentee_only', 'no_signal')),
  corp        boolean,
  trust       boolean,
  oos         boolean,
  resident    boolean,
  stack_n     integer,
  stack_id    integer,
  primary key (build_id, comp_id)
);
create index if not exists mi_sale_owner_link_stack on public.mi_sale_owner_link (build_id, stack_id) where stack_id is not null;

create table if not exists public.mi_geo_period_inferred (
  build_id    bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  geo_level   text not null,
  geo_key     text not null,
  period      text not null,
  asset       text not null,
  sale_count     integer not null,
  linked_count   integer not null,
  strong_n       integer not null,
  likely_n       integer not null,
  trust_n        integer not null,
  absentee_n     integer not null,
  no_signal_n    integer not null,
  stack3_n       integer not null,
  {val_cols},
  primary key (build_id, geo_level, period, asset, geo_key)
);

create table if not exists public.mi_owner_stack (
  build_id  bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  stack_id  integer not null,
  props_n   integer not null,
  corp_n    integer not null,
  oos_n     integer not null,
  trust_n   integer not null,
  linked_n  integer not null,
  named_n   integer not null,
  label     text,
  label_n   integer not null,
  primary key (build_id, stack_id)
);

create table if not exists public.mi_owner_stack_activity (
  build_id  bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  comp_id   text not null,
  stack_id  integer not null,
  sold_on   date not null,
  zip       text,
  state     text not null,
  city_key  text,
  asset     text not null,
  primary key (build_id, comp_id)
);

do $grants$
declare t text;
begin
  foreach t in array array['public.mi_sale_owner_link', 'public.mi_geo_period_inferred', 'public.mi_owner_stack', 'public.mi_owner_stack_activity', 'comp_private.mi_owner_mail_cluster'] loop
    execute format('alter table %s enable row level security', t);
    execute format('revoke all on %s from public, anon, authenticated', t);
    execute format('grant select on %s to service_role', t);
  end loop;
end
$grants$;

{view_new}revoke all on public.mi_rollup_sales_v from public, anon, authenticated;
grant select on public.mi_rollup_sales_v to service_role;

-- The tier rule (mi_owner_tier@2). Inputs are non-null: callers coalesce unknown to false / 1.
create or replace function public.mi_owner_tier(p_corp boolean, p_trust boolean, p_oos boolean, p_stack integer, p_resident boolean)
returns text language sql immutable as $$
  select {TIER_CASE}
$$;

create or replace function public.mi_infer_run_unit(p_build bigint, p_unit text, p_as_of date)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_kind text := split_part(p_unit, ':', 2);
  v_arg text := split_part(p_unit, ':', 3);
  v_key text;
  v_rows bigint := 0;
  v_n bigint;
  v_attempts integer;
  v_keep bigint;
  v_having text := '((grouping(x.asset) = 0 and x.asset in (''sfr'', ''mf_2_4'', ''mf_5_plus'', ''land'', ''commercial''))
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 0 and x.is_mf)
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 1))';
  v_asset text := 'case when grouping(x.asset) = 0 then x.asset when grouping(x.is_mf) = 0 then ''mf'' else ''all'' end';
begin
  select attempts into v_attempts from public.mi_rollup_builds where build_id = p_build;
  -- a failed inferred unit earlier in this build: skip the rest of the inferred chain (cleanup still runs)
  if v_kind <> 'cleanup' and exists (select 1 from public.mi_rollup_builds where build_id = p_build and notes ? 'inferred_errors') then
    return 0;
  end if;
  begin
    if v_kind = 'clusters' then
      insert into comp_private.mi_owner_mail_cluster (build_id, mail_key, stack_id, props_n, corp_n, oos_n, trust_n)
      select p_build, k, (row_number() over (order by n desc, k))::int, n, corp, oos, trust
        from (select cp.owner_mailing_identity_key_v1 as k, count(*)::int as n,
                     count(*) filter (where cp.is_corporate_owner)::int as corp, count(*) filter (where cp.out_of_state_owner)::int as oos,
                     count(*) filter (where cp.is_trust)::int as trust
                from comp_private.comp_properties cp
               where cp.owner_mailing_identity_key_v1 is not null
               group by 1 having count(*) >= 2) c;
      get diagnostics v_rows = row_count;

    elsif v_kind = 'link' then
      -- one eighth of the properties (all sales of a property land in the same eighth, so
      -- "most recent sale" is decided over the property's whole history)
      insert into public.mi_sale_owner_link (build_id, comp_id, sold_on, state, zip, city_key, asset, is_mf, buyer_known, is_investor, buyer,
                                             link, tier, corp, trust, oos, resident, stack_n, stack_id)
      select p_build, s.comp_id, s.sold_on, s.state, s.zip, s.city_key, s.asset, s.is_mf, s.buyer_known, s.is_investor,
             case when c.stack_id is not null then s.buyer end,
             l.link,
             case when l.link = 'linked' then public.mi_owner_tier(coalesce(cp.is_corporate_owner, false), coalesce(cp.is_trust, false),
               coalesce(cp.out_of_state_owner, false), coalesce(c.props_n, 1), r.resident) end,
             cp.is_corporate_owner, cp.is_trust, cp.out_of_state_owner, case when l.link = 'linked' then r.resident end,
             case when cp.owner_mailing_identity_key_v1 is not null then coalesce(c.props_n, 1) end, c.stack_id
        from (select v.*, v.sold_on = max(v.sold_on) over (partition by v.property_id) as latest
                from public.mi_rollup_sales_v v
               where coalesce(hashtext(v.property_id) & 7, 0) = v_arg::int) s
        left join comp_private.comp_properties cp on cp.property_id = s.property_id
        left join comp_private.mi_owner_mail_cluster c on c.build_id = p_build and c.mail_key = cp.owner_mailing_identity_key_v1
        cross join lateral (select case
            when s.property_id is null then 'no_property'
            when not s.latest then 'not_latest_sale'
            when exists (select 1 from comp_private.comp_canonical_transactions t
                          where t.primary_property_id = s.property_id and t.event_date > s.sold_on + 45) then 'later_transfer'
            when cp.property_id is null or cp.last_observed_at is null then 'no_owner_record'
            when cp.last_observed_at::date - s.sold_on < 30 then 'owner_snapshot_before_sale'
            else 'linked' end as link) l
        cross join lateral (select case when l.link = 'linked' then exists (
            select 1 from comp_private.comp_property_contacts pc where pc.property_id = s.property_id and pc.resident and pc.likely_owner) else false end as resident) r;
      get diagnostics v_rows = row_count;

    elsif v_kind = 'stacks' then
      insert into public.mi_owner_stack (build_id, stack_id, props_n, corp_n, oos_n, trust_n, linked_n, named_n, label, label_n)
      select p_build, x.stack_id, c.props_n, c.corp_n, c.oos_n, c.trust_n, x.linked_n, x.named_n, nm.buyer, coalesce(nm.n, 0)
        from (select l.stack_id, count(*)::int as linked_n, count(*) filter (where l.buyer is not null)::int as named_n
                from public.mi_sale_owner_link l
               where l.build_id = p_build and l.link = 'linked' and l.stack_n >= 3
               group by l.stack_id) x
        join comp_private.mi_owner_mail_cluster c on c.build_id = p_build and c.stack_id = x.stack_id
        left join lateral (select l.buyer, count(*)::int as n from public.mi_sale_owner_link l
                            where l.build_id = p_build and l.stack_id = x.stack_id and l.link = 'linked' and l.buyer is not null
                            group by l.buyer order by count(*) desc, l.buyer limit 1) nm on true;
      get diagnostics v_n = row_count; v_rows := v_n;
      insert into public.mi_owner_stack_activity (build_id, comp_id, stack_id, sold_on, zip, state, city_key, asset)
      select p_build, l.comp_id, l.stack_id, l.sold_on, l.zip, l.state, l.city_key, l.asset
        from public.mi_sale_owner_link l
       where l.build_id = p_build and l.link = 'linked' and l.stack_n >= 3;
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;

    elsif v_kind = 'g' then
      v_key := public.mi_rollup_level_key(v_arg);
      if v_key is null then raise exception 'mi_infer: unknown level in unit %', p_unit; end if;
      -- Periods are nested windows ending at the as-of, so each sale is counted once in its
      -- narrowest band and every period sums the bands it contains.
      execute format($q$
        insert into public.mi_geo_period_inferred (build_id, geo_level, geo_key, period, asset, sale_count, linked_count,
          strong_n, likely_n, trust_n, absentee_n, no_signal_n, stack3_n, {val_names})
        with x0 as (
          select %1$s as k, s.asset, s.is_mf, s.buyer_known, s.is_investor, s.tier, s.stack_n, (s.link = 'linked') as lk,
                 case when s.sold_on > $3::date - 30 then 1 when s.sold_on > $3::date - 90 then 2 when s.sold_on > $3::date - 182 then 3
                      when s.sold_on > $3::date - 365 then 4 when s.sold_on > $3::date - 1095 then 5 else 6 end as band
            from public.mi_sale_owner_link s
            left join public.mi_zip_geo g on g.build_id = $1 and g.zip = s.zip
           where s.build_id = $1
        ), a as (
          select x.k, %2$s as asset, x.band, count(*)::int as n, count(*) filter (where x.lk)::int as linked,
            count(*) filter (where x.lk and x.tier = 'strong')::int as strong_n, count(*) filter (where x.lk and x.tier = 'likely')::int as likely_n,
            count(*) filter (where x.lk and x.tier = 'trust_estate')::int as trust_n, count(*) filter (where x.lk and x.tier = 'absentee_only')::int as absentee_n,
            count(*) filter (where x.lk and x.tier = 'no_signal')::int as no_signal_n, count(*) filter (where x.lk and x.stack_n >= 3)::int as stack3_n,
            {val_sel}
            from x0 x where x.k is not null
           group by grouping sets ((x.k, x.asset, x.band), (x.k, x.band), (x.k, x.is_mf, x.band))
          having %3$s
        )
        select $1, $2, a.k, p.period, a.asset,
           sum(a.n) filter (where a.band <= p.maxband), sum(a.linked) filter (where a.band <= p.maxband),
           sum(a.strong_n) filter (where a.band <= p.maxband), sum(a.likely_n) filter (where a.band <= p.maxband),
           sum(a.trust_n) filter (where a.band <= p.maxband), sum(a.absentee_n) filter (where a.band <= p.maxband),
           sum(a.no_signal_n) filter (where a.band <= p.maxband), sum(a.stack3_n) filter (where a.band <= p.maxband),
           {val_sums}
          from a cross join (values ('30d', 1), ('90d', 2), ('6m', 3), ('1y', 4), ('3y', 5), ('all', 6)) as p(period, maxband)
         group by a.k, p.period, a.asset
        having coalesce(sum(a.n) filter (where a.band <= p.maxband), 0) > 0
      $q$, v_key, v_asset, v_having) using p_build, v_arg, p_as_of;
      get diagnostics v_rows = row_count;

    elsif v_kind = 'validate' then
      -- the build's published validation: the national, all-time, all-asset matrix
      update public.mi_rollup_builds b set notes = b.notes || jsonb_build_object('inferred_investor', jsonb_build_object(
        'link_rule', 'mi_owner_link@1', 'tier_rule', 'mi_owner_tier@2',
        'sales', r.sale_count, 'linked', r.linked_count,
        'tiers', jsonb_build_object('strong', r.strong_n, 'likely', r.likely_n, 'trust_estate', r.trust_n, 'absentee_only', r.absentee_n, 'no_signal', r.no_signal_n),
        'matrix', jsonb_build_object(
        {val_json}),
        'stacks', (select count(*) from public.mi_owner_stack s where s.build_id = p_build)))
        from public.mi_geo_period_inferred r
       where b.build_id = p_build and r.build_id = p_build and r.geo_level = 'nation' and r.geo_key = 'US' and r.period = 'all' and r.asset = 'all';
      get diagnostics v_rows = row_count;
      if v_rows = 0 then raise exception 'mi_infer: no national row to validate'; end if;

    elsif v_kind = 'cleanup' then
      -- the per-sale link rows and mailing keys are intermediates: keep them for the current build only;
      -- served tables follow the core rule (current + previous ready build).
      delete from public.mi_sale_owner_link where build_id <> p_build;
      get diagnostics v_n = row_count; v_rows := v_n;
      delete from comp_private.mi_owner_mail_cluster where build_id <> p_build;
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;
      select max(build_id) into v_keep from public.mi_rollup_builds where status = 'superseded';
      delete from public.mi_geo_period_inferred where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> p_build and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;
      delete from public.mi_owner_stack where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> p_build and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;
      delete from public.mi_owner_stack_activity where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> p_build and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;

    else
      raise exception 'mi_infer: unknown unit %', p_unit;
    end if;
    return v_rows;
  exception when query_canceled or others then
    -- first failure: re-raise, the tick records it and retries next tick. On the retry, record
    -- and skip: the inferred chain must never fail the core build.
    if coalesce(v_attempts, 0) = 0 or v_kind = 'cleanup' then raise; end if;
    update public.mi_rollup_builds set notes = notes || jsonb_build_object('inferred_errors', jsonb_build_object(p_unit, left(sqlerrm, 300)))
     where build_id = p_build;
    return 0;
  end;
end
$$;

{units_new}
{fp_new}
{run_new}
do $fn_grants$
declare f text;
begin
  foreach f in array array['mi_owner_tier(boolean, boolean, boolean, integer, boolean)', 'mi_infer_run_unit(bigint, text, date)',
                           'mi_rollup_units()', 'mi_rollup_fingerprint()', 'mi_rollup_run_unit(bigint, text, date)'] loop
    execute format('revoke all on function public.%s from public, anon, authenticated', f);
    execute format('grant execute on function public.%s to service_role', f);
  end loop;
end
$fn_grants$;

comment on table public.mi_geo_period_inferred is
  'Market Intelligence INFERRED investor (owner-based, mi_owner_link@1 + mi_owner_tier@2): geography x period x asset. Separate from recorded investor purchases (mi_geo_period_rollup.investor_count); never add them.';
"""

assert '$mig$' not in mig

rollback = f"""-- ROLLBACK for PROPOSED_{STAMP}.sql. GENERATED; do not edit by hand.
-- Restores the applied summary functions and view byte for byte (from 20261004150000_market_intel_geo_rollup.sql)
-- and drops every inferred object. The core summary tables and their builds are untouched.
-- A build started under the extension still lists 'i:' units: mark it failed first so the next
-- tick starts a clean core build:
update public.mi_rollup_builds set status = 'failed', last_error = 'inferred extension rolled back', finished_at = now(), updated_at = now()
 where status = 'building' and units @> array['i:clusters'];
update public.mi_rollup_builds set cursor = cardinality(units)
 where status = 'ready' and cursor < cardinality(units) and units @> array['i:clusters'];
update public.mi_rollup_builds set notes = notes - 'inferred_investor' - 'inferred_errors' where notes ?| array['inferred_investor', 'inferred_errors'];

{run_orig}
{fp_orig}
{units_orig}
drop function if exists public.mi_infer_run_unit(bigint, text, date);
drop function if exists public.mi_owner_tier(boolean, boolean, boolean, integer, boolean);
drop table if exists public.mi_owner_stack_activity;
drop table if exists public.mi_owner_stack;
drop table if exists public.mi_geo_period_inferred;
drop table if exists public.mi_sale_owner_link;
drop table if exists comp_private.mi_owner_mail_cluster;
-- property_id cannot be removed by create or replace view: drop and re-create the original.
drop view if exists public.mi_rollup_sales_v;
{view_orig}revoke all on public.mi_rollup_sales_v from public, anon, authenticated;
grant select on public.mi_rollup_sales_v to service_role;
do $fn_grants$
declare f text;
begin
  foreach f in array array['mi_rollup_units()', 'mi_rollup_fingerprint()', 'mi_rollup_run_unit(bigint, text, date)'] loop
    execute format('revoke all on function public.%s from public, anon, authenticated', f);
    execute format('grant execute on function public.%s to service_role', f);
  end loop;
end
$fn_grants$;
"""

pretest = f"""-- PRETEST for PROPOSED_{STAMP}.sql. GENERATED by apps/api/scripts/market-intel-make-inferred-migration.py.
-- Rollback-only: every change is undone by the RAISE at the end. Expected result:
--   ERROR:  pretest ok: ...      and NO schema change afterwards.
-- Run OUTSIDE 05:00-08:59, 09:15-11:59 UTC with:  SET statement_timeout = '300s';
-- It runs the full inferred chain against the live ready build's id space in a scratch build:
-- clusters, the eight link slices, stacks, nation + zip geography units and validate (~60-90 s).
-- What it proves: the DDL and the patches apply over the live objects; every inferred unit runs;
-- each unit's time is reported; the national validation matrix is produced.
DO $pretest$
DECLARE
  b bigint;
  n bigint;
  t0 timestamptz;
  ms text := '';
  u text;
  r record;
BEGIN
  EXECUTE $mig${mig}$mig$;

  INSERT INTO public.mi_rollup_builds (fingerprint, source_as_of, source_first, source_rows, units, status)
  SELECT fingerprint, source_as_of, source_first, source_rows, public.mi_rollup_units(), 'building'
    FROM public.mi_rollup_builds WHERE status = 'ready' ORDER BY build_id DESC LIMIT 1
  RETURNING build_id INTO b;
  IF b IS NULL THEN RAISE EXCEPTION 'pretest FAILED: no ready build to copy'; END IF;
  INSERT INTO public.mi_zip_geo SELECT b, zip, state, city_key, county_key, county_name, county_via, market_key, sales_n, min_lat, max_lat, min_lng, max_lng
    FROM public.mi_zip_geo WHERE build_id = (SELECT max(build_id) FROM public.mi_rollup_builds WHERE status = 'ready');

  FOREACH u IN ARRAY array['i:clusters', 'i:link:0', 'i:link:1', 'i:link:2', 'i:link:3', 'i:link:4', 'i:link:5', 'i:link:6', 'i:link:7', 'i:stacks', 'i:g:nation', 'i:g:zip', 'i:validate'] LOOP
    t0 := clock_timestamp();
    n := public.mi_rollup_run_unit(b, u, (SELECT source_as_of FROM public.mi_rollup_builds WHERE build_id = b));
    ms := ms || format('%s=%s rows/%s ms; ', u, n, floor(extract(epoch from clock_timestamp() - t0) * 1000));
  END LOOP;

  SELECT count(*) INTO n FROM public.mi_sale_owner_link WHERE build_id = b;
  IF n <> (SELECT source_rows FROM public.mi_rollup_builds WHERE build_id = b) THEN
    RAISE EXCEPTION 'pretest FAILED: % link rows for % sales', n, (SELECT source_rows FROM public.mi_rollup_builds WHERE build_id = b);
  END IF;
  SELECT linked_count, strong_n, likely_n, trust_n, sale_count INTO r FROM public.mi_geo_period_inferred
   WHERE build_id = b AND geo_level = 'nation' AND period = 'all' AND asset = 'all';
  RAISE EXCEPTION 'pretest ok: build % · sales % · linked % · strong % · likely % · trust % · % · validation %',
    b, r.sale_count, r.linked_count, r.strong_n, r.likely_n, r.trust_n, ms,
    (SELECT notes -> 'inferred_investor' -> 'matrix' FROM public.mi_rollup_builds WHERE build_id = b);
END
$pretest$;
"""

(root / f'PROPOSED_{STAMP}.sql').write_text(mig)
(root / f'PROPOSED_{STAMP}_rollback.sql').write_text(rollback)
(root / f'PROPOSED_{STAMP}_pretest.sql').write_text(pretest)
print('written', STAMP)
