#!/usr/bin/env python3
"""Generates the rollback-only PRETEST for the Market Intelligence summary migration.

RC 7.1 practice: one DO block whose every change is rolled back by the RAISE at the end
(never an explicit BEGIN through MCP; an aborted transaction can hold locks on a pooled
connection). The migration text is embedded verbatim (a unit test checks it), so the
pretest can never drift from what will be applied.
"""
import pathlib
root = pathlib.Path(__file__).resolve().parents[3] / 'supabase/migrations'
mig = (root / '20261004150000_market_intel_geo_rollup.sql').read_text()
assert '$mig$' not in mig
out = f"""-- PRETEST for PROPOSED_20261004150000_market_intel_geo_rollup.sql. GENERATED by
-- apps/api/scripts/market-intel-make-pretest.py; do not edit by hand.
-- Rollback-only: every change is undone by the RAISE at the end. Expected result:
--   ERROR:  pretest ok: ...      and NO schema change afterwards.
-- Run in a quiet window with:  SET statement_timeout = '120s';  (prepare + three units ≈ 25 s)
-- What it proves: the DDL applies; the first tick creates a build and runs 'prepare'; a period unit,
-- a month unit and the fingerprint run; the asset mapping covers the corpus; ZIP 55411 / 1y / all
-- matches the API's own numbers for the same as-of.
DO $pretest$
DECLARE
  r jsonb;
  b bigint;
  n bigint;
  v record;
BEGIN
  EXECUTE $mig${mig}$mig$;

  r := public.mi_rollup_tick(true);                                  -- creates the build + runs 'prepare'
  IF r ->> 'unit' IS DISTINCT FROM 'prepare' OR r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at prepare: %', r; END IF;
  SELECT build_id INTO b FROM public.mi_rollup_builds WHERE status = 'building';
  SELECT count(*) INTO n FROM public.mi_zip_geo WHERE build_id = b;
  IF n < 1000 THEN RAISE EXCEPTION 'pretest FAILED: mi_zip_geo has % rows', n; END IF;

  r := public.mi_rollup_tick();                                      -- buyers
  IF r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at %: %', r ->> 'unit', r; END IF;
  r := public.mi_rollup_tick();                                      -- p:nation:1y
  IF r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at %: %', r ->> 'unit', r; END IF;
  r := public.mi_rollup_tick();                                      -- p:state:1y
  IF r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at %: %', r ->> 'unit', r; END IF;
  PERFORM public.mi_rollup_run_unit(b, 'p:zip:1y', (SELECT source_as_of FROM public.mi_rollup_builds WHERE build_id = b));
  PERFORM public.mi_rollup_run_unit(b, 'm:state', (SELECT source_as_of FROM public.mi_rollup_builds WHERE build_id = b));

  SELECT sale_count, median_price, investor_count, buyer_known_count, entity_owned_count INTO v
    FROM public.mi_geo_period_rollup WHERE build_id = b AND geo_level = 'zip' AND geo_key = '55411' AND period = '1y' AND asset = 'all';
  SELECT count(*) INTO n FROM public.mi_geo_month_rollup WHERE build_id = b AND geo_level = 'state';
  RAISE EXCEPTION 'pretest ok: build %, 55411/1y/all sales % median % investor % of % buyer-known, entity %; state month rows %; unmapped types %',
    b, v.sale_count, v.median_price, v.investor_count, v.buyer_known_count, v.entity_owned_count, n,
    (SELECT notes -> 'unmapped_types' FROM public.mi_rollup_builds WHERE build_id = b);
END
$pretest$;
"""
(root / 'PROPOSED_20261004150000_market_intel_geo_rollup_pretest.sql').write_text(out)
print('written')
