-- SENDER ROUTING 2.0 — PROPOSED INITIAL GRAPH SEED — PROPOSED, NOT APPLIED.
-- Generated 2026-10-08T00:53:34.255Z by apps/api/scripts/ops/sender-routing/build-seed-sql.mjs
-- from proposed-initial-graph.js (proposal-2026-10-07-r3) and the dry-run evidence of 2026-10-07T10:35:43.007Z.
--
-- APPLY ONLY AFTER: (1) 20261002130000_sender_routing_v2.sql is applied, and
-- (2) the owner has approved the graph table (owner / proposal / confirm rows).
-- Applying it does NOT enable routing: system_control.sender_routing_v2_enabled stays 'false'.
-- Idempotent (on conflict do nothing / guarded updates). Rollback: the 130000 rollback file.
--
-- r3 (owner regional map 2026-10-07). Indianapolis (+13173494612) and Tampa (+18138947553) finished
-- onboarding on 2026-10-03 and are regular members. Chicago (+18722547122) is written here as a
-- row only if absent (owner activated it on 2026-10-07; never paused here) and joins the chicago pool.
-- Registration / inbound evidence for every number: the 171000 evidence backfill (apply-time ledgers).
-- +13057604780 (local-only, retired, absent from the provider) is in no pool.
-- Unmapped markets (no routes; they HOLD as today): memphis-tn, new-orleans-la, louisville-ky, pittsburgh-pa, rochester-ny.
-- No BEGIN/COMMIT inside: apply with psql --single-transaction (or MCP apply_migration, which wraps it)
-- so the rollback-txn pretest (PROPOSED_20261007170000_..._pretest.sql) can \ir it inside ITS transaction.

-- ── 1. evidence (registration / inbound webhook) is NOT seeded here: it is computed at apply time from
--    the delivery + inbound ledgers by PROPOSED_20261007171000_sender_routing_v2_evidence_backfill.sql (next step).

-- ── 1b. Chicago +18722547122: ensure the row exists. ON CONFLICT DO NOTHING: an existing row (prod 2026-10-07:
--    owner-activated, active, 800/day) is never paused or changed. v2 still skips it until its first inbound
--    (webhook unverified); the evidence backfill flips it once that inbound lands.
insert into public.textgrid_numbers (phone_number, friendly_name, market, status, health_state, registration_status, daily_limit, messages_sent_today, metadata)
values ('+18722547122', 'CHICAGO', 'Chicago, IL', 'paused', 'unverified', 'registered', 800, 0, jsonb_build_object('market', 'Chicago, IL', 'friendly_name', 'CHICAGO', 'campaign_id_10dlc', 'CHM4NL2', 'onboarding_stage', 'configuring', 'sms_webhook_status', 'configured', 'provider_checked_at', '2026-10-07', 'onboarded_by', 'owner_approved_seed_r3'))
on conflict (phone_number) do nothing;

-- ── 2. pools (sending hubs) ──
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('minneapolis', 'Minneapolis', 'minneapolis-mn') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('st_louis', 'St. Louis', 'st-louis-mo') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('chicago', 'Chicago', 'chicago-il') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('indianapolis', 'Indianapolis', 'indianapolis-in') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('dallas', 'Dallas', 'dallas-tx') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('houston', 'Houston', 'houston-tx') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('los_angeles', 'Los Angeles', 'los-angeles-ca') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('atlanta', 'Atlanta', 'atlanta-ga') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('charlotte', 'Charlotte', 'charlotte-nc') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('jacksonville', 'Jacksonville', 'jacksonville-fl') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('tampa', 'Tampa', 'tampa-fl') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('miami', 'Miami', 'miami-fl') on conflict (pool_key) do nothing;

-- ── 3. pool membership (one pool per number) ──
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'minneapolis' and tn.phone_number = '+16128060495' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'minneapolis' and tn.phone_number = '+16125092382' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'minneapolis' and tn.phone_number = '+16125092623' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'st_louis' and tn.phone_number = '+13149268488' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'chicago' and tn.phone_number = '+18722547122' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'indianapolis' and tn.phone_number = '+13173494612' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'dallas' and tn.phone_number = '+14693131600' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'houston' and tn.phone_number = '+12818458577' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'los_angeles' and tn.phone_number = '+13234104544' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'los_angeles' and tn.phone_number = '+13235589881' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'atlanta' and tn.phone_number = '+14704920588' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'atlanta' and tn.phone_number = '+14702936385' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'atlanta' and tn.phone_number = '+14702936402' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'charlotte' and tn.phone_number = '+17042405818' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'charlotte' and tn.phone_number = '+19804589889' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'jacksonville' and tn.phone_number = '+19048774448' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'tampa' and tn.phone_number = '+18138947553' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'miami' and tn.phone_number = '+17866052999' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'miami' and tn.phone_number = '+13058975670' on conflict (textgrid_number_id) do nothing;

-- ── 4. market routes (array order = priority 10, 20, 30 …) ──
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'los-angeles-ca', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: LA local' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'los-angeles-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'inland-empire-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'inland-empire-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-diego-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-diego-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'bakersfield-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'bakersfield-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fresno-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fresno-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'modesto-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'modesto-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'stockton-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'stockton-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'sacramento-ca', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'sacramento-ca', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'las-vegas-nv', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'las-vegas-nv', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'phoenix-az', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'phoenix-az', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tucson-az', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tucson-az', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'salt-lake-city-ut', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'salt-lake-city-ut', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'boise-id', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'boise-id', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'spokane-wa', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'spokane-wa', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'seattle-wa', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'seattle-wa', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'albuquerque-nm', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'albuquerque-nm', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'colorado-springs-co', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: LA numbers cover the West' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'colorado-springs-co', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: West uses LA first, Dallas as last resort only' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'dallas-tx', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'dallas-tx', sp.id, 20, 'preferred_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'houston-tx', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'houston-tx', sp.id, 20, 'preferred_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'austin-tx', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'austin-tx', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-antonio-tx', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-antonio-tx', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'el-paso-tx', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'el-paso-tx', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'oklahoma-city-ok', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-02+owner 2026-10-07: Dallas covers Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'oklahoma-city-ok', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tulsa-ok', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-02+owner 2026-10-07: Dallas covers Oklahoma' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tulsa-ok', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Texas numbers cover all Texas markets and Oklahoma' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'miami-fl', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Florida numbers (Miami local)' from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'miami-fl', sp.id, 20, 'preferred_fallback', 'proposal', 'intra-Florida fallback, implied by ''Florida numbers''' from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'miami-fl', sp.id, 30, 'regional_fallback', 'proposal', 'intra-Florida fallback' from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tampa-fl', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Florida numbers (Tampa local)' from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tampa-fl', sp.id, 20, 'preferred_fallback', 'proposal', 'intra-Florida fallback, implied by ''Florida numbers''' from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tampa-fl', sp.id, 30, 'regional_fallback', 'proposal', 'intra-Florida fallback' from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'jacksonville-fl', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Florida numbers (Jacksonville local)' from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'jacksonville-fl', sp.id, 20, 'preferred_fallback', 'proposal', 'intra-Florida fallback, implied by ''Florida numbers''' from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'jacksonville-fl', sp.id, 30, 'regional_fallback', 'proposal', 'intra-Florida fallback' from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'orlando-fl', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Miami or Tampa cover Orlando (Tampa first: 85 mi)' from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'orlando-fl', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Miami or Tampa cover Orlando' from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'birmingham-al', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Florida numbers cover Alabama' from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'birmingham-al', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Florida numbers cover Alabama' from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'birmingham-al', sp.id, 30, 'last_resort', 'owner', 'owner 2026-10-07: Florida numbers cover Alabama' from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'chicago-il', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Chicago covers Chicago / IL' from public.sender_pools sp where sp.pool_key = 'chicago' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'chicago-il', sp.id, 20, 'preferred_fallback', 'owner', 'owner 2026-10-02: Indianapolis serves Chicago' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'chicago-il', sp.id, 30, 'regional_fallback', 'owner', 'owner 2026-10-02: Chicago -> Indianapolis / Minneapolis' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'detroit-mi', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Chicago covers Ohio markets and Detroit' from public.sender_pools sp where sp.pool_key = 'chicago' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'detroit-mi', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-02: Indianapolis serves Detroit' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cleveland-oh', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Chicago covers Ohio markets and Detroit' from public.sender_pools sp where sp.pool_key = 'chicago' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cleveland-oh', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-02: other Ohio: Indianapolis as lower priority' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cincinnati-oh', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-02: Indianapolis serves Cincinnati (110 mi)' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cincinnati-oh', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Chicago covers Ohio markets and Detroit' from public.sender_pools sp where sp.pool_key = 'chicago' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'columbus-oh', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-02: Indianapolis serves Columbus (175 mi)' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'columbus-oh', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Chicago covers Ohio markets and Detroit' from public.sender_pools sp where sp.pool_key = 'chicago' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'indianapolis-in', sp.id, 10, 'primary', 'owner', 'owner 2026-10-02: Indiana first' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'indianapolis-in', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — St. Louis nearer (240 mi)' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'indianapolis-in', sp.id, 30, 'last_resort', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis farther' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'st-louis-mo', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — St. Louis local' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'st-louis-mo', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis second' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'kansas-city-mo', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — same state, 314 is a Missouri code (250 mi)' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'kansas-city-mo', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis 440 mi' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'wichita-ks', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — nearest Midwest hub' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'wichita-ks', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis farther' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'minneapolis-mn', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis local' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'minneapolis-mn', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — St. Louis second' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'des-moines-ia', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis 245 mi' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'des-moines-ia', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — St. Louis 350 mi' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'omaha-ne', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis 380 mi; 10-02 MSP may serve NE' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'omaha-ne', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — St. Louis 440 mi' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'milwaukee-wi', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — Minneapolis; 10-02 MSP may serve WI' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'milwaukee-wi', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: St. Louis + Minneapolis cover Kansas City and the Midwest — St. Louis second' from public.sender_pools sp where sp.pool_key = 'st_louis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'atlanta-ga', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Atlanta local' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'atlanta-ga', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'charlotte-nc', sp.id, 10, 'primary', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Charlotte local' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'charlotte-nc', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'durham-nc', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Carolinas strong' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'durham-nc', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fayetteville-nc', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Carolinas strong' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fayetteville-nc', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'rocky-mount-nc', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Carolinas strong' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'rocky-mount-nc', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'richmond-va', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Virginia strong' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'richmond-va', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'hampton-roads-va', sp.id, 10, 'preferred_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Virginia strong' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'hampton-roads-va', sp.id, 20, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'baltimore-md', sp.id, 10, 'regional_fallback', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — Mid-Atlantic, broader than Carolinas/Virginia' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'baltimore-md', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'philadelphia-pa', sp.id, 10, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — farther Northeast: weak' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'philadelphia-pa', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — farther Northeast: weak' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'hartford-ct', sp.id, 10, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — farther Northeast: weak' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'hartford-ct', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — farther Northeast: weak' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'providence-ri', sp.id, 10, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — farther Northeast: weak' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'providence-ri', sp.id, 20, 'last_resort', 'owner', 'owner 2026-10-07: Charlotte and Atlanta cover the East Coast — farther Northeast: weak' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;

-- ── 5. version + audit ──
insert into public.sender_routing_audit (graph_version, event_type, actor, reason, subject)
select nextval('public.sender_routing_graph_version_seq'), 'graph_seed', 'owner_approved_seed', 'proposal proposal-2026-10-07-r3', jsonb_build_object('markets', 53, 'pools', 12)
 where not exists (select 1 from public.sender_routing_audit where event_type = 'graph_seed' and reason = 'proposal proposal-2026-10-07-r3');
