-- SENDER ROUTING 2.0 — PROPOSED INITIAL GRAPH SEED — PROPOSED, NOT APPLIED.
-- Generated 2026-10-02T23:24:48.393Z by apps/api/scripts/ops/sender-routing/build-seed-sql.mjs
-- from proposed-initial-graph.js (proposal-2026-10-02) and the dry-run evidence of 2026-10-02T23:22:36.169Z.
--
-- APPLY ONLY AFTER: (1) 20261002130000_sender_routing_v2.sql is applied, and
-- (2) the owner has approved the graph table (owner / proposal / confirm rows).
-- Applying it does NOT enable routing: system_control.sender_routing_v2_enabled stays 'false'.
-- Idempotent (on conflict do nothing / guarded updates). Rollback: the 130000 rollback file.
--
-- Indianapolis (+13173494612) and Tampa (+18138947553) are NOT in textgrid_numbers yet, so they
-- get no pool membership here; their pools exist (empty) and fill on onboarding
-- (scripts/ops/sender-routing/sql/onboard-indianapolis-tampa.sql, WARMING step).
-- +13057604780 (local-only, absent from the provider) is in no pool (retirement script).

begin;

-- ── 1. evidence backfill on textgrid_numbers (registration + webhook evidence only) ──
--    registered   = provider (TextGrid API GET, 2026-10-02) reports campaign CHM4NL2 and nothing local disputes it
--    verified     = inbound SMS has reached LeadCommand on the number (message_events history)
--    configured   = provider points at the inbound URL; no inbound yet
--    Atlanta 2 / Atlanta 3 are NOT marked registered: the API says CHM4NL2, the owner's console paste and the local
--    hold_reason say "not linked" — CONFIG MISMATCH until the owner confirms.
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+12818458577';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+13058975670';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'configured', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+13234104544';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+13235589881';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+14693131600';
update public.textgrid_numbers set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'configured', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+14702936385';
update public.textgrid_numbers set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'configured', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+14702936402';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+14704920588';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+16125092382';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+16125092623';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+16128060495';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+17042405818';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+17866052999';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+19048774448';
update public.textgrid_numbers set registration_status = coalesce(registration_status, 'registered'), metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('sms_webhook_status', 'verified', 'sms_webhook_evidence_at', '2026-10-02') where phone_number = '+19804589889';

-- ── 2. pools (sending hubs) ──
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('minneapolis', 'Minneapolis', 'minneapolis-mn') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('dallas', 'Dallas', 'dallas-tx') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('houston', 'Houston', 'houston-tx') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('los_angeles', 'Los Angeles', 'los-angeles-ca') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('atlanta', 'Atlanta', 'atlanta-ga') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('charlotte', 'Charlotte', 'charlotte-nc') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('jacksonville', 'Jacksonville', 'jacksonville-fl') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('miami', 'Miami', 'miami-fl') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('indianapolis', 'Indianapolis', 'indianapolis-in') on conflict (pool_key) do nothing;
insert into public.sender_pools (pool_key, display_name, home_market_id) values ('tampa', 'Tampa', 'tampa-fl') on conflict (pool_key) do nothing;

-- ── 3. pool membership (one pool per number) ──
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'minneapolis' and tn.phone_number = '+16128060495' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'minneapolis' and tn.phone_number = '+16125092382' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'minneapolis' and tn.phone_number = '+16125092623' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'dallas' and tn.phone_number = '+14693131600' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'houston' and tn.phone_number = '+12818458577' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'los_angeles' and tn.phone_number = '+13234104544' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'los_angeles' and tn.phone_number = '+13235589881' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'atlanta' and tn.phone_number = '+14704920588' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'atlanta' and tn.phone_number = '+14702936385' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'atlanta' and tn.phone_number = '+14702936402' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'charlotte' and tn.phone_number = '+17042405818' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'charlotte' and tn.phone_number = '+19804589889' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'jacksonville' and tn.phone_number = '+19048774448' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'miami' and tn.phone_number = '+17866052999' on conflict (textgrid_number_id) do nothing;
insert into public.sender_pool_numbers (sender_pool_id, textgrid_number_id) select sp.id, tn.id from public.sender_pools sp, public.textgrid_numbers tn where sp.pool_key = 'miami' and tn.phone_number = '+13058975670' on conflict (textgrid_number_id) do nothing;

-- ── 4. market routes (array order = priority 10, 20, 30 …) ──
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'minneapolis-mn', sp.id, 10, 'primary', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'milwaukee-wi', sp.id, 10, 'preferred_fallback', 'owner', 'Minneapolis may serve WI' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'des-moines-ia', sp.id, 10, 'preferred_fallback', 'owner', 'Minneapolis may serve IA' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'omaha-ne', sp.id, 10, 'preferred_fallback', 'owner', 'Minneapolis may serve NE' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'st-louis-mo', sp.id, 10, 'preferred_fallback', 'owner', 'Minneapolis may serve St. Louis' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'st-louis-mo', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'chicago-il', sp.id, 10, 'preferred_fallback', 'owner', 'Chicago -> Indianapolis / Minneapolis' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'chicago-il', sp.id, 20, 'regional_fallback', 'owner', 'Chicago -> Indianapolis / Minneapolis' from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'indianapolis-in', sp.id, 10, 'primary', 'owner', 'Indianapolis -> Indianapolis first' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'indianapolis-in', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'detroit-mi', sp.id, 10, 'preferred_fallback', 'owner', 'Indianapolis -> ... Detroit' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'detroit-mi', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'columbus-oh', sp.id, 10, 'preferred_fallback', 'confirm', 'Indianapolis -> selected Ohio' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'columbus-oh', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cincinnati-oh', sp.id, 10, 'preferred_fallback', 'confirm', 'Indianapolis -> selected Ohio' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cincinnati-oh', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cleveland-oh', sp.id, 10, 'preferred_fallback', 'confirm', 'Indianapolis -> selected Ohio' from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'cleveland-oh', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'kansas-city-mo', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'kansas-city-mo', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'wichita-ks', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'wichita-ks', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'minneapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'dallas-tx', sp.id, 10, 'primary', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'dallas-tx', sp.id, 20, 'preferred_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'houston-tx', sp.id, 10, 'primary', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'houston-tx', sp.id, 20, 'preferred_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'austin-tx', sp.id, 10, 'preferred_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'austin-tx', sp.id, 20, 'regional_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-antonio-tx', sp.id, 10, 'preferred_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-antonio-tx', sp.id, 20, 'regional_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'el-paso-tx', sp.id, 10, 'preferred_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'el-paso-tx', sp.id, 20, 'regional_fallback', 'owner', 'Texas hub serves TX' from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'oklahoma-city-ok', sp.id, 10, 'preferred_fallback', 'confirm', 'Texas hub + selected OK' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'oklahoma-city-ok', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tulsa-ok', sp.id, 10, 'preferred_fallback', 'confirm', 'Texas hub + selected OK' from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tulsa-ok', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'new-orleans-la', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'houston' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'new-orleans-la', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'los-angeles-ca', sp.id, 10, 'primary', 'owner', 'LA serves SoCal' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'inland-empire-ca', sp.id, 10, 'preferred_fallback', 'owner', 'LA serves SoCal' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'san-diego-ca', sp.id, 10, 'preferred_fallback', 'owner', 'LA serves SoCal' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'bakersfield-ca', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'las-vegas-nv', sp.id, 10, 'preferred_fallback', 'owner', 'LA serves Las Vegas' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'phoenix-az', sp.id, 10, 'preferred_fallback', 'owner', 'LA serves Phoenix-AZ' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tucson-az', sp.id, 10, 'preferred_fallback', 'owner', 'LA serves Phoenix-AZ' from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fresno-ca', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'modesto-ca', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'stockton-ca', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'sacramento-ca', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'boise-id', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'salt-lake-city-ut', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'spokane-wa', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'seattle-wa', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'albuquerque-nm', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'albuquerque-nm', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'colorado-springs-co', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'colorado-springs-co', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'los_angeles' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'atlanta-ga', sp.id, 10, 'primary', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'atlanta-ga', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'birmingham-al', sp.id, 10, 'preferred_fallback', 'owner', 'Birmingham -> Atlanta / Southeast' from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'birmingham-al', sp.id, 20, 'regional_fallback', 'owner', 'Birmingham -> Atlanta / Southeast' from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'memphis-tn', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'memphis-tn', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'dallas' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'louisville-ky', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'indianapolis' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'louisville-ky', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'charlotte-nc', sp.id, 10, 'primary', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'charlotte-nc', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'durham-nc', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'durham-nc', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fayetteville-nc', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'fayetteville-nc', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'rocky-mount-nc', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'rocky-mount-nc', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'atlanta' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'richmond-va', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'hampton-roads-va', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'baltimore-md', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'miami-fl', sp.id, 10, 'primary', 'proposal', null from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'miami-fl', sp.id, 20, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'miami-fl', sp.id, 30, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tampa-fl', sp.id, 10, 'primary', 'proposal', null from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tampa-fl', sp.id, 20, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'tampa-fl', sp.id, 30, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'orlando-fl', sp.id, 10, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'orlando-fl', sp.id, 20, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'orlando-fl', sp.id, 30, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'jacksonville-fl', sp.id, 10, 'primary', 'proposal', null from public.sender_pools sp where sp.pool_key = 'jacksonville' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'jacksonville-fl', sp.id, 20, 'preferred_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'tampa' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'jacksonville-fl', sp.id, 30, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'miami' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'philadelphia-pa', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'pittsburgh-pa', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'hartford-ct', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'providence-ri', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;
insert into public.market_sender_routes (market_id, sender_pool_id, priority, affinity_tier, provenance, notes) select 'rochester-ny', sp.id, 10, 'regional_fallback', 'proposal', null from public.sender_pools sp where sp.pool_key = 'charlotte' on conflict (market_id, sender_pool_id) do nothing;

-- ── 5. version + audit ──
insert into public.sender_routing_audit (graph_version, event_type, actor, reason, subject)
select nextval('public.sender_routing_graph_version_seq'), 'graph_seed', 'owner_approved_seed', 'proposal proposal-2026-10-02', jsonb_build_object('markets', 58, 'pools', 10)
 where not exists (select 1 from public.sender_routing_audit where event_type = 'graph_seed' and reason = 'proposal proposal-2026-10-02');

commit;
