-- POST-APPLY VERIFICATION for PROPOSED_20261005140000_market_intel_inferred_investor.sql. GENERATED by apps/api/scripts/market-intel-make-inferred-migration.py.
-- READ-ONLY. Run after the first build with the extension is READY (notes ? 'inferred_investor'), outside
-- 05:00-08:59 / 09:15-11:59 UTC, with SET statement_timeout = '60s'.
-- Statement 1 (assertion): the extension never changes RECORDED counts. For the newest ready build that
--   carries notes.inferred_investor, its recorded nation and per-state rows (period 'all', asset 'all':
--   sale_count, investor_count, buyer_known_count) must equal a fresh count over the live source
--   (public.mi_rollup_sales_v), and the inferred sale_count must equal the recorded one. Guarded by the
--   source fingerprint: mv_map_market_sales refreshes daily (rolling 5-year window: build 2 665,245 ->
--   build 4 665,232), so run this the same day the build finished; if the source moved, it RAISEs
--   'verify INCONCLUSIVE' instead of a false failure. Any difference: 'verify FAILED'.
--   It also lists the previous core build's recorded nation counts as context (they differ by the drift).
-- Statement 2 (report): nation — eligible sales, linked latest sales, strong / likely inferred, unresolved by
--   reason, recorded buyer coverage, inferred coverage, the validation matrix — and the top 15 markets (1y),
--   each against the 10-05 validation snapshot. status: PASS (|delta| <= max(50, 0.1%)), CHECK (look at it),
--   INFO (markets: the snapshot used the JS market assignment, so they are context, not a gate).
DO $verify$
DECLARE
  b bigint;
  fb jsonb;
  src record;
  n bigint;
  prev record;
BEGIN
  SELECT build_id, fingerprint INTO b, fb FROM public.mi_rollup_builds
   WHERE status = 'ready' AND notes ? 'inferred_investor' ORDER BY build_id DESC LIMIT 1;
  IF b IS NULL THEN RAISE EXCEPTION 'verify FAILED: no ready build carries notes.inferred_investor yet'; END IF;
  SELECT count(*) AS n, max(sold_on) AS last, min(sold_on) AS first, coalesce(sum(price), 0)::text AS psum INTO src FROM public.mi_rollup_sales_v;
  IF src.n <> (fb ->> 'rows')::bigint OR src.last::text <> fb ->> 'as_of' OR src.first::text <> fb ->> 'first' OR src.psum <> fb ->> 'price_sum' THEN
    RAISE EXCEPTION 'verify INCONCLUSIVE: the source moved since build % (build: % rows %..% · now: % rows %..%); verify on the day the build finishes',
      b, fb ->> 'rows', fb ->> 'first', fb ->> 'as_of', src.n, src.first, src.last;
  END IF;
  SELECT count(*) INTO n FROM (
    SELECT 'nation' AS geo_level, 'US'::text AS geo_key, count(*)::int AS sale_count, count(*) FILTER (WHERE v.is_investor)::int AS investor_count,
           count(*) FILTER (WHERE v.buyer_known)::int AS buyer_known_count FROM public.mi_rollup_sales_v v
    UNION ALL
    SELECT 'state', v.state, count(*)::int, count(*) FILTER (WHERE v.is_investor)::int, count(*) FILTER (WHERE v.buyer_known)::int
      FROM public.mi_rollup_sales_v v GROUP BY v.state) live
    FULL JOIN (SELECT r.geo_level, r.geo_key, r.sale_count, r.investor_count, r.buyer_known_count FROM public.mi_geo_period_rollup r
                WHERE r.build_id = b AND r.geo_level IN ('nation', 'state') AND r.period = 'all' AND r.asset = 'all') rec
    USING (geo_level, geo_key)
   WHERE live.sale_count IS DISTINCT FROM rec.sale_count OR live.investor_count IS DISTINCT FROM rec.investor_count
      OR live.buyer_known_count IS DISTINCT FROM rec.buyer_known_count;
  IF n > 0 THEN RAISE EXCEPTION 'verify FAILED: recorded counts of build % differ from the live source in % nation/state rows', b, n; END IF;
  SELECT count(*) INTO n FROM public.mi_geo_period_rollup r
    JOIN public.mi_geo_period_inferred i USING (build_id, geo_level, geo_key, period, asset)
   WHERE r.build_id = b AND r.sale_count IS DISTINCT FROM i.sale_count;
  IF n > 0 THEN RAISE EXCEPTION 'verify FAILED: inferred sale_count differs from recorded sale_count in % rows (build %)', n, b; END IF;
  SELECT r.build_id, r.sale_count, r.investor_count, r.buyer_known_count INTO prev FROM public.mi_geo_period_rollup r
   WHERE r.build_id = (SELECT max(build_id) FROM public.mi_rollup_builds WHERE build_id < b AND status IN ('ready', 'superseded'))
     AND r.geo_level = 'nation' AND r.period = 'all' AND r.asset = 'all';
  RAISE NOTICE 'verify: recorded counts of build % equal the live source; previous core build % (context): sales % · investor % · buyer_known %',
    b, prev.build_id, prev.sale_count, prev.investor_count, prev.buyer_known_count;
END
$verify$;

with bld as (
  select build_id as b, notes -> 'inferred_investor' as ii from public.mi_rollup_builds
   where status = 'ready' and notes ? 'inferred_investor' order by build_id desc limit 1
), inf as (
  select r.* from public.mi_geo_period_inferred r, bld
   where r.build_id = bld.b and r.geo_level = 'nation' and r.geo_key = 'US' and r.period = 'all' and r.asset = 'all'
), rec as (
  select r.* from public.mi_geo_period_rollup r, bld
   where r.build_id = bld.b and r.geo_level = 'nation' and r.geo_key = 'US' and r.period = 'all' and r.asset = 'all'
), reasons as (
  select 'reason:' || l.link as k, count(*)::bigint as v from public.mi_sale_owner_link l, bld where l.build_id = bld.b group by l.link
), nation(k, v) as (
  select 'sales', inf.sale_count::bigint from inf union all
  select 'linked', inf.linked_count from inf union all
  select 'strong', inf.strong_n from inf union all
  select 'likely', inf.likely_n from inf union all
  select 'trust_estate', inf.trust_n from inf union all
  select 'absentee_only', inf.absentee_n from inf union all
  select 'no_signal', inf.no_signal_n from inf union all
  select 'buyer_known', rec.buyer_known_count from rec union all
  select 'recorded_investor', rec.investor_count from rec union all
  select s.k, coalesce(r.v, 0) from (values ('reason:linked'), ('reason:not_latest_sale'), ('reason:later_transfer'), ('reason:no_owner_record'),
         ('reason:owner_snapshot_before_sale'), ('reason:no_property')) s(k) left join reasons r using (k)
), snap(k, v) as (values ('sales', 665288), ('linked', 598841), ('strong', 95776), ('likely', 60997), ('trust_estate', 1881), ('absentee_only', 12643), ('no_signal', 427544), ('buyer_known', 52766), ('recorded_investor', 13183), ('reason:linked', 598841), ('reason:not_latest_sale', 14387), ('reason:later_transfer', 1), ('reason:no_owner_record', 24410), ('reason:owner_snapshot_before_sale', 27649), ('reason:no_property', 0)),
snapm(tier, inv, other) as (values ('strong', 2256, 340), ('likely', 2853, 416), ('trust_estate', 431, 1436), ('absentee_only', 35, 1041), ('no_signal', 752, 26783)),
snapk(slug, sales, buyer_known, linked, inferred_share) as (values ('houston-tx', 74440, 6295, 69418, 0.279), ('dallas-tx', 56744, 3244, 53039, 0.307), ('los-angeles-ca', 51334, 6998, 47805, 0.241), ('miami-fl', 49408, 194, 47826, 0.28), ('atlanta-ga', 32822, 77, 31879, 0.35), ('minneapolis-mn', 24074, 2967, 21980, 0.152), ('orlando-fl', 20221, 27, 19306, 0.248), ('inland-empire-ca', 19098, 4407, 18060, 0.129), ('tampa-fl', 19093, 74, 18024, 0.204), ('st-louis-mo', 18843, 98, 16872, 0.389), ('jacksonville-fl', 17815, 74, 16934, 0.298), ('indianapolis-in', 14740, 79, 13981, 0.393), ('sacramento-ca', 14366, 1713, 13348, 0.145), ('phoenix-az', 8818, 7081, 6324, 0.155), ('charlotte-nc', 8108, 28, 7722, 0.27))
select 1 as ord, 'nation' as section, n.k as metric, n.v::numeric as value, s.v::numeric as snapshot_10_05, (n.v - s.v)::numeric as delta,
       case when abs(n.v - s.v) <= greatest(50, 0.001 * s.v) then 'PASS' else 'CHECK' end as status
  from nation n join snap s using (k)
union all
select 2, 'nation', x.metric, x.value, x.snap, round(x.value - x.snap, 4), case when abs(x.value - x.snap) <= 0.002 then 'PASS' else 'CHECK' end
  from (select 'recorded_buyer_coverage' as metric, round(rec.buyer_known_count::numeric / nullif(rec.sale_count, 0), 4) as value, round(52766 / 665288.0, 4) as snap from rec
        union all select 'inferred_coverage (linked / sales)', round(inf.linked_count::numeric / nullif(inf.sale_count, 0), 4), round(598841 / 665288.0, 4) from inf
        union all select 'inferred_share (strong+likely / linked)', round((inf.strong_n + inf.likely_n)::numeric / nullif(inf.linked_count, 0), 4), round((95776 + 60997) / 598841.0, 4) from inf) x
union all
select 3, 'validation', m.tier || ' · ' || x.col, x.value, x.snap, x.value - x.snap,
       case when abs(x.value - x.snap) <= greatest(25, 0.01 * x.snap) then 'PASS' else 'CHECK' end
  from snapm m cross join bld
  cross join lateral (values ('recorded_investor', (bld.ii -> 'matrix' -> m.tier ->> 'recorded_investor')::numeric, m.inv::numeric),
                             ('recorded_other', (bld.ii -> 'matrix' -> m.tier ->> 'recorded_other')::numeric, m.other::numeric)) x(col, value, snap)
union all
select 4, 'market 1y · ' || k.slug, x.metric, x.value, x.snap, round(x.value - x.snap, 4), 'INFO'
  from snapk k
  left join public.mi_geo_period_inferred i on i.build_id = (select b from bld) and i.geo_level = 'market' and i.geo_key = k.slug and i.period = '1y' and i.asset = 'all'
  left join public.mi_geo_period_rollup r on r.build_id = (select b from bld) and r.geo_level = 'market' and r.geo_key = k.slug and r.period = '1y' and r.asset = 'all'
  cross join lateral (values
    ('sales', r.sale_count::numeric, k.sales::numeric),
    ('recorded_buyer_coverage', round(r.buyer_known_count::numeric / nullif(r.sale_count, 0), 4), round(k.buyer_known::numeric / k.sales, 4)),
    ('recorded_investor_share (of buyer_known)', round(r.investor_count::numeric / nullif(r.buyer_known_count, 0), 4), null::numeric),
    ('inferred_coverage (linked / sales)', round(i.linked_count::numeric / nullif(i.sale_count, 0), 4), round(k.linked::numeric / k.sales, 4)),
    ('inferred_share (strong+likely / linked)', round((i.strong_n + i.likely_n)::numeric / nullif(i.linked_count, 0), 4), k.inferred_share::numeric)) x(metric, value, snap)
order by 1, 2, 3;
