-- PROPOSED — NOT APPLIED. REQUIRES OWNER APPROVAL OF THE WORDING.
-- 30 sms_templates rows (EN + ES), every one INACTIVE and safe_for_auto_reply = false:
--   s3_no_response_fu1 / _fu2 / _nurture   S3 asking-price question unanswered (+24h / +72h / +30d)
--   condition_probe (S4) residential x3    natural condition question after the seller's price
--   condition_probe (S4) commercial  x3    commercial wording only (never move-in / roof / HVAC)
-- Activate per row after approval:
--   update public.sms_templates set is_active = true, safe_for_auto_reply = true, updated_at = now()
--    where template_id in (...approved ids...);
-- Idempotent: inserts only template_ids that do not exist yet.

begin;
set local lock_timeout = '5s';

insert into public.sms_templates (
  use_case, template_id, template_name, language, template_body,
  english_translation, variables, is_active, safe_for_auto_reply, reply_mode,
  identity_contact_mode, property_type_scope, allowed_property_groups, prohibited_property_groups,
  stage_code, stage_label, is_first_touch, is_follow_up, minimal_fallback, fallback_rank, quarantine_state, metadata
)
select v.use_case, v.template_id, v.template_name, v.language, v.template_body,
       v.english_translation, '{}'::jsonb, false, false, 'auto',
       'neutral', v.property_type_scope, v.allowed_property_groups, v.prohibited_property_groups,
       v.stage_code, v.stage_label, false, v.is_follow_up, v.minimal_fallback, v.fallback_rank, 'active',
       jsonb_build_object(
         'authored_by', 'seller_flow_followups_2026_10_10',
         'approval_status', 'proposed_pending_owner_approval',
         'variant', v.variant,
         'fires', v.fires,
         'asset_scope', v.asset_scope
       )
from (values
  ('s3_no_response_fu1', 'lc-s3fu1-en-a', 's3_no_response_fu1 — English A (Stage 3 No-Response Follow-Up)', 'English', 'Hey {{seller_first_name}}, just checking back. Do you have an asking price in mind for the property?', null, 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'A', '24h after our S3 asking-price question (templated or typed) with no reply.', 'residential'),
  ('s3_no_response_fu1', 'lc-s3fu1-en-b', 's3_no_response_fu1 — English B (Stage 3 No-Response Follow-Up)', 'English', 'Hi {{seller_first_name}}, no rush at all. What price would you need to sell the property?', null, 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'B', '24h after our S3 asking-price question (templated or typed) with no reply.', 'residential'),
  ('s3_no_response_fu1', 'lc-s3fu1-en-n', 's3_no_response_fu1 — English N (Stage 3 No-Response Follow-Up)', 'English', 'Just checking back. Do you have an asking price in mind for the property?', null, 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, true, 9, 'N', '24h after our S3 asking-price question (templated or typed) with no reply.', 'residential'),
  ('s3_no_response_fu1', 'lc-s3fu1-es-a', 's3_no_response_fu1 — Spanish A (Stage 3 No-Response Follow-Up)', 'Spanish', 'Hola {{seller_first_name}}, solo para darle seguimiento. ¿Tiene un precio en mente para la propiedad?', 'Hey {{seller_first_name}}, just checking back. Do you have an asking price in mind for the property?', 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'A', '24h after our S3 asking-price question (templated or typed) with no reply.', 'residential'),
  ('s3_no_response_fu1', 'lc-s3fu1-es-b', 's3_no_response_fu1 — Spanish B (Stage 3 No-Response Follow-Up)', 'Spanish', 'Hola {{seller_first_name}}, sin prisa. ¿Qué precio necesitaría para vender la propiedad?', 'Hi {{seller_first_name}}, no rush at all. What price would you need to sell the property?', 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'B', '24h after our S3 asking-price question (templated or typed) with no reply.', 'residential'),
  ('s3_no_response_fu1', 'lc-s3fu1-es-n', 's3_no_response_fu1 — Spanish N (Stage 3 No-Response Follow-Up)', 'Spanish', 'Solo para darle seguimiento. ¿Tiene un precio en mente para la propiedad?', 'Just checking back. Do you have an asking price in mind for the property?', 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, true, 9, 'N', '24h after our S3 asking-price question (templated or typed) with no reply.', 'residential'),
  ('s3_no_response_fu2', 'lc-s3fu2-en-a', 's3_no_response_fu2 — English A (Stage 3 No-Response Follow-Up)', 'English', '{{seller_first_name}}, following up one more time. Even a ballpark number helps. What would you want for the property?', null, 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'A', '72h after the S3 FU1 with no reply. Different wording from FU1.', 'residential'),
  ('s3_no_response_fu2', 'lc-s3fu2-en-b', 's3_no_response_fu2 — English B (Stage 3 No-Response Follow-Up)', 'English', 'Hi {{seller_first_name}}, if you share a rough price you''d sell for, I can tell you quickly if I can make it work.', null, 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'B', '72h after the S3 FU1 with no reply. Different wording from FU1.', 'residential'),
  ('s3_no_response_fu2', 'lc-s3fu2-en-n', 's3_no_response_fu2 — English N (Stage 3 No-Response Follow-Up)', 'English', 'Following up one more time. Even a ballpark number helps. What would you want for the property?', null, 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, true, 9, 'N', '72h after the S3 FU1 with no reply. Different wording from FU1.', 'residential'),
  ('s3_no_response_fu2', 'lc-s3fu2-es-a', 's3_no_response_fu2 — Spanish A (Stage 3 No-Response Follow-Up)', 'Spanish', '{{seller_first_name}}, le escribo una vez más. Aunque sea un número aproximado me ayuda. ¿Cuánto quisiera por la propiedad?', '{{seller_first_name}}, following up one more time. Even a ballpark number helps. What would you want for the property?', 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'A', '72h after the S3 FU1 with no reply. Different wording from FU1.', 'residential'),
  ('s3_no_response_fu2', 'lc-s3fu2-es-b', 's3_no_response_fu2 — Spanish B (Stage 3 No-Response Follow-Up)', 'Spanish', 'Hola {{seller_first_name}}, si me comparte un precio aproximado, le digo rápido si lo puedo hacer funcionar.', 'Hi {{seller_first_name}}, if you share a rough price you''d sell for, I can tell you quickly if I can make it work.', 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'B', '72h after the S3 FU1 with no reply. Different wording from FU1.', 'residential'),
  ('s3_no_response_fu2', 'lc-s3fu2-es-n', 's3_no_response_fu2 — Spanish N (Stage 3 No-Response Follow-Up)', 'Spanish', 'Le escribo una vez más. Aunque sea un número aproximado me ayuda. ¿Cuánto quisiera por la propiedad?', 'Following up one more time. Even a ballpark number helps. What would you want for the property?', 'S3F', 'Stage 3 No-Response Follow-Up', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, true, 9, 'N', '72h after the S3 FU1 with no reply. Different wording from FU1.', 'residential'),
  ('s3_no_response_nurture', 'lc-s3nur-en-a', 's3_no_response_nurture — English A (Stage 3 No-Response Nurture)', 'English', 'Hi {{seller_first_name}}, checking back in on the property. If you''re still open to selling, what price would you have in mind?', null, 'S3F', 'Stage 3 No-Response Nurture', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'A', '30 days after the S3 FU2. Last touch of the chain.', 'residential'),
  ('s3_no_response_nurture', 'lc-s3nur-en-b', 's3_no_response_nurture — English B (Stage 3 No-Response Nurture)', 'English', 'Hey {{seller_first_name}}, circling back. If the timing is better now, do you have a number in mind for the property?', null, 'S3F', 'Stage 3 No-Response Nurture', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'B', '30 days after the S3 FU2. Last touch of the chain.', 'residential'),
  ('s3_no_response_nurture', 'lc-s3nur-en-n', 's3_no_response_nurture — English N (Stage 3 No-Response Nurture)', 'English', 'Checking back in on the property. If you''re still open to selling, what price would you have in mind?', null, 'S3F', 'Stage 3 No-Response Nurture', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, true, 9, 'N', '30 days after the S3 FU2. Last touch of the chain.', 'residential'),
  ('s3_no_response_nurture', 'lc-s3nur-es-a', 's3_no_response_nurture — Spanish A (Stage 3 No-Response Nurture)', 'Spanish', 'Hola {{seller_first_name}}, le escribo de nuevo sobre la propiedad. Si todavía piensa vender, ¿qué precio tendría en mente?', 'Hi {{seller_first_name}}, checking back in on the property. If you''re still open to selling, what price would you have in mind?', 'S3F', 'Stage 3 No-Response Nurture', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'A', '30 days after the S3 FU2. Last touch of the chain.', 'residential'),
  ('s3_no_response_nurture', 'lc-s3nur-es-b', 's3_no_response_nurture — Spanish B (Stage 3 No-Response Nurture)', 'Spanish', 'Hola {{seller_first_name}}, le doy seguimiento. Si ahora es mejor momento, ¿tiene un número en mente para la propiedad?', 'Hey {{seller_first_name}}, circling back. If the timing is better now, do you have a number in mind for the property?', 'S3F', 'Stage 3 No-Response Nurture', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, false, 1, 'B', '30 days after the S3 FU2. Last touch of the chain.', 'residential'),
  ('s3_no_response_nurture', 'lc-s3nur-es-n', 's3_no_response_nurture — Spanish N (Stage 3 No-Response Nurture)', 'Spanish', 'Le escribo de nuevo sobre la propiedad. Si todavía piensa vender, ¿qué precio tendría en mente?', 'Checking back in on the property. If you''re still open to selling, what price would you have in mind?', 'S3F', 'Stage 3 No-Response Nurture', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], true, true, 9, 'N', '30 days after the S3 FU2. Last touch of the chain.', 'residential'),
  ('condition_probe', 'lc-s4-cond-res-en-1', 'condition_probe — English 1 (Stage 4 Condition)', 'English', 'Got it, thanks. What kind of shape is the property in? Any repairs it needs?', null, 'S4', 'Stage 4 Condition', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], false, false, 9, '1', 'Seller gave their price (S3 answered); we ask condition before any offer. Residential assets only.', 'residential'),
  ('condition_probe', 'lc-s4-cond-res-en-2', 'condition_probe — English 2 (Stage 4 Condition)', 'English', 'Appreciate that. Has the place been updated, or does it need some work?', null, 'S4', 'Stage 4 Condition', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], false, false, 9, '2', 'Seller gave their price (S3 answered); we ask condition before any offer. Residential assets only.', 'residential'),
  ('condition_probe', 'lc-s4-cond-res-en-3', 'condition_probe — English 3 (Stage 4 Condition)', 'English', 'Thanks. Is the property in good shape, or are there repairs you know about?', null, 'S4', 'Stage 4 Condition', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], false, false, 9, '3', 'Seller gave their price (S3 answered); we ask condition before any offer. Residential assets only.', 'residential'),
  ('condition_probe', 'lc-s4-cond-res-es-1', 'condition_probe — Spanish 1 (Stage 4 Condition)', 'Spanish', 'Entendido, gracias. ¿En qué estado está la propiedad? ¿Necesita alguna reparación?', 'Got it, thanks. What kind of shape is the property in? Any repairs it needs?', 'S4', 'Stage 4 Condition', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], false, false, 9, '1', 'Seller gave their price (S3 answered); we ask condition before any offer. Residential assets only.', 'residential'),
  ('condition_probe', 'lc-s4-cond-res-es-2', 'condition_probe — Spanish 2 (Stage 4 Condition)', 'Spanish', 'Gracias. ¿La propiedad está actualizada o necesita algo de trabajo?', 'Appreciate that. Has the place been updated, or does it need some work?', 'S4', 'Stage 4 Condition', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], false, false, 9, '2', 'Seller gave their price (S3 answered); we ask condition before any offer. Residential assets only.', 'residential'),
  ('condition_probe', 'lc-s4-cond-res-es-3', 'condition_probe — Spanish 3 (Stage 4 Condition)', 'Spanish', 'Gracias. ¿La propiedad está en buen estado o sabe de alguna reparación que necesite?', 'Thanks. Is the property in good shape, or are there repairs you know about?', 'S4', 'Stage 4 Condition', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], null::text[], false, false, 9, '3', 'Seller gave their price (S3 answered); we ask condition before any offer. Residential assets only.', 'residential'),
  ('condition_probe', 'lc-s4-cond-com-en-1', 'condition_probe — English 1 (Stage 4 Condition (Commercial))', 'English', 'Got it, thanks. How is the building holding up overall? Any deferred maintenance I should know about?', null, 'S4', 'Stage 4 Condition (Commercial)', 'Commercial (Other)', array['self_storage','retail','office','industrial','hotel_motel','mobile_home_park','other_commercial']::text[], array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus','land']::text[], false, false, 9, '1', 'Seller gave their price (S3 answered); commercial assets (retail, office, industrial, storage, hotel, MHP, other commercial).', 'commercial'),
  ('condition_probe', 'lc-s4-cond-com-en-2', 'condition_probe — English 2 (Stage 4 Condition (Commercial))', 'English', 'Appreciate it. What does occupancy look like right now, and is there any major work the property needs?', null, 'S4', 'Stage 4 Condition (Commercial)', 'Commercial (Other)', array['self_storage','retail','office','industrial','hotel_motel','mobile_home_park','other_commercial']::text[], array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus','land']::text[], false, false, 9, '2', 'Seller gave their price (S3 answered); commercial assets (retail, office, industrial, storage, hotel, MHP, other commercial).', 'commercial'),
  ('condition_probe', 'lc-s4-cond-com-en-3', 'condition_probe — English 3 (Stage 4 Condition (Commercial))', 'English', 'Thanks. Is the property leased up and in decent shape, or does it need some work?', null, 'S4', 'Stage 4 Condition (Commercial)', 'Commercial (Other)', array['self_storage','retail','office','industrial','hotel_motel','mobile_home_park','other_commercial']::text[], array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus','land']::text[], false, false, 9, '3', 'Seller gave their price (S3 answered); commercial assets (retail, office, industrial, storage, hotel, MHP, other commercial).', 'commercial'),
  ('condition_probe', 'lc-s4-cond-com-es-1', 'condition_probe — Spanish 1 (Stage 4 Condition (Commercial))', 'Spanish', 'Entendido, gracias. ¿Cómo está el edificio en general? ¿Hay mantenimiento pendiente que deba saber?', 'Got it, thanks. How is the building holding up overall? Any deferred maintenance I should know about?', 'S4', 'Stage 4 Condition (Commercial)', 'Commercial (Other)', array['self_storage','retail','office','industrial','hotel_motel','mobile_home_park','other_commercial']::text[], array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus','land']::text[], false, false, 9, '1', 'Seller gave their price (S3 answered); commercial assets (retail, office, industrial, storage, hotel, MHP, other commercial).', 'commercial'),
  ('condition_probe', 'lc-s4-cond-com-es-2', 'condition_probe — Spanish 2 (Stage 4 Condition (Commercial))', 'Spanish', 'Gracias. ¿Cómo está la ocupación ahora y la propiedad necesita algún trabajo importante?', 'Appreciate it. What does occupancy look like right now, and is there any major work the property needs?', 'S4', 'Stage 4 Condition (Commercial)', 'Commercial (Other)', array['self_storage','retail','office','industrial','hotel_motel','mobile_home_park','other_commercial']::text[], array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus','land']::text[], false, false, 9, '2', 'Seller gave their price (S3 answered); commercial assets (retail, office, industrial, storage, hotel, MHP, other commercial).', 'commercial'),
  ('condition_probe', 'lc-s4-cond-com-es-3', 'condition_probe — Spanish 3 (Stage 4 Condition (Commercial))', 'Spanish', 'Gracias. ¿La propiedad está rentada y en buen estado, o necesita trabajo?', 'Thanks. Is the property leased up and in decent shape, or does it need some work?', 'S4', 'Stage 4 Condition (Commercial)', 'Commercial (Other)', array['self_storage','retail','office','industrial','hotel_motel','mobile_home_park','other_commercial']::text[], array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus','land']::text[], false, false, 9, '3', 'Seller gave their price (S3 answered); commercial assets (retail, office, industrial, storage, hotel, MHP, other commercial).', 'commercial')
) as v(use_case, template_id, template_name, language, template_body, english_translation, stage_code, stage_label,
       property_type_scope, allowed_property_groups, prohibited_property_groups, is_follow_up, minimal_fallback, fallback_rank,
       variant, fires, asset_scope)
where not exists (select 1 from public.sms_templates t where t.template_id = v.template_id);

commit;

-- POSTCHECK (read-only):
--   select use_case, language, property_type_scope, count(*) from public.sms_templates
--    where metadata->>'authored_by' = 'seller_flow_followups_2026_10_10' group by 1, 2, 3 order by 1, 2, 3;
