-- PROPOSED — NOT APPLIED. NATIVE-SCRIPT DRAFTS, EACH ROW NEEDS NATIVE REVIEW + OWNER APPROVAL.
--
-- Round 8 (2026-10-06, owner: "every language gets an automatic response").
-- Today only English and Spanish have active + safe_for_auto_reply reply
-- templates; every other language's catalog rows are romanised drafts with
-- safe_for_auto_reply = false. These are NATIVE-SCRIPT drafts for the core
-- seller flow in the 9 non-Latin / tonal languages:
--   S1 ownership_check, S2 consider_selling, S3 seller_asking_price,
--   S4 ask_condition_clarifier, not_interested (30-day nurture),
--   seller_frustration_apology, price_reality_check.
-- who_is_this (native, lc-ap2-wis2-*) and ownership_connection_clarifier
-- (native, lc-ap2-ocl-*) are already drafted in
-- PROPOSED_20261006090000_seller_autopilot_v2_templates.sql.
--
-- EVERY row is inserted INACTIVE and NOT safe_for_auto_reply, with
-- metadata.needs_native_review = true. Nothing can send from this file.
-- Activate per language after a native speaker signs off, e.g.:
--   update public.sms_templates set is_active = true, safe_for_auto_reply = true, updated_at = now()
--    where template_id like 'lc-native-%-zh-1';
-- Placeholders: {{seller_first_name}}, {{agent_name}}, {{property_address}}
-- (S1 only), the same as the English rows. Idempotent insert by template_id.

begin;
set local lock_timeout = '5s';

insert into public.sms_templates (
  use_case, template_id, template_name, language, agent_persona, template_body,
  english_translation, variables, is_active, safe_for_auto_reply, reply_mode,
  identity_contact_mode, property_type_scope, stage_code, stage_label,
  is_first_touch, is_follow_up, fallback_rank, quarantine_state, metadata
)
select v.use_case, v.template_id, v.template_name, v.language, 'Alex', v.template_body,
       v.english_translation, '{}'::jsonb, false, false,
       case when v.is_first_touch then 'manual' else 'auto_reply' end,
       'neutral', 'Any Residential', v.stage_code, v.stage_label,
       v.is_first_touch, false, 1, 'active',
       jsonb_build_object(
         'authored_by', 'reply_quality_round8_2026_10_06',
         'approval_status', 'proposed_pending_native_review',
         'needs_native_review', true,
         'script', 'native'
       )
from (values
  ('ownership_check', 'lc-native-own-zh-1', 'ownership_check — Mandarin (native script, round 8)', 'Mandarin', '{{seller_first_name}}您好，我是{{agent_name}}。请问您还是{{property_address}}的业主吗？', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-zh-1', 'consider_selling — Mandarin (native script, round 8)', 'Mandarin', '谢谢您的确认。您会考虑我们为这处房产提出的报价吗？', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-zh-1', 'seller_asking_price — Mandarin (native script, round 8)', 'Mandarin', '明白了。您心目中这处房产的价格大概是多少？', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-zh-1', 'ask_condition_clarifier — Mandarin (native script, round 8)', 'Mandarin', '谢谢。能再多介绍一下房子的状况吗？比如屋顶、空调暖气或地基有没有大问题？', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-zh-1', 'not_interested — Mandarin (native script, round 8)', 'Mandarin', '明白，我不再打扰。如果以后情况有变，需要我过一段时间再联系您吗？', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-zh-1', 'seller_frustration_apology — Mandarin (native script, round 8)', 'Mandarin', '抱歉，我记下了。谢谢您告诉我。', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-zh-1', 'price_reality_check — Mandarin (native script, round 8)', 'Mandarin', '哈，那就好了！说实话，如果价格合理，您会考虑出售吗？', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-vi-1', 'ownership_check — Vietnamese (native script, round 8)', 'Vietnamese', 'Chào {{seller_first_name}}, tôi là {{agent_name}}. Anh/chị vẫn là chủ của {{property_address}} phải không?', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-vi-1', 'consider_selling — Vietnamese (native script, round 8)', 'Vietnamese', 'Cảm ơn anh/chị đã xác nhận. Anh/chị có cân nhắc một đề nghị mua cho bất động sản này không?', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-vi-1', 'seller_asking_price — Vietnamese (native script, round 8)', 'Vietnamese', 'Tôi hiểu rồi. Anh/chị nghĩ giá bao nhiêu cho bất động sản này?', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-vi-1', 'ask_condition_clarifier — Vietnamese (native script, round 8)', 'Vietnamese', 'Cảm ơn. Anh/chị có thể cho tôi biết thêm về tình trạng nhà không? Có vấn đề lớn nào như mái, điều hòa hay móng không?', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-vi-1', 'not_interested — Vietnamese (native script, round 8)', 'Vietnamese', 'Tôi hiểu, tôi sẽ không làm phiền nữa. Nếu sau này có gì thay đổi, anh/chị có muốn tôi liên lạc lại không?', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-vi-1', 'seller_frustration_apology — Vietnamese (native script, round 8)', 'Vietnamese', 'Xin lỗi về điều đó, tôi đã ghi lại. Cảm ơn anh/chị đã cho tôi biết.', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-vi-1', 'price_reality_check — Vietnamese (native script, round 8)', 'Vietnamese', 'Haha, ước gì được vậy! Nói thật, nếu giá hợp lý thì anh/chị có cân nhắc bán không?', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-ko-1', 'ownership_check — Korean (native script, round 8)', 'Korean', '안녕하세요 {{seller_first_name}}님, {{agent_name}}입니다. 아직 {{property_address}}의 소유주이신가요?', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-ko-1', 'consider_selling — Korean (native script, round 8)', 'Korean', '확인해 주셔서 감사합니다. 이 부동산에 대한 매입 제안을 고려해 보시겠어요?', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-ko-1', 'seller_asking_price — Korean (native script, round 8)', 'Korean', '알겠습니다. 이 부동산의 희망 가격은 어느 정도 생각하고 계신가요?', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-ko-1', 'ask_condition_clarifier — Korean (native script, round 8)', 'Korean', '감사합니다. 집 상태에 대해 조금 더 알려주실 수 있을까요? 지붕, 냉난방, 기초 같은 큰 문제가 있나요?', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-ko-1', 'not_interested — Korean (native script, round 8)', 'Korean', '알겠습니다. 더 이상 연락드리지 않을게요. 혹시 나중에 상황이 바뀌면 다시 연락드려도 될까요?', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-ko-1', 'seller_frustration_apology — Korean (native script, round 8)', 'Korean', '죄송합니다. 기록해 두겠습니다. 알려주셔서 감사합니다.', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-ko-1', 'price_reality_check — Korean (native script, round 8)', 'Korean', '하하, 그러면 좋겠네요! 현실적으로 가격이 맞으면 매각을 고려해 보시겠어요?', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-ja-1', 'ownership_check — Japanese (native script, round 8)', 'Japanese', '{{seller_first_name}}様、{{agent_name}}と申します。現在も{{property_address}}の所有者でいらっしゃいますか？', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-ja-1', 'consider_selling — Japanese (native script, round 8)', 'Japanese', 'ご確認ありがとうございます。この物件について買取のご提案をご検討いただけますか？', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-ja-1', 'seller_asking_price — Japanese (native script, round 8)', 'Japanese', '承知しました。この物件のご希望価格はどのくらいでしょうか？', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-ja-1', 'ask_condition_clarifier — Japanese (native script, round 8)', 'Japanese', 'ありがとうございます。物件の状態についてもう少し教えていただけますか？屋根、空調、基礎などに大きな問題はありますか？', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-ja-1', 'not_interested — Japanese (native script, round 8)', 'Japanese', '承知しました。これ以上ご連絡はいたしません。もし状況が変わりましたら、また改めてご連絡してもよろしいですか？', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-ja-1', 'seller_frustration_apology — Japanese (native script, round 8)', 'Japanese', '申し訳ありません。記録しておきます。教えていただきありがとうございます。', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-ja-1', 'price_reality_check — Japanese (native script, round 8)', 'Japanese', 'はは、それなら嬉しいですね！現実的に、価格が合えば売却をご検討いただけますか？', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-ar-1', 'ownership_check — Arabic (native script, round 8)', 'Arabic', 'مرحبا {{seller_first_name}}، معك {{agent_name}}. هل ما زلت مالك {{property_address}}؟', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-ar-1', 'consider_selling — Arabic (native script, round 8)', 'Arabic', 'شكراً على التأكيد. هل تفكر في عرض شراء لهذا العقار؟', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-ar-1', 'seller_asking_price — Arabic (native script, round 8)', 'Arabic', 'فهمت. ما السعر الذي تفكر فيه لهذا العقار؟', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-ar-1', 'ask_condition_clarifier — Arabic (native script, round 8)', 'Arabic', 'شكراً. هل يمكنك أن تخبرني المزيد عن حالة العقار؟ هل هناك مشاكل كبيرة مثل السقف أو التكييف أو الأساس؟', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-ar-1', 'not_interested — Arabic (native script, round 8)', 'Arabic', 'مفهوم، لن أزعجك. إذا تغير شيء لاحقاً، هل تريد أن أتواصل معك مرة أخرى؟', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-ar-1', 'seller_frustration_apology — Arabic (native script, round 8)', 'Arabic', 'آسف على ذلك، سأدوّن الملاحظة. شكراً لإخباري.', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-ar-1', 'price_reality_check — Arabic (native script, round 8)', 'Arabic', 'ها، يا ليت! بواقعية، إذا كان السعر معقولاً، هل تفكر في البيع؟', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-he-1', 'ownership_check — Hebrew (native script, round 8)', 'Hebrew', 'שלום {{seller_first_name}}, כאן {{agent_name}}. האם אתה עדיין הבעלים של {{property_address}}?', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-he-1', 'consider_selling — Hebrew (native script, round 8)', 'Hebrew', 'תודה על האישור. האם תשקול הצעה לרכישת הנכס?', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-he-1', 'seller_asking_price — Hebrew (native script, round 8)', 'Hebrew', 'הבנתי. איזה מחיר יש לך בראש עבור הנכס?', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-he-1', 'ask_condition_clarifier — Hebrew (native script, round 8)', 'Hebrew', 'תודה. תוכל לספר לי קצת יותר על מצב הנכס? יש בעיות גדולות כמו גג, מיזוג או יסודות?', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-he-1', 'not_interested — Hebrew (native script, round 8)', 'Hebrew', 'מובן, לא אטריד יותר. אם משהו ישתנה בהמשך, תרצה שאחזור אליך?', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-he-1', 'seller_frustration_apology — Hebrew (native script, round 8)', 'Hebrew', 'סליחה על זה, רשמתי לי. תודה שעדכנת אותי.', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-he-1', 'price_reality_check — Hebrew (native script, round 8)', 'Hebrew', 'הא, הלוואי! באופן מציאותי, אם המחיר יהיה הגיוני, תשקול למכור?', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-ru-1', 'ownership_check — Russian (native script, round 8)', 'Russian', 'Здравствуйте, {{seller_first_name}}! Это {{agent_name}}. Вы всё ещё владелец {{property_address}}?', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-ru-1', 'consider_selling — Russian (native script, round 8)', 'Russian', 'Спасибо, что подтвердили. Рассмотрели бы вы предложение о покупке этой недвижимости?', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-ru-1', 'seller_asking_price — Russian (native script, round 8)', 'Russian', 'Понял. Какую цену вы бы хотели за эту недвижимость?', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-ru-1', 'ask_condition_clarifier — Russian (native script, round 8)', 'Russian', 'Спасибо. Можете рассказать подробнее о состоянии? Есть ли серьёзные проблемы с крышей, отоплением, кондиционером или фундаментом?', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-ru-1', 'not_interested — Russian (native script, round 8)', 'Russian', 'Понимаю, больше не буду беспокоить. Если что-то изменится, можно мне связаться с вами позже?', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-ru-1', 'seller_frustration_apology — Russian (native script, round 8)', 'Russian', 'Извините за это, я отметил. Спасибо, что сообщили.', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-ru-1', 'price_reality_check — Russian (native script, round 8)', 'Russian', 'Ха, было бы здорово! А если реально: при разумной цене вы бы рассмотрели продажу?', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-el-1', 'ownership_check — Greek (native script, round 8)', 'Greek', 'Γεια σας {{seller_first_name}}, είμαι ο {{agent_name}}. Είστε ακόμα ο ιδιοκτήτης του {{property_address}};', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-el-1', 'consider_selling — Greek (native script, round 8)', 'Greek', 'Ευχαριστώ για την επιβεβαίωση. Θα εξετάζατε μια πρόταση αγοράς για το ακίνητο;', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-el-1', 'seller_asking_price — Greek (native script, round 8)', 'Greek', 'Κατάλαβα. Τι τιμή έχετε στο μυαλό σας για το ακίνητο;', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-el-1', 'ask_condition_clarifier — Greek (native script, round 8)', 'Greek', 'Ευχαριστώ. Μπορείτε να μου πείτε λίγο περισσότερα για την κατάσταση; Υπάρχει κάποιο σοβαρό πρόβλημα, όπως στέγη, κλιματισμός ή θεμέλια;', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-el-1', 'not_interested — Greek (native script, round 8)', 'Greek', 'Κατανοητό, δεν θα σας ενοχλήσω. Αν αλλάξει κάτι, θέλετε να επικοινωνήσω ξανά αργότερα;', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-el-1', 'seller_frustration_apology — Greek (native script, round 8)', 'Greek', 'Συγγνώμη γι'' αυτό, το σημείωσα. Ευχαριστώ που με ενημερώσατε.', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-el-1', 'price_reality_check — Greek (native script, round 8)', 'Greek', 'Χα, μακάρι! Ρεαλιστικά, αν η τιμή ήταν λογική, θα σκεφτόσασταν να πουλήσετε;', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false),
  ('ownership_check', 'lc-native-own-hi-1', 'ownership_check — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'नमस्ते {{seller_first_name}}, मैं {{agent_name}} बोल रहा हूँ। क्या आप अभी भी {{property_address}} के मालिक हैं?', 'Hi {{seller_first_name}}, this is {{agent_name}}. Are you still the owner of {{property_address}}?', 'S1', 'Stage 1 Ownership Confirmation', true),
  ('consider_selling', 'lc-native-cs-hi-1', 'consider_selling — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'पुष्टि करने के लिए धन्यवाद। क्या आप इस प्रॉपर्टी के लिए एक प्रस्ताव पर विचार करेंगे?', 'Thanks for confirming. Would you consider a proposal for the property?', 'S2', 'Stage 2 Consider Selling', false),
  ('seller_asking_price', 'lc-native-ap-hi-1', 'seller_asking_price — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'समझ गया। इस प्रॉपर्टी के लिए आपके मन में क्या कीमत है?', 'Got it. What price would you have in mind for the property?', 'S3', 'Stage 3 Seller Asking Price', false),
  ('ask_condition_clarifier', 'lc-native-cond-hi-1', 'ask_condition_clarifier — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'धन्यवाद। क्या आप प्रॉपर्टी की हालत के बारे में थोड़ा और बता सकते हैं? छत, एसी/हीटिंग या नींव जैसी कोई बड़ी समस्या है?', 'Thanks, could you tell me a little more about the condition? Anything major like roof, HVAC, or foundation?', 'S4', 'Stage 4 Condition Clarifier', false),
  ('not_interested', 'lc-native-ni-hi-1', 'not_interested — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'समझ गया, मैं आपको परेशान नहीं करूँगा। अगर आगे कुछ बदलता है, तो क्या मैं बाद में फिर संपर्क करूँ?', 'Understood, I''ll leave it alone. If that ever changes, want me to check back down the road?', 'SP', 'Not Interested (30-day nurture)', false),
  ('seller_frustration_apology', 'lc-native-sfa-hi-1', 'seller_frustration_apology — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'इसके लिए माफ़ी चाहता हूँ, मैंने नोट कर लिया है। बताने के लिए धन्यवाद।', 'Sorry about that, I''ll note it. Thanks for letting me know.', null, 'Frustration Apology', false),
  ('price_reality_check', 'lc-native-prc-hi-1', 'price_reality_check — Indian (Hindi or Other) (native script, round 8)', 'Indian (Hindi or Other)', 'हाहा, काश! सच कहूँ तो, अगर कीमत सही हो, तो क्या आप बेचने पर विचार करेंगे?', 'Ha, I wish! Realistically, if the number made sense, is selling something you''d consider?', null, 'Price Reality Check', false)
) as v(use_case, template_id, template_name, language, template_body, english_translation, stage_code, stage_label, is_first_touch)
where not exists (select 1 from public.sms_templates t where t.template_id = v.template_id);

commit;

-- POSTCHECK (read-only):
--   select language, use_case, template_id, is_active, safe_for_auto_reply
--     from public.sms_templates where template_id like 'lc-native-%' order by language, use_case;
