-- =============================================================================
-- Market Intelligence: INFERRED INVESTOR (owner-based), an extension of the market summary.
-- STATUS: PROPOSED — NOT APPLIED. GENERATED by apps/api/scripts/market-intel-make-inferred-migration.py;
-- do not edit by hand. Pretest: PROPOSED_20261005140000_market_intel_inferred_investor_pretest.sql · Rollback: PROPOSED_20261005140000_market_intel_inferred_investor_rollback.sql
-- Evidence (2026-10-05, read-only, prod): ~/.claude/jobs/c39b0175/tmp/market-intel/INFERRED_INVESTOR_EVIDENCE.txt
--   linked 598,841 of 665,288 sales (90.0%); validation on 36,343 linked sales that record a buyer:
--   precision 87.1%, recall 80.7% for strong+likely (unchanged by tier@2, which only moves 9,537 stack-only
--   individual/trust sales from strong to likely); trust 23.1%, absentee-only 3.3%, no signal 2.7%.
--   tier@2 counts: strong 95,776 · likely 60,997 · trust 1,881 · absentee-only 12,643 · no signal 427,544.
--   Pretest 2026-10-07 09:00Z: link slices took 17-56 s (hash slices, per-row index probes into the
--   516 MB comp_properties heap, ~1 cold random read per sale, and the lateral CASE inlined so the
--   transfer probe ran up to 5x per sale). v2 (this file): contiguous property_id range slices, one
--   ordered range scan per source + merge/hash joins, owner columns from a covering index (pre-step).
--   Measured 2026-10-07 on a 108,831-sale range with the existing indexes: 2.6 s cold; per-row rule
--   vs set-based rule on 5,948 sales: 0 differences (link reason and resident flag).
-- APPLY PLAN (owner approval required; nothing here is applied):
--   0. PRE-STEP: PROPOSED_20261005140000_market_intel_inferred_investor_pre_index.sql (CREATE INDEX CONCURRENTLY; execute_sql, NOT apply_migration,
--      CONCURRENTLY cannot run inside a transaction). The pretest refuses to run without it.
--   1. Outside 05:00-08:59 / 09:15-11:59 UTC: run the _pretest (SET statement_timeout = '300s'); expect
--      'pretest ok' with per-unit ms; it RAISEs 'pretest FAILED' if any unit takes >= 15000 ms.
--      National matrix ≈ the numbers above.
--   2. Apply this file (MCP apply_migration) outside the windows; no cron change (same 75 ticks).
--   3. The fingerprint now includes owner snapshots, so the next nightly tick starts build 2 with 66 units
--      (~ +3 min DB time). Until it is ready, MI keeps serving build 1; inferred metrics read 'unavailable'.
--   4. Verify: select notes->'inferred_investor' from mi_rollup_builds where status = 'ready';
--      GET op=status → inferred_investor.available = true.
--   5. Rollback: the _rollback file (restores the applied functions and view byte for byte).
-- =============================================================================
--
-- WHY. Recorded investor purchases need a deed that names the buyer (~6% of sales). For the
-- other sales the property's CURRENT owner of record is known. Brief §48: an LLC owner alone
-- does not make an investor purchase. So this is a SEPARATE metric, tiered, with its evidence,
-- and validated against the sales that DO name a buyer. It never changes investor_count.
--
-- RULES (mirrored in apps/api/src/lib/domain/market-intelligence/mi-inferred-investor.js):
--   LINK mi_owner_link@1: a sale inherits today's owner only if it is the property's most recent
--     sale, no canonical transfer exists > 45 days after it (closer events are the same
--     transaction's other recordings), and the owner snapshot was observed ≥ 30 days after it
--     (an earlier snapshot can still show the seller).
--   TIER mi_owner_tier@2 (public.mi_owner_tier): strong · likely · trust_estate · absentee_only ·
--     no_signal. Inferred investor = strong + likely.
--   STACK: properties whose owner receives the tax bill at the same normalised mailing address
--     (comp_properties.owner_mailing_identity_key_v1, a keyed hash). NOT proof of one legal owner.
--
-- OBJECTS (all new except the four patched below; service_role only, RLS on, no policies):
--   comp_private.mi_owner_mail_cluster  per build: mailing key → stack id + size (keys stay in comp_private)
--   public.mi_sale_owner_link           per build (current build only, intermediate): one row per sale
--   public.mi_geo_period_inferred       per build: geography × period × asset inferred counts + validation
--   public.mi_owner_stack               per build: stacks ≥ 3 with a linked sale (company label candidate)
--   public.mi_owner_stack_activity      per build: the linked sales in those stacks (for top stacks)
--   public.mi_owner_tier(...)           the tier rule
--   public.mi_infer_run_unit(...)       the 'i:' units
-- PATCHED (exact insertions into the applied text; the rollback restores the originals):
--   mi_rollup_sales_v      + property_id (last column)
--   mi_rollup_units()      + 18 'i:' units (66 units; the nightly window has 75 ticks)
--   mi_rollup_fingerprint()+ owner snapshot (count, max observed) so an owner refresh rebuilds
--   mi_rollup_run_unit()   + one dispatch line for 'i:' units
-- ISOLATION: an 'i:' unit that fails on its RETRY is recorded in notes.inferred_errors and skipped;
--   the core build still completes and the API shows the inferred metric as unavailable for that build.
-- =============================================================================

create table if not exists comp_private.mi_owner_mail_cluster (
  build_id  bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  mail_key  text not null,
  stack_id  integer not null,
  props_n   integer not null,
  corp_n    integer not null,
  oos_n     integer not null,
  trust_n   integer not null,
  primary key (build_id, mail_key)
);
create index if not exists mi_owner_mail_cluster_stack on comp_private.mi_owner_mail_cluster (build_id, stack_id);

create table if not exists public.mi_sale_owner_link (
  build_id    bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  comp_id     text not null,
  sold_on     date not null,
  state       text not null,
  zip         text,
  city_key    text,
  asset       text not null,
  is_mf       boolean not null,
  buyer_known boolean not null,
  is_investor boolean not null,
  buyer       text,              -- the MV's company buyer, kept only for sales inside a stack (label evidence)
  link        text not null check (link in ('linked', 'no_property', 'not_latest_sale', 'later_transfer', 'no_owner_record', 'owner_snapshot_before_sale')),
  tier        text check (tier in ('strong', 'likely', 'trust_estate', 'absentee_only', 'no_signal')),
  corp        boolean,
  trust       boolean,
  oos         boolean,
  resident    boolean,
  stack_n     integer,
  stack_id    integer,
  primary key (build_id, comp_id)
);
create index if not exists mi_sale_owner_link_stack on public.mi_sale_owner_link (build_id, stack_id) where stack_id is not null;

create table if not exists public.mi_geo_period_inferred (
  build_id    bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  geo_level   text not null,
  geo_key     text not null,
  period      text not null,
  asset       text not null,
  sale_count     integer not null,
  linked_count   integer not null,
  strong_n       integer not null,
  likely_n       integer not null,
  trust_n        integer not null,
  absentee_n     integer not null,
  no_signal_n    integer not null,
  stack3_n       integer not null,
  v_strong_known integer not null, v_strong_inv integer not null,
  v_likely_known integer not null, v_likely_inv integer not null,
  v_trust_estate_known integer not null, v_trust_estate_inv integer not null,
  v_absentee_only_known integer not null, v_absentee_only_inv integer not null,
  v_no_signal_known integer not null, v_no_signal_inv integer not null,
  primary key (build_id, geo_level, period, asset, geo_key)
);

create table if not exists public.mi_owner_stack (
  build_id  bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  stack_id  integer not null,
  props_n   integer not null,
  corp_n    integer not null,
  oos_n     integer not null,
  trust_n   integer not null,
  linked_n  integer not null,
  named_n   integer not null,
  label     text,
  label_n   integer not null,
  primary key (build_id, stack_id)
);

create table if not exists public.mi_owner_stack_activity (
  build_id  bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  comp_id   text not null,
  stack_id  integer not null,
  sold_on   date not null,
  zip       text,
  state     text not null,
  city_key  text,
  asset     text not null,
  primary key (build_id, comp_id)
);

do $grants$
declare t text;
begin
  foreach t in array array['public.mi_sale_owner_link', 'public.mi_geo_period_inferred', 'public.mi_owner_stack', 'public.mi_owner_stack_activity', 'comp_private.mi_owner_mail_cluster'] loop
    execute format('alter table %s enable row level security', t);
    execute format('revoke all on %s from public, anon, authenticated', t);
    execute format('grant select on %s to service_role', t);
  end loop;
end
$grants$;

create or replace view public.mi_rollup_sales_v as
select m.comp_id, m.sold_on, m.price, m.ppsf, m.units, m.sqft, m.property_type, m.lat, m.lng, m.buyer,
       upper(btrim(m.state)) as state,
       case when m.zip ~ '^[0-9]{5}$' and m.zip <> '00000' then m.zip end as zip,
       case when nullif(lower(btrim(m.city)), '') is not null then upper(btrim(m.state)) || ':' || lower(btrim(m.city)) end as city_key,
       coalesce(m.is_investor, false) as is_investor,
       m.buyer_kind is not null as buyer_known,
       m.is_cash_purchase,
       coalesce(m.investor_inferred_current_owner, false) as entity,
       (m.source = 'mls') as is_mls,
       coalesce(m.price > 0, false) as priced,
       coalesce(m.price > 0 and coalesce(m.portfolio_size, 1) < 2 and m.is_arms_length is distinct from false
         and coalesce(m.doc_type, '') !~* 'quit ?claim|gift|transfer on death|correction|re-recorded|public action', false) as q,
       a.asset,
       a.asset in ('mf_2_4', 'mf_5_plus', 'mf_unknown') as is_mf,
       m.property_id
  from public.mv_map_market_sales m
  left join public.mi_asset_type_map t on t.raw_type = m.property_type
  cross join lateral (select case
      -- unit count governs the residential lanes (assetTaxonomy unit_count_governs_residential_lane)
      when coalesce(t.base_class, 'unknown') in ('sfr', 'mf_generic', 'mf_5_plus', 'unknown') and m.units > 1
        then case when m.units >= 5 then 'mf_5_plus' else 'mf_2_4' end
      when t.base_class = 'mf_generic' then 'mf_unknown'
      else coalesce(t.base_class, 'unknown') end as asset) a
 where m.sold_on is not null and upper(btrim(m.state)) ~ '^[A-Z]{2}$';
revoke all on public.mi_rollup_sales_v from public, anon, authenticated;
grant select on public.mi_rollup_sales_v to service_role;

-- The tier rule (mi_owner_tier@2). Inputs are non-null: callers coalesce unknown to false / 1.
create or replace function public.mi_owner_tier(p_corp boolean, p_trust boolean, p_oos boolean, p_stack integer, p_resident boolean)
returns text language sql immutable as $$
  select case
    when not p_corp and p_resident then 'no_signal'
    when p_corp and (p_oos or p_stack >= 2) then 'strong'
    when p_stack >= 3 and p_oos then 'strong'
    when p_stack >= 3 then 'likely'
    when p_trust and not p_corp then 'trust_estate'
    when p_corp then 'likely'
    when p_oos and p_stack = 2 then 'likely'
    when p_oos then 'absentee_only'
    else 'no_signal'
  end
$$;

create or replace function public.mi_infer_run_unit(p_build bigint, p_unit text, p_as_of date)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_kind text := split_part(p_unit, ':', 2);
  v_arg text := split_part(p_unit, ':', 3);
  v_key text;
  v_rows bigint := 0;
  v_n bigint;
  v_attempts integer;
  v_keep bigint;
  v_bounds jsonb;
  v_lo text;
  v_hi text;
  v_rng text;
  v_having text := '((grouping(x.asset) = 0 and x.asset in (''sfr'', ''mf_2_4'', ''mf_5_plus'', ''land'', ''commercial''))
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 0 and x.is_mf)
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 1))';
  v_asset text := 'case when grouping(x.asset) = 0 then x.asset when grouping(x.is_mf) = 0 then ''mf'' else ''all'' end';
begin
  select attempts into v_attempts from public.mi_rollup_builds where build_id = p_build;
  -- a failed inferred unit earlier in this build: skip the rest of the inferred chain (cleanup still runs)
  if v_kind <> 'cleanup' and exists (select 1 from public.mi_rollup_builds where build_id = p_build and notes ? 'inferred_errors') then
    return 0;
  end if;
  begin
    if v_kind = 'clusters' then
      insert into comp_private.mi_owner_mail_cluster (build_id, mail_key, stack_id, props_n, corp_n, oos_n, trust_n)
      select p_build, k, (row_number() over (order by n desc, k))::int, n, corp, oos, trust
        from (select cp.owner_mailing_identity_key_v1 as k, count(*)::int as n,
                     count(*) filter (where cp.is_corporate_owner)::int as corp, count(*) filter (where cp.out_of_state_owner)::int as oos,
                     count(*) filter (where cp.is_trust)::int as trust
                from comp_private.comp_properties cp
               where cp.owner_mailing_identity_key_v1 is not null
               group by 1 having count(*) >= 2) c;
      get diagnostics v_rows = row_count;
      analyze comp_private.mi_owner_mail_cluster;
      -- the link slices: 8 contiguous property_id ranges of equal sale count, fixed for this build
      -- (the ranges partition all text values, so every sale lands in exactly one slice)
      update public.mi_rollup_builds b set notes = b.notes || jsonb_build_object('inferred_link_bounds', (
        select to_jsonb(percentile_disc(array[0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875]::float8[]) within group (order by m.property_id))
          from public.mv_map_market_sales m where m.property_id is not null))
       where b.build_id = p_build;

    elsif v_kind = 'link' then
      -- One slice of the properties as a CONTIGUOUS property_id range (bounds fixed per build by
      -- i:clusters in notes.inferred_link_bounds). All sales of a property land in the same slice, so
      -- "most recent sale" is decided over the property's whole history. Set-based: each source is
      -- read once, as an ordered range scan of its property_id index (owner columns from the covering
      -- index comp_properties_mi_owner_cover, the pre-step), then merge/hash joined. Identical to the
      -- per-row rule: "a transfer > 45 days after the sale exists" is "the property's latest transfer
      -- is > 45 days after the sale"; resident is "some contact is a resident likely owner".
      select b.notes -> 'inferred_link_bounds' into v_bounds from public.mi_rollup_builds b where b.build_id = p_build;
      if v_bounds is null or jsonb_array_length(v_bounds) <> 7 then
        raise exception 'mi_infer: no link bounds for build % (i:clusters sets them)', p_build;
      end if;
      v_lo := case when v_arg::int > 0 then v_bounds ->> (v_arg::int - 1) else '' end;  -- '' sorts before every text
      v_hi := case when v_arg::int < 7 then v_bounds ->> v_arg::int end;
      v_rng := '@ >= ' || quote_literal(v_lo) || coalesce(' and @ < ' || quote_literal(v_hi), '');
      execute format($q$
        insert into public.mi_sale_owner_link (build_id, comp_id, sold_on, state, zip, city_key, asset, is_mf, buyer_known, is_investor, buyer,
                                               link, tier, corp, trust, oos, resident, stack_n, stack_id)
        with s as materialized (
          select v.comp_id, v.sold_on, v.state, v.zip, v.city_key, v.asset, v.is_mf, v.buyer_known, v.is_investor, v.buyer, v.property_id,
                 v.sold_on = max(v.sold_on) over (partition by v.property_id) as latest
            from public.mi_rollup_sales_v v
           where %1$s
        ), tx as (
          select t.primary_property_id as property_id, max(t.event_date) as last_event
            from comp_private.comp_canonical_transactions t where %2$s group by 1
        ), pc as (
          select c.property_id, bool_or(c.resident and c.likely_owner) as resident
            from comp_private.comp_property_contacts c where %3$s group by 1
        ), j as (
          select s.*, cp.is_corporate_owner, cp.is_trust, cp.out_of_state_owner, cp.owner_mailing_identity_key_v1 as mail_key,
                 c.props_n, c.stack_id, coalesce(pc.resident, false) as resident_any,
                 case
                   when s.property_id is null then 'no_property'
                   when not s.latest then 'not_latest_sale'
                   when tx.last_event > s.sold_on + 45 then 'later_transfer'
                   when cp.property_id is null or cp.last_observed_at is null then 'no_owner_record'
                   when cp.last_observed_at::date - s.sold_on < 30 then 'owner_snapshot_before_sale'
                   else 'linked' end as link
            from s
            left join comp_private.comp_properties cp on cp.property_id = s.property_id and %4$s
            left join tx on tx.property_id = s.property_id
            left join pc on pc.property_id = s.property_id
            left join comp_private.mi_owner_mail_cluster c on c.build_id = $1 and c.mail_key = cp.owner_mailing_identity_key_v1
        )
        select $1, j.comp_id, j.sold_on, j.state, j.zip, j.city_key, j.asset, j.is_mf, j.buyer_known, j.is_investor,
               case when j.stack_id is not null then j.buyer end,
               j.link,
               case when j.link = 'linked' then public.mi_owner_tier(coalesce(j.is_corporate_owner, false), coalesce(j.is_trust, false),
                 coalesce(j.out_of_state_owner, false), coalesce(j.props_n, 1), j.resident_any) end,
               j.is_corporate_owner, j.is_trust, j.out_of_state_owner, case when j.link = 'linked' then j.resident_any end,
               case when j.mail_key is not null then coalesce(j.props_n, 1) end, j.stack_id
          from j
      $q$, case when v_arg::int = 0 then format('(v.property_id is null or %s)', replace(v_rng, '@', 'v.property_id'))
                else replace(v_rng, '@', 'v.property_id') end,
           replace(v_rng, '@', 't.primary_property_id'), replace(v_rng, '@', 'c.property_id'), replace(v_rng, '@', 'cp.property_id'))
      using p_build;
      get diagnostics v_rows = row_count;

    elsif v_kind = 'stacks' then
      insert into public.mi_owner_stack (build_id, stack_id, props_n, corp_n, oos_n, trust_n, linked_n, named_n, label, label_n)
      select p_build, x.stack_id, c.props_n, c.corp_n, c.oos_n, c.trust_n, x.linked_n, x.named_n, nm.buyer, coalesce(nm.n, 0)
        from (select l.stack_id, count(*)::int as linked_n, count(*) filter (where l.buyer is not null)::int as named_n
                from public.mi_sale_owner_link l
               where l.build_id = p_build and l.link = 'linked' and l.stack_n >= 3
               group by l.stack_id) x
        join comp_private.mi_owner_mail_cluster c on c.build_id = p_build and c.stack_id = x.stack_id
        left join lateral (select l.buyer, count(*)::int as n from public.mi_sale_owner_link l
                            where l.build_id = p_build and l.stack_id = x.stack_id and l.link = 'linked' and l.buyer is not null
                            group by l.buyer order by count(*) desc, l.buyer limit 1) nm on true;
      get diagnostics v_n = row_count; v_rows := v_n;
      insert into public.mi_owner_stack_activity (build_id, comp_id, stack_id, sold_on, zip, state, city_key, asset)
      select p_build, l.comp_id, l.stack_id, l.sold_on, l.zip, l.state, l.city_key, l.asset
        from public.mi_sale_owner_link l
       where l.build_id = p_build and l.link = 'linked' and l.stack_n >= 3;
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;

    elsif v_kind = 'g' then
      v_key := public.mi_rollup_level_key(v_arg);
      if v_key is null then raise exception 'mi_infer: unknown level in unit %', p_unit; end if;
      -- Periods are nested windows ending at the as-of, so each sale is counted once in its
      -- narrowest band and every period sums the bands it contains.
      execute format($q$
        insert into public.mi_geo_period_inferred (build_id, geo_level, geo_key, period, asset, sale_count, linked_count,
          strong_n, likely_n, trust_n, absentee_n, no_signal_n, stack3_n, v_strong_known, v_strong_inv, v_likely_known, v_likely_inv, v_trust_estate_known, v_trust_estate_inv, v_absentee_only_known, v_absentee_only_inv, v_no_signal_known, v_no_signal_inv)
        with x0 as (
          select %1$s as k, s.asset, s.is_mf, s.buyer_known, s.is_investor, s.tier, s.stack_n, (s.link = 'linked') as lk,
                 case when s.sold_on > $3::date - 30 then 1 when s.sold_on > $3::date - 90 then 2 when s.sold_on > $3::date - 182 then 3
                      when s.sold_on > $3::date - 365 then 4 when s.sold_on > $3::date - 1095 then 5 else 6 end as band
            from public.mi_sale_owner_link s
            left join public.mi_zip_geo g on g.build_id = $1 and g.zip = s.zip
           where s.build_id = $1
        ), a as (
          select x.k, %2$s as asset, x.band, count(*)::int as n, count(*) filter (where x.lk)::int as linked,
            count(*) filter (where x.lk and x.tier = 'strong')::int as strong_n, count(*) filter (where x.lk and x.tier = 'likely')::int as likely_n,
            count(*) filter (where x.lk and x.tier = 'trust_estate')::int as trust_n, count(*) filter (where x.lk and x.tier = 'absentee_only')::int as absentee_n,
            count(*) filter (where x.lk and x.tier = 'no_signal')::int as no_signal_n, count(*) filter (where x.lk and x.stack_n >= 3)::int as stack3_n,
            count(*) filter (where x.lk and x.buyer_known and x.tier = 'strong')::int as v_strong_known, count(*) filter (where x.lk and x.buyer_known and x.tier = 'strong' and x.is_investor)::int as v_strong_inv,
            count(*) filter (where x.lk and x.buyer_known and x.tier = 'likely')::int as v_likely_known, count(*) filter (where x.lk and x.buyer_known and x.tier = 'likely' and x.is_investor)::int as v_likely_inv,
            count(*) filter (where x.lk and x.buyer_known and x.tier = 'trust_estate')::int as v_trust_estate_known, count(*) filter (where x.lk and x.buyer_known and x.tier = 'trust_estate' and x.is_investor)::int as v_trust_estate_inv,
            count(*) filter (where x.lk and x.buyer_known and x.tier = 'absentee_only')::int as v_absentee_only_known, count(*) filter (where x.lk and x.buyer_known and x.tier = 'absentee_only' and x.is_investor)::int as v_absentee_only_inv,
            count(*) filter (where x.lk and x.buyer_known and x.tier = 'no_signal')::int as v_no_signal_known, count(*) filter (where x.lk and x.buyer_known and x.tier = 'no_signal' and x.is_investor)::int as v_no_signal_inv
            from x0 x where x.k is not null
           group by grouping sets ((x.k, x.asset, x.band), (x.k, x.band), (x.k, x.is_mf, x.band))
          having %3$s
        )
        select $1, $2, a.k, p.period, a.asset,
           sum(a.n) filter (where a.band <= p.maxband), sum(a.linked) filter (where a.band <= p.maxband),
           sum(a.strong_n) filter (where a.band <= p.maxband), sum(a.likely_n) filter (where a.band <= p.maxband),
           sum(a.trust_n) filter (where a.band <= p.maxband), sum(a.absentee_n) filter (where a.band <= p.maxband),
           sum(a.no_signal_n) filter (where a.band <= p.maxband), sum(a.stack3_n) filter (where a.band <= p.maxband),
           sum(a.v_strong_known) filter (where a.band <= p.maxband), sum(a.v_strong_inv) filter (where a.band <= p.maxband),
           sum(a.v_likely_known) filter (where a.band <= p.maxband), sum(a.v_likely_inv) filter (where a.band <= p.maxband),
           sum(a.v_trust_estate_known) filter (where a.band <= p.maxband), sum(a.v_trust_estate_inv) filter (where a.band <= p.maxband),
           sum(a.v_absentee_only_known) filter (where a.band <= p.maxband), sum(a.v_absentee_only_inv) filter (where a.band <= p.maxband),
           sum(a.v_no_signal_known) filter (where a.band <= p.maxband), sum(a.v_no_signal_inv) filter (where a.band <= p.maxband)
          from a cross join (values ('30d', 1), ('90d', 2), ('6m', 3), ('1y', 4), ('3y', 5), ('all', 6)) as p(period, maxband)
         group by a.k, p.period, a.asset
        having coalesce(sum(a.n) filter (where a.band <= p.maxband), 0) > 0
      $q$, v_key, v_asset, v_having) using p_build, v_arg, p_as_of;
      get diagnostics v_rows = row_count;

    elsif v_kind = 'validate' then
      -- the build's published validation: the national, all-time, all-asset matrix
      update public.mi_rollup_builds b set notes = b.notes || jsonb_build_object('inferred_investor', jsonb_build_object(
        'link_rule', 'mi_owner_link@1', 'tier_rule', 'mi_owner_tier@2',
        'sales', r.sale_count, 'linked', r.linked_count,
        'tiers', jsonb_build_object('strong', r.strong_n, 'likely', r.likely_n, 'trust_estate', r.trust_n, 'absentee_only', r.absentee_n, 'no_signal', r.no_signal_n),
        'matrix', jsonb_build_object(
        'strong', jsonb_build_object('recorded_investor', r.v_strong_inv, 'recorded_other', r.v_strong_known - r.v_strong_inv),
        'likely', jsonb_build_object('recorded_investor', r.v_likely_inv, 'recorded_other', r.v_likely_known - r.v_likely_inv),
        'trust_estate', jsonb_build_object('recorded_investor', r.v_trust_estate_inv, 'recorded_other', r.v_trust_estate_known - r.v_trust_estate_inv),
        'absentee_only', jsonb_build_object('recorded_investor', r.v_absentee_only_inv, 'recorded_other', r.v_absentee_only_known - r.v_absentee_only_inv),
        'no_signal', jsonb_build_object('recorded_investor', r.v_no_signal_inv, 'recorded_other', r.v_no_signal_known - r.v_no_signal_inv)),
        'stacks', (select count(*) from public.mi_owner_stack s where s.build_id = p_build)))
        from public.mi_geo_period_inferred r
       where b.build_id = p_build and r.build_id = p_build and r.geo_level = 'nation' and r.geo_key = 'US' and r.period = 'all' and r.asset = 'all';
      get diagnostics v_rows = row_count;
      if v_rows = 0 then raise exception 'mi_infer: no national row to validate'; end if;

    elsif v_kind = 'cleanup' then
      -- the per-sale link rows and mailing keys are intermediates: keep them for the current build only;
      -- served tables follow the core rule (current + previous ready build).
      delete from public.mi_sale_owner_link where build_id <> p_build;
      get diagnostics v_n = row_count; v_rows := v_n;
      delete from comp_private.mi_owner_mail_cluster where build_id <> p_build;
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;
      select max(build_id) into v_keep from public.mi_rollup_builds where status = 'superseded';
      delete from public.mi_geo_period_inferred where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> p_build and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;
      delete from public.mi_owner_stack where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> p_build and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;
      delete from public.mi_owner_stack_activity where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> p_build and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      get diagnostics v_n = row_count; v_rows := v_rows + v_n;

    else
      raise exception 'mi_infer: unknown unit %', p_unit;
    end if;
    return v_rows;
  exception when query_canceled or others then
    -- first failure: re-raise, the tick records it and retries next tick. On the retry, record
    -- and skip: the inferred chain must never fail the core build.
    if coalesce(v_attempts, 0) = 0 or v_kind = 'cleanup' then raise; end if;
    update public.mi_rollup_builds set notes = notes || jsonb_build_object('inferred_errors', jsonb_build_object(p_unit, left(sqlerrm, 300)))
     where build_id = p_build;
    return 0;
  end;
end
$$;

create or replace function public.mi_rollup_units()
returns text[] language sql immutable as $$
  select array['prepare', 'buyers', 'i:clusters', 'i:link:0', 'i:link:1', 'i:link:2', 'i:link:3', 'i:link:4', 'i:link:5', 'i:link:6', 'i:link:7', 'i:stacks']
    || (select array_agg(format('p:%s:%s', l, p) order by pi, li)
          from unnest(array['1y', '90d', '30d', '6m', '3y', 'all']) with ordinality as pp(p, pi),
               unnest(array['nation', 'state', 'market', 'county', 'city', 'zip']) with ordinality as ll(l, li))
    || array['m:nation', 'm:state', 'm:market', 'm:county', 'm:city', 'm:zip', 'i:g:nation', 'i:g:state', 'i:g:market', 'i:g:county', 'i:g:city', 'i:g:zip', 'i:validate', 'finalize', 'i:cleanup', 'c:period', 'c:month', 'c:aux']
$$;

create or replace function public.mi_rollup_fingerprint()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'rows', s.n, 'as_of', s.last, 'first', s.first, 'price_sum', s.psum::text,
    'membership', (select jsonb_build_array(count(*), max(computed_at)) from public.market_zip_membership),
    'census', (select jsonb_build_array(count(*), max(vintage)) from public.exchange_market_fundamentals_cells),
    'owners', (select jsonb_build_array(count(*), max(last_observed_at)) from comp_private.comp_properties))
  from (select count(*) as n, max(sold_on) as last, min(sold_on) as first, coalesce(sum(price), 0) as psum
          from public.mi_rollup_sales_v) s
$$;

create or replace function public.mi_rollup_run_unit(p_build bigint, p_unit text, p_as_of date)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_kind text := split_part(p_unit, ':', 1);
  v_level text := split_part(p_unit, ':', 2);
  v_period text := split_part(p_unit, ':', 3);
  v_days integer;
  v_key text;
  v_rows bigint := 0;
  v_n bigint;
  -- asset-filter rule shared by period and month units: per-class rows for the operator
  -- filters, the 'mf' roll-up, and 'all'.
  v_having text := '((grouping(x.asset) = 0 and x.asset in (''sfr'', ''mf_2_4'', ''mf_5_plus'', ''land'', ''commercial''))
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 0 and x.is_mf)
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 1))';
  v_asset text := 'case when grouping(x.asset) = 0 then x.asset when grouping(x.is_mf) = 0 then ''mf'' else ''all'' end';
begin
  perform set_config('work_mem', '128MB', true);
  if v_kind = 'i' then return public.mi_infer_run_unit(p_build, p_unit, p_as_of); end if;
  if v_kind = 'prepare' then
    -- ZIP → state / city (sale majority), county (census cell, else parcel majority), market.
    insert into public.mi_zip_geo (build_id, zip, state, city_key, county_key, county_name, county_via, market_key, sales_n, min_lat, max_lat, min_lng, max_lng)
    with zs as (
      -- ONE pass over sales: (zip, state, city) groups with counts and bounds.
      select zip, state, city_key, count(*) as n, min(lat) as min_lat, max(lat) as max_lat, min(lng) as min_lng, max(lng) as max_lng
        from public.mi_rollup_sales_v where zip is not null group by 1, 2, 3
    ), st as (
      select distinct on (zip) zip, state from (select zip, state, sum(n) as n from zs group by 1, 2) z order by zip, n desc, state
    ), ct as (
      select distinct on (zip) zip, city_key from (select zip, city_key, sum(n) as n from zs where city_key is not null group by 1, 2) z order by zip, n desc, city_key
    ), agg as (
      select zip, sum(n)::int as n, min(min_lat) as min_lat, max(max_lat) as max_lat, min(min_lng) as min_lng, max(max_lng) as max_lng from zs group by zip
    ), census as (
      select substr(c.geo_id, 6) as zip, replace(c.county_geo_id, 'county:', '') as county_key, c.county_name
        from public.exchange_market_fundamentals_cells c where c.geo_level = 'zip5' and c.county_geo_id is not null
    ), parcel_raw as (
      -- group the 600K parcels first (a plain hash aggregate); normalise the ~2K groups after
      select cp.zip5::text as zip, cp.state::text as st, cp.county_name as cn, count(*) as n
        from comp_private.comp_properties cp
       where cp.zip5 is not null and cp.county_name is not null and btrim(cp.county_name) <> ''
       group by 1, 2, 3
    ), parcel as (
      select distinct on (zip) zip, county_key, county_name from (
        select zip,
               upper(st) || ':' || regexp_replace(regexp_replace(lower(btrim(cn)), '\s+(county|parish|borough)$', ''), '\s+', ' ', 'g') as county_key,
               initcap(regexp_replace(lower(btrim(cn)), '\s+(county|parish|borough)$', '')) as county_name,
               sum(n) as n
          from parcel_raw group by 1, 2, 3) p
       order by zip, n desc, county_key
    ), mk as (
      select z.zip5 as zip, z.canonical_market_id as market_key
        from public.market_zip_membership z join public.canonical_markets cm on cm.id = z.canonical_market_id and cm.is_active
       where z.status = 'resolved'
    ), zips as (
      select zip from agg union select zip from census union select zip from parcel union select zip from mk
    )
    select p_build, z.zip, st.state, ct.city_key,
           coalesce(c.county_key, p.county_key), coalesce(c.county_name, p.county_name),
           case when c.county_key is not null then 'census' when p.county_key is not null then 'parcel_majority' end,
           mk.market_key, coalesce(agg.n, 0), agg.min_lat, agg.max_lat, agg.min_lng, agg.max_lng
      from zips z
      left join st using (zip) left join ct using (zip) left join agg using (zip)
      left join census c using (zip) left join parcel p using (zip) left join mk using (zip)
     where z.zip ~ '^[0-9]{5}$';
    get diagnostics v_n = row_count; v_rows := v_rows + v_n;

    update public.mi_rollup_builds set notes = notes || jsonb_build_object('unmapped_types',
      coalesce((select jsonb_agg(distinct m.property_type) from public.mv_map_market_sales m
                 where m.property_type is not null and not exists (select 1 from public.mi_asset_type_map t where t.raw_type = m.property_type)), '[]'::jsonb))
     where build_id = p_build;
    return v_rows;
  end if;

  if v_kind = 'buyers' then
    -- the ~12.7K sales with a named company buyer (the MV's partial buyer index)
    insert into public.mi_buyer_activity (build_id, comp_id, sold_on, zip, state, city_key, property_type, units, price, qualified, is_investor, buyer)
    select p_build, s.comp_id, s.sold_on, s.zip, s.state, s.city_key, s.property_type, s.units::float8,
           case when s.price > 0 then s.price::float8 end, s.q, s.is_investor, s.buyer
      from public.mi_rollup_sales_v s where s.buyer is not null;
    get diagnostics v_rows = row_count;

    return v_rows;
  end if;

  v_key := public.mi_rollup_level_key(v_level);
  if v_key is null then raise exception 'mi_rollup: unknown level in unit %', p_unit; end if;

  if v_kind = 'p' then
    v_days := case v_period when '30d' then 30 when '90d' then 90 when '6m' then 182 when '1y' then 365 when '3y' then 1095 when 'all' then null
              else -1 end;
    if v_days = -1 then raise exception 'mi_rollup: unknown period in unit %', p_unit; end if;
    execute format($q$
      insert into public.mi_geo_period_rollup (build_id, geo_level, geo_key, period, asset,
        sale_count, priced_sale_count, qualified_sale_count, mls_count, mf_sale_count, investor_count, buyer_known_count,
        cash_known_count, cash_count, entity_owned_count, latest_sale,
        median_price, median_ppsf, ppsf_n, median_ppu, ppu_n, median_inv_price, inv_price_n, price_deciles,
        n_sfr, n_mf_2_4, n_mf_5_plus, n_mf_unknown, n_land, n_commercial, n_other_res, n_unknown,
        u_2, u_3, u_4, u_5_9, u_10_19, u_20_49, u_50p, u_unrec, s_lt2k, s_2_4k, s_4_8k, s_8_20k, s_20kp, s_unrec)
      select $1, $2, x.k, $3, %2$s,
        count(*) filter (where x.w), count(*) filter (where x.w and x.priced), count(*) filter (where x.w and x.q),
        count(*) filter (where x.w and x.is_mls), count(*) filter (where x.w and x.is_mf), count(*) filter (where x.w and x.is_investor),
        count(*) filter (where x.w and x.buyer_known), count(*) filter (where x.w and x.is_cash_purchase is not null),
        count(*) filter (where x.w and x.is_cash_purchase), count(*) filter (where x.entity), max(x.sold_on) filter (where x.w),
        percentile_cont(0.5) within group (order by x.price) filter (where x.w and x.q),
        percentile_cont(0.5) within group (order by x.ppsf) filter (where x.w and x.q and x.ppsf > 0),
        count(*) filter (where x.w and x.q and x.ppsf > 0),
        percentile_cont(0.5) within group (order by x.price / x.units) filter (where x.w and x.ppu),
        count(*) filter (where x.w and x.ppu),
        percentile_cont(0.5) within group (order by x.price) filter (where x.w and x.q and x.is_investor),
        count(*) filter (where x.w and x.q and x.is_investor),
        percentile_disc(array[0.1, 0.25, 0.5, 0.75, 0.9]) within group (order by x.price) filter (where x.w and x.q),
        count(*) filter (where x.w and x.asset = 'sfr'), count(*) filter (where x.w and x.asset = 'mf_2_4'),
        count(*) filter (where x.w and x.asset = 'mf_5_plus'), count(*) filter (where x.w and x.asset = 'mf_unknown'),
        count(*) filter (where x.w and x.asset = 'land'), count(*) filter (where x.w and x.asset = 'commercial'),
        count(*) filter (where x.w and x.asset = 'other_res'), count(*) filter (where x.w and x.asset = 'unknown'),
        count(*) filter (where x.w and x.is_mf and x.ur = 2), count(*) filter (where x.w and x.is_mf and x.ur = 3),
        count(*) filter (where x.w and x.is_mf and x.ur = 4), count(*) filter (where x.w and x.is_mf and x.ur between 5 and 9),
        count(*) filter (where x.w and x.is_mf and x.ur between 10 and 19), count(*) filter (where x.w and x.is_mf and x.ur between 20 and 49),
        count(*) filter (where x.w and x.is_mf and x.ur >= 50), count(*) filter (where x.w and x.is_mf and (x.ur is null or x.ur < 2)),
        count(*) filter (where x.w and x.is_mf and x.sqft > 0 and x.sqft < 2000), count(*) filter (where x.w and x.is_mf and x.sqft >= 2000 and x.sqft < 4000),
        count(*) filter (where x.w and x.is_mf and x.sqft >= 4000 and x.sqft < 8000), count(*) filter (where x.w and x.is_mf and x.sqft >= 8000 and x.sqft < 20000),
        count(*) filter (where x.w and x.is_mf and x.sqft >= 20000), count(*) filter (where x.w and x.is_mf and (x.sqft is null or x.sqft <= 0))
      from (
        select %1$s as k, s.*, ($5::int is null or s.sold_on > $4::date - $5::int) as w,
               case when s.units > 1 then round(s.units)::int end as ur,
               (s.q and s.asset in ('mf_2_4', 'mf_5_plus') and s.units > 0 and (s.sqft is null or s.sqft <= 0 or s.sqft / s.units >= 350)) as ppu
          from public.mi_rollup_sales_v s
          left join public.mi_zip_geo g on g.build_id = $1 and g.zip = s.zip
      ) x
      where x.k is not null
      group by grouping sets ((x.k, x.asset), (x.k), (x.k, x.is_mf))
      having %3$s and (count(*) filter (where x.w) > 0 or count(*) filter (where x.entity) > 0)
    $q$, v_key, v_asset, v_having) using p_build, v_level, v_period, p_as_of, v_days;
    get diagnostics v_rows = row_count;
    return v_rows;
  end if;

  if v_kind = 'm' then
    execute format($q$
      insert into public.mi_geo_month_rollup (build_id, geo_level, geo_key, asset, month, sales, investor, buyer_known, cash, cash_known,
        price_n, median_price, ppsf_n, median_ppsf)
      select $1, $2, x.k, %2$s, x.mo,
        count(*), count(*) filter (where x.is_investor), count(*) filter (where x.buyer_known),
        count(*) filter (where x.is_cash_purchase), count(*) filter (where x.is_cash_purchase is not null),
        count(*) filter (where x.q), percentile_cont(0.5) within group (order by x.price) filter (where x.q),
        count(*) filter (where x.q and x.ppsf > 0), percentile_cont(0.5) within group (order by x.ppsf) filter (where x.q and x.ppsf > 0)
      from (
        select %1$s as k, date_trunc('month', s.sold_on)::date as mo, s.*
          from public.mi_rollup_sales_v s
          left join public.mi_zip_geo g on g.build_id = $1 and g.zip = s.zip
      ) x
      where x.k is not null
      group by grouping sets ((x.k, x.mo, x.asset), (x.k, x.mo), (x.k, x.mo, x.is_mf))
      having %3$s
    $q$, v_key, v_asset, v_having) using p_build, v_level;
    get diagnostics v_rows = row_count;
    return v_rows;
  end if;

  raise exception 'mi_rollup: unknown unit %', p_unit;
end
$$;

do $fn_grants$
declare f text;
begin
  foreach f in array array['mi_owner_tier(boolean, boolean, boolean, integer, boolean)', 'mi_infer_run_unit(bigint, text, date)',
                           'mi_rollup_units()', 'mi_rollup_fingerprint()', 'mi_rollup_run_unit(bigint, text, date)'] loop
    execute format('revoke all on function public.%s from public, anon, authenticated', f);
    execute format('grant execute on function public.%s to service_role', f);
  end loop;
end
$fn_grants$;

comment on table public.mi_geo_period_inferred is
  'Market Intelligence INFERRED investor (owner-based, mi_owner_link@1 + mi_owner_tier@2): geography x period x asset. Separate from recorded investor purchases (mi_geo_period_rollup.investor_count); never add them.';
