-- PRETEST for PROPOSED_20261004150000_market_intel_geo_rollup.sql. GENERATED by
-- apps/api/scripts/market-intel-make-pretest.py; do not edit by hand.
-- Rollback-only: every change is undone by the RAISE at the end. Expected result:
--   ERROR:  pretest ok: ...      and NO schema change afterwards.
-- Run in a quiet window with:  SET statement_timeout = '120s';  (prepare + three units ≈ 25 s)
-- What it proves: the DDL applies; the first tick creates a build and runs 'prepare'; a period unit,
-- a month unit and the fingerprint run; the asset mapping covers the corpus; ZIP 55411 / 1y / all
-- matches the API's own numbers for the same as-of.
DO $pretest$
DECLARE
  r jsonb;
  b bigint;
  n bigint;
  v record;
BEGIN
  EXECUTE $mig$-- =============================================================================
-- Market Intelligence: the market summary (an analytical projection of raw sales)
-- STATUS: PROPOSED. Owner-approved design (2026-10-04): "raw sales = source of
-- truth; summary table = fast analytical projection; build it off-hours, refresh
-- incrementally/nightly, and make Market Intelligence read that instead."
-- NOT APPLIED. Apply plan, runtimes and evidence: docs/market-intelligence/SUMMARY_APPLY_PLAN.txt
-- Pretest (rollback-only):  PROPOSED_20261004150000_market_intel_geo_rollup_pretest.sql
-- Rollback:                 PROPOSED_20261004150000_market_intel_geo_rollup_rollback.sql
-- Schedule (separate file): PROPOSED_20261004151000_market_intel_rollup_schedule.sql
-- =============================================================================
--
-- WHAT
--   Source of truth stays public.mv_map_market_sales. The summary is a versioned
--   projection written in BUILDS. Readers only ever see the latest build whose
--   status = 'ready', so a build in progress or a failed build is never served.
--   The previous ready build is kept, so going back is one UPDATE.
--     mi_rollup_builds           one row per build: status, cursor, units, fingerprint, timings,
--                                and the freshness the UI shows ("data as of")
--     mi_rollup_sync_state       last tick / skip reason (campaign-graph convention)
--     mi_asset_type_map          raw property_type → base class (parity-tested against JS)
--     mi_zip_geo                 per build: ZIP → state, city, county (+ how), market, sales, bounds
--     mi_geo_period_rollup       per build: geography × period × asset; counts + EXACT medians
--     mi_geo_month_rollup        per build: geography × month × asset; trends, coverage, growth
--     mi_buyer_activity          per build: the ~12.7K sales with a named company buyer
--                                (privacy and lender rules stay in JS: buyer-name-privacy.js /
--                                buyer-identity-rules.js)
--
-- EXACT, NOT APPROXIMATE
--   Every median is percentile_cont(0.5) over the qualified rows of exactly that
--   (geography, period, asset) group, recomputed from raw sales each build. Medians are
--   never averaged or merged from smaller groups. Price deciles use percentile_disc.
--   Windows end at the build's source as-of (max sold_on) and are the same day counts as
--   the API (30/90/182/365/1095 days, all).
--
-- INCREMENTAL / NIGHTLY (campaign-graph conventions)
--   - mi_rollup_tick() does ONE unit per call: an advisory lock, the load guard
--     (> 12 active client backends or a query running > 10 s → skip), a cursor in
--     mi_rollup_builds, and a 30 s statement cap set by the cron command.
--   - Units: prepare · buyers · 36 period units (6 periods × 6 levels, ordered period by period) ·
--     6 month units · finalize · 3 cleanup.
--     Measured ≤ 10 s each, read side, on prod (see the plan doc).
--   - Nightly: a build starts only if the source fingerprint changed (row count, sum of
--     prices, first/last sale, membership, census) or the last build is older than 7 days.
--     Unchanged means one fingerprint scan a night and nothing written.
--   - Cold-cache tolerant: a unit that errors or hits the cap is rolled back alone
--     (sub-transaction), recorded, and retried on the next tick. After 3 failures the
--     build is marked failed; readers keep the previous ready build.
--   - finalize re-checks the fingerprint. If the MV changed mid-build, the build fails
--     and the next tick starts a fresh one; never a mixed build.
--
-- SECURITY: tables, the view and functions are service_role-only (revoked from PUBLIC,
--   anon and authenticated). RLS is enabled with no policies. Company buyer names only
--   (the MV's buyer column); individuals are never stored here.
-- LOCKS / VOLUME: new objects only. A build writes ~120K period rows + ~250K month rows
--   + ~16K ZIP rows + ~12.7K buyer rows (~90 MB with indexes). Two builds are kept.
-- =============================================================================

create table if not exists public.mi_asset_type_map (
  raw_type   text primary key,
  base_class text not null check (base_class in ('sfr', 'mf_generic', 'mf_5_plus', 'land', 'other_res', 'commercial', 'unknown'))
);
-- The 7 raw values in the corpus (audited 2026-10-04). A value not in this table is 'unknown'
-- (the JS resolver's verdict for an unrecognised label) and is listed on the build (notes.unmapped_types).
insert into public.mi_asset_type_map (raw_type, base_class) values
  ('Single Family', 'sfr'),
  ('Vacant Land', 'land'),
  ('Other', 'unknown'),
  ('Multi-Family', 'mf_generic'),
  ('Apartment', 'mf_5_plus'),
  ('Townhouse', 'other_res'),
  ('Mobile Home', 'other_res')
on conflict (raw_type) do nothing;

create table if not exists public.mi_rollup_builds (
  build_id        bigint generated always as identity primary key,
  status          text not null default 'building' check (status in ('building', 'ready', 'superseded', 'failed')),
  fingerprint     jsonb not null,
  source_as_of    date not null,
  source_first    date,
  source_rows     bigint not null,
  units           text[] not null,
  cursor          integer not null default 0,
  attempts        integer not null default 0,
  ticks           integer not null default 0,
  rows_written    bigint not null default 0,
  db_ms           bigint not null default 0,
  last_unit       text,
  last_unit_ms    integer,
  last_error      text,
  notes           jsonb not null default '{}'::jsonb,
  started_at      timestamptz not null default now(),
  ready_at        timestamptz,
  finished_at     timestamptz,
  updated_at      timestamptz not null default now()
);
create unique index if not exists mi_rollup_builds_one_building on public.mi_rollup_builds ((true)) where status = 'building';
create index if not exists mi_rollup_builds_ready on public.mi_rollup_builds (build_id desc) where status = 'ready';

create table if not exists public.mi_rollup_sync_state (
  key               text primary key,
  last_run_at       timestamptz,
  last_checked_at   timestamptz,
  last_result       text,
  last_skip_reason  text,
  last_ms           integer,
  updated_at        timestamptz not null default now()
);
insert into public.mi_rollup_sync_state (key) values ('nightly') on conflict (key) do nothing;

create table if not exists public.mi_zip_geo (
  build_id    bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  zip         text not null,
  state       text,
  city_key    text,
  county_key  text,
  county_name text,
  county_via  text check (county_via in ('census', 'parcel_majority')),
  market_key  text,
  sales_n     integer not null default 0,
  min_lat double precision, max_lat double precision, min_lng double precision, max_lng double precision,
  primary key (build_id, zip)
);

create table if not exists public.mi_geo_period_rollup (
  build_id      bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  geo_level     text not null,
  geo_key       text not null,
  period        text not null,
  asset         text not null,
  sale_count            integer not null,
  priced_sale_count     integer not null,
  qualified_sale_count  integer not null,
  mls_count             integer not null,
  mf_sale_count         integer not null,
  investor_count        integer not null,
  buyer_known_count     integer not null,
  cash_known_count      integer not null,
  cash_count            integer not null,
  entity_owned_count    integer not null,
  latest_sale           date,
  median_price double precision, median_ppsf double precision, ppsf_n integer not null,
  median_ppu double precision, ppu_n integer not null,
  median_inv_price double precision, inv_price_n integer not null,
  price_deciles double precision[],
  n_sfr integer not null, n_mf_2_4 integer not null, n_mf_5_plus integer not null, n_mf_unknown integer not null,
  n_land integer not null, n_commercial integer not null, n_other_res integer not null, n_unknown integer not null,
  u_2 integer not null, u_3 integer not null, u_4 integer not null, u_5_9 integer not null, u_10_19 integer not null,
  u_20_49 integer not null, u_50p integer not null, u_unrec integer not null,
  s_lt2k integer not null, s_2_4k integer not null, s_4_8k integer not null, s_8_20k integer not null, s_20kp integer not null, s_unrec integer not null,
  primary key (build_id, geo_level, period, asset, geo_key)
);

create table if not exists public.mi_geo_month_rollup (
  build_id     bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  geo_level    text not null,
  geo_key      text not null,
  asset        text not null,
  month        date not null,
  sales        integer not null,
  investor     integer not null,
  buyer_known  integer not null,
  cash         integer not null,
  cash_known   integer not null,
  price_n      integer not null,
  median_price double precision,
  ppsf_n       integer not null,
  median_ppsf  double precision,
  primary key (build_id, geo_level, asset, geo_key, month)
);

create table if not exists public.mi_buyer_activity (
  build_id      bigint not null references public.mi_rollup_builds (build_id) on delete cascade,
  comp_id       text not null,
  sold_on       date not null,
  zip           text,
  state         text not null,
  city_key      text,
  property_type text,
  units         double precision,
  price         double precision,
  qualified     boolean not null,
  is_investor   boolean not null,
  buyer         text not null,
  primary key (build_id, comp_id)
);

do $grants$
declare t text;
begin
  foreach t in array array['mi_asset_type_map', 'mi_rollup_builds', 'mi_rollup_sync_state', 'mi_zip_geo', 'mi_geo_period_rollup', 'mi_geo_month_rollup', 'mi_buyer_activity'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from public, anon, authenticated', t);
    execute format('grant select on public.%I to service_role', t);
  end loop;
end
$grants$;

-- One row per usable sale, with the asset class and the qualified-price flag (mi_qualified_price@1,
-- the same predicate as apps/api/.../market-intelligence/mi-loader.js).
create or replace view public.mi_rollup_sales_v as
select m.comp_id, m.sold_on, m.price, m.ppsf, m.units, m.sqft, m.property_type, m.lat, m.lng, m.buyer,
       upper(btrim(m.state)) as state,
       case when m.zip ~ '^[0-9]{5}$' and m.zip <> '00000' then m.zip end as zip,
       case when nullif(lower(btrim(m.city)), '') is not null then upper(btrim(m.state)) || ':' || lower(btrim(m.city)) end as city_key,
       coalesce(m.is_investor, false) as is_investor,
       m.buyer_kind is not null as buyer_known,
       m.is_cash_purchase,
       coalesce(m.investor_inferred_current_owner, false) as entity,
       (m.source = 'mls') as is_mls,
       coalesce(m.price > 0, false) as priced,
       coalesce(m.price > 0 and coalesce(m.portfolio_size, 1) < 2 and m.is_arms_length is distinct from false
         and coalesce(m.doc_type, '') !~* 'quit ?claim|gift|transfer on death|correction|re-recorded|public action', false) as q,
       a.asset,
       a.asset in ('mf_2_4', 'mf_5_plus', 'mf_unknown') as is_mf
  from public.mv_map_market_sales m
  left join public.mi_asset_type_map t on t.raw_type = m.property_type
  cross join lateral (select case
      -- unit count governs the residential lanes (assetTaxonomy unit_count_governs_residential_lane)
      when coalesce(t.base_class, 'unknown') in ('sfr', 'mf_generic', 'mf_5_plus', 'unknown') and m.units > 1
        then case when m.units >= 5 then 'mf_5_plus' else 'mf_2_4' end
      when t.base_class = 'mf_generic' then 'mf_unknown'
      else coalesce(t.base_class, 'unknown') end as asset) a
 where m.sold_on is not null and upper(btrim(m.state)) ~ '^[A-Z]{2}$';
revoke all on public.mi_rollup_sales_v from public, anon, authenticated;
grant select on public.mi_rollup_sales_v to service_role;

create or replace function public.mi_rollup_load_ok()
returns boolean language sql stable security definer set search_path = '' as $$
  select count(*) filter (where a.state = 'active' and a.backend_type = 'client backend') <= 12
     and coalesce(max(extract(epoch from now() - a.query_start)) filter (
           where a.state = 'active' and a.backend_type = 'client backend' and a.pid <> pg_backend_pid()), 0) <= 10
    from pg_catalog.pg_stat_activity a
$$;

-- The source fingerprint: one sequential pass over the MV (~0.5–1 s) plus two small tables.
create or replace function public.mi_rollup_fingerprint()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'rows', s.n, 'as_of', s.last, 'first', s.first, 'price_sum', s.psum::text,
    'membership', (select jsonb_build_array(count(*), max(computed_at)) from public.market_zip_membership),
    'census', (select jsonb_build_array(count(*), max(vintage)) from public.exchange_market_fundamentals_cells))
  from (select count(*) as n, max(sold_on) as last, min(sold_on) as first, coalesce(sum(price), 0) as psum
          from public.mi_rollup_sales_v) s
$$;

create or replace function public.mi_rollup_units()
returns text[] language sql immutable as $$
  select array['prepare', 'buyers']
    || (select array_agg(format('p:%s:%s', l, p) order by pi, li)
          from unnest(array['1y', '90d', '30d', '6m', '3y', 'all']) with ordinality as pp(p, pi),
               unnest(array['nation', 'state', 'market', 'county', 'city', 'zip']) with ordinality as ll(l, li))
    || array['m:nation', 'm:state', 'm:market', 'm:county', 'm:city', 'm:zip', 'finalize', 'c:period', 'c:month', 'c:aux']
$$;

create or replace function public.mi_rollup_level_key(p_level text)
returns text language sql immutable as $$
  select case p_level
    when 'nation' then '''US''::text'
    when 'state'  then 's.state'
    when 'market' then 'g.market_key'
    when 'county' then 'g.county_key'
    when 'city'   then 's.city_key'
    when 'zip'    then 's.zip'
  end
$$;

-- One unit of work. Returns rows written. Raises on bad input.
create or replace function public.mi_rollup_run_unit(p_build bigint, p_unit text, p_as_of date)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_kind text := split_part(p_unit, ':', 1);
  v_level text := split_part(p_unit, ':', 2);
  v_period text := split_part(p_unit, ':', 3);
  v_days integer;
  v_key text;
  v_rows bigint := 0;
  v_n bigint;
  -- asset-filter rule shared by period and month units: per-class rows for the operator
  -- filters, the 'mf' roll-up, and 'all'.
  v_having text := '((grouping(x.asset) = 0 and x.asset in (''sfr'', ''mf_2_4'', ''mf_5_plus'', ''land'', ''commercial''))
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 0 and x.is_mf)
                     or (grouping(x.asset) = 1 and grouping(x.is_mf) = 1))';
  v_asset text := 'case when grouping(x.asset) = 0 then x.asset when grouping(x.is_mf) = 0 then ''mf'' else ''all'' end';
begin
  perform set_config('work_mem', '128MB', true);
  if v_kind = 'prepare' then
    -- ZIP → state / city (sale majority), county (census cell, else parcel majority), market.
    insert into public.mi_zip_geo (build_id, zip, state, city_key, county_key, county_name, county_via, market_key, sales_n, min_lat, max_lat, min_lng, max_lng)
    with zs as (
      -- ONE pass over sales: (zip, state, city) groups with counts and bounds.
      select zip, state, city_key, count(*) as n, min(lat) as min_lat, max(lat) as max_lat, min(lng) as min_lng, max(lng) as max_lng
        from public.mi_rollup_sales_v where zip is not null group by 1, 2, 3
    ), st as (
      select distinct on (zip) zip, state from (select zip, state, sum(n) as n from zs group by 1, 2) z order by zip, n desc, state
    ), ct as (
      select distinct on (zip) zip, city_key from (select zip, city_key, sum(n) as n from zs where city_key is not null group by 1, 2) z order by zip, n desc, city_key
    ), agg as (
      select zip, sum(n)::int as n, min(min_lat) as min_lat, max(max_lat) as max_lat, min(min_lng) as min_lng, max(max_lng) as max_lng from zs group by zip
    ), census as (
      select substr(c.geo_id, 6) as zip, replace(c.county_geo_id, 'county:', '') as county_key, c.county_name
        from public.exchange_market_fundamentals_cells c where c.geo_level = 'zip5' and c.county_geo_id is not null
    ), parcel_raw as (
      -- group the 600K parcels first (a plain hash aggregate); normalise the ~2K groups after
      select cp.zip5::text as zip, cp.state::text as st, cp.county_name as cn, count(*) as n
        from comp_private.comp_properties cp
       where cp.zip5 is not null and cp.county_name is not null and btrim(cp.county_name) <> ''
       group by 1, 2, 3
    ), parcel as (
      select distinct on (zip) zip, county_key, county_name from (
        select zip,
               upper(st) || ':' || regexp_replace(regexp_replace(lower(btrim(cn)), '\s+(county|parish|borough)$', ''), '\s+', ' ', 'g') as county_key,
               initcap(regexp_replace(lower(btrim(cn)), '\s+(county|parish|borough)$', '')) as county_name,
               sum(n) as n
          from parcel_raw group by 1, 2, 3) p
       order by zip, n desc, county_key
    ), mk as (
      select z.zip5 as zip, z.canonical_market_id as market_key
        from public.market_zip_membership z join public.canonical_markets cm on cm.id = z.canonical_market_id and cm.is_active
       where z.status = 'resolved'
    ), zips as (
      select zip from agg union select zip from census union select zip from parcel union select zip from mk
    )
    select p_build, z.zip, st.state, ct.city_key,
           coalesce(c.county_key, p.county_key), coalesce(c.county_name, p.county_name),
           case when c.county_key is not null then 'census' when p.county_key is not null then 'parcel_majority' end,
           mk.market_key, coalesce(agg.n, 0), agg.min_lat, agg.max_lat, agg.min_lng, agg.max_lng
      from zips z
      left join st using (zip) left join ct using (zip) left join agg using (zip)
      left join census c using (zip) left join parcel p using (zip) left join mk using (zip)
     where z.zip ~ '^[0-9]{5}$';
    get diagnostics v_n = row_count; v_rows := v_rows + v_n;

    update public.mi_rollup_builds set notes = notes || jsonb_build_object('unmapped_types',
      coalesce((select jsonb_agg(distinct m.property_type) from public.mv_map_market_sales m
                 where m.property_type is not null and not exists (select 1 from public.mi_asset_type_map t where t.raw_type = m.property_type)), '[]'::jsonb))
     where build_id = p_build;
    return v_rows;
  end if;

  if v_kind = 'buyers' then
    -- the ~12.7K sales with a named company buyer (the MV's partial buyer index)
    insert into public.mi_buyer_activity (build_id, comp_id, sold_on, zip, state, city_key, property_type, units, price, qualified, is_investor, buyer)
    select p_build, s.comp_id, s.sold_on, s.zip, s.state, s.city_key, s.property_type, s.units::float8,
           case when s.price > 0 then s.price::float8 end, s.q, s.is_investor, s.buyer
      from public.mi_rollup_sales_v s where s.buyer is not null;
    get diagnostics v_rows = row_count;

    return v_rows;
  end if;

  v_key := public.mi_rollup_level_key(v_level);
  if v_key is null then raise exception 'mi_rollup: unknown level in unit %', p_unit; end if;

  if v_kind = 'p' then
    v_days := case v_period when '30d' then 30 when '90d' then 90 when '6m' then 182 when '1y' then 365 when '3y' then 1095 when 'all' then null
              else -1 end;
    if v_days = -1 then raise exception 'mi_rollup: unknown period in unit %', p_unit; end if;
    execute format($q$
      insert into public.mi_geo_period_rollup (build_id, geo_level, geo_key, period, asset,
        sale_count, priced_sale_count, qualified_sale_count, mls_count, mf_sale_count, investor_count, buyer_known_count,
        cash_known_count, cash_count, entity_owned_count, latest_sale,
        median_price, median_ppsf, ppsf_n, median_ppu, ppu_n, median_inv_price, inv_price_n, price_deciles,
        n_sfr, n_mf_2_4, n_mf_5_plus, n_mf_unknown, n_land, n_commercial, n_other_res, n_unknown,
        u_2, u_3, u_4, u_5_9, u_10_19, u_20_49, u_50p, u_unrec, s_lt2k, s_2_4k, s_4_8k, s_8_20k, s_20kp, s_unrec)
      select $1, $2, x.k, $3, %2$s,
        count(*) filter (where x.w), count(*) filter (where x.w and x.priced), count(*) filter (where x.w and x.q),
        count(*) filter (where x.w and x.is_mls), count(*) filter (where x.w and x.is_mf), count(*) filter (where x.w and x.is_investor),
        count(*) filter (where x.w and x.buyer_known), count(*) filter (where x.w and x.is_cash_purchase is not null),
        count(*) filter (where x.w and x.is_cash_purchase), count(*) filter (where x.entity), max(x.sold_on) filter (where x.w),
        percentile_cont(0.5) within group (order by x.price) filter (where x.w and x.q),
        percentile_cont(0.5) within group (order by x.ppsf) filter (where x.w and x.q and x.ppsf > 0),
        count(*) filter (where x.w and x.q and x.ppsf > 0),
        percentile_cont(0.5) within group (order by x.price / x.units) filter (where x.w and x.ppu),
        count(*) filter (where x.w and x.ppu),
        percentile_cont(0.5) within group (order by x.price) filter (where x.w and x.q and x.is_investor),
        count(*) filter (where x.w and x.q and x.is_investor),
        percentile_disc(array[0.1, 0.25, 0.5, 0.75, 0.9]) within group (order by x.price) filter (where x.w and x.q),
        count(*) filter (where x.w and x.asset = 'sfr'), count(*) filter (where x.w and x.asset = 'mf_2_4'),
        count(*) filter (where x.w and x.asset = 'mf_5_plus'), count(*) filter (where x.w and x.asset = 'mf_unknown'),
        count(*) filter (where x.w and x.asset = 'land'), count(*) filter (where x.w and x.asset = 'commercial'),
        count(*) filter (where x.w and x.asset = 'other_res'), count(*) filter (where x.w and x.asset = 'unknown'),
        count(*) filter (where x.w and x.is_mf and x.ur = 2), count(*) filter (where x.w and x.is_mf and x.ur = 3),
        count(*) filter (where x.w and x.is_mf and x.ur = 4), count(*) filter (where x.w and x.is_mf and x.ur between 5 and 9),
        count(*) filter (where x.w and x.is_mf and x.ur between 10 and 19), count(*) filter (where x.w and x.is_mf and x.ur between 20 and 49),
        count(*) filter (where x.w and x.is_mf and x.ur >= 50), count(*) filter (where x.w and x.is_mf and (x.ur is null or x.ur < 2)),
        count(*) filter (where x.w and x.is_mf and x.sqft > 0 and x.sqft < 2000), count(*) filter (where x.w and x.is_mf and x.sqft >= 2000 and x.sqft < 4000),
        count(*) filter (where x.w and x.is_mf and x.sqft >= 4000 and x.sqft < 8000), count(*) filter (where x.w and x.is_mf and x.sqft >= 8000 and x.sqft < 20000),
        count(*) filter (where x.w and x.is_mf and x.sqft >= 20000), count(*) filter (where x.w and x.is_mf and (x.sqft is null or x.sqft <= 0))
      from (
        select %1$s as k, s.*, ($5::int is null or s.sold_on > $4::date - $5::int) as w,
               case when s.units > 1 then round(s.units)::int end as ur,
               (s.q and s.asset in ('mf_2_4', 'mf_5_plus') and s.units > 0 and (s.sqft is null or s.sqft <= 0 or s.sqft / s.units >= 350)) as ppu
          from public.mi_rollup_sales_v s
          left join public.mi_zip_geo g on g.build_id = $1 and g.zip = s.zip
      ) x
      where x.k is not null
      group by grouping sets ((x.k, x.asset), (x.k), (x.k, x.is_mf))
      having %3$s and (count(*) filter (where x.w) > 0 or count(*) filter (where x.entity) > 0)
    $q$, v_key, v_asset, v_having) using p_build, v_level, v_period, p_as_of, v_days;
    get diagnostics v_rows = row_count;
    return v_rows;
  end if;

  if v_kind = 'm' then
    execute format($q$
      insert into public.mi_geo_month_rollup (build_id, geo_level, geo_key, asset, month, sales, investor, buyer_known, cash, cash_known,
        price_n, median_price, ppsf_n, median_ppsf)
      select $1, $2, x.k, %2$s, x.mo,
        count(*), count(*) filter (where x.is_investor), count(*) filter (where x.buyer_known),
        count(*) filter (where x.is_cash_purchase), count(*) filter (where x.is_cash_purchase is not null),
        count(*) filter (where x.q), percentile_cont(0.5) within group (order by x.price) filter (where x.q),
        count(*) filter (where x.q and x.ppsf > 0), percentile_cont(0.5) within group (order by x.ppsf) filter (where x.q and x.ppsf > 0)
      from (
        select %1$s as k, date_trunc('month', s.sold_on)::date as mo, s.*
          from public.mi_rollup_sales_v s
          left join public.mi_zip_geo g on g.build_id = $1 and g.zip = s.zip
      ) x
      where x.k is not null
      group by grouping sets ((x.k, x.mo, x.asset), (x.k, x.mo), (x.k, x.mo, x.is_mf))
      having %3$s
    $q$, v_key, v_asset, v_having) using p_build, v_level;
    get diagnostics v_rows = row_count;
    return v_rows;
  end if;

  raise exception 'mi_rollup: unknown unit %', p_unit;
end
$$;

-- THE TICK. One unit per call. Run with SET statement_timeout = '30s'; SET lock_timeout = '2s'.
create or replace function public.mi_rollup_tick(p_force boolean default false)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_started timestamptz := clock_timestamp();
  v_t0 timestamptz;
  b public.mi_rollup_builds%rowtype;
  s public.mi_rollup_sync_state%rowtype;
  v_fp jsonb;
  v_unit text;
  v_rows bigint;
  v_ms integer;
  v_keep bigint;
begin
  if not pg_try_advisory_xact_lock(hashtext('mi_rollup')) then
    update public.mi_rollup_sync_state set last_run_at = now(), last_skip_reason = 'locked', updated_at = now() where key = 'nightly';
    return jsonb_build_object('skipped', 'locked');
  end if;
  if not public.mi_rollup_load_ok() then
    update public.mi_rollup_sync_state set last_run_at = now(), last_skip_reason = 'busy', updated_at = now() where key = 'nightly';
    return jsonb_build_object('skipped', 'busy');
  end if;

  select * into b from public.mi_rollup_builds
   where status = 'building' or (status = 'ready' and cursor < cardinality(units))
   order by build_id desc limit 1 for update;

  if not found then
    select * into s from public.mi_rollup_sync_state where key = 'nightly' for update;
    if not p_force and s.last_result = 'up_to_date' and s.last_checked_at > now() - interval '20 hours' then
      update public.mi_rollup_sync_state set last_run_at = now(), last_skip_reason = 'checked_recently', updated_at = now() where key = 'nightly';
      return jsonb_build_object('skipped', 'checked_recently');
    end if;
    v_fp := public.mi_rollup_fingerprint();
    if not p_force and exists (
         select 1 from public.mi_rollup_builds r
          where r.status = 'ready' and r.fingerprint = v_fp and r.ready_at > now() - interval '7 days'
          order by r.build_id desc limit 1) then
      update public.mi_rollup_sync_state set last_run_at = now(), last_checked_at = now(), last_result = 'up_to_date', last_skip_reason = null,
             last_ms = floor(extract(epoch from clock_timestamp() - v_started) * 1000)::int, updated_at = now() where key = 'nightly';
      return jsonb_build_object('skipped', 'up_to_date');
    end if;
    if (v_fp ->> 'as_of') is null then
      update public.mi_rollup_sync_state set last_run_at = now(), last_skip_reason = 'source_empty', updated_at = now() where key = 'nightly';
      return jsonb_build_object('skipped', 'source_empty');
    end if;
    insert into public.mi_rollup_builds (fingerprint, source_as_of, source_first, source_rows, units)
    values (v_fp, (v_fp ->> 'as_of')::date, (v_fp ->> 'first')::date, (v_fp ->> 'rows')::bigint, public.mi_rollup_units())
    returning * into b;
    update public.mi_rollup_sync_state set last_result = 'building', last_checked_at = now(), updated_at = now() where key = 'nightly';
  end if;

  v_unit := b.units[b.cursor + 1];
  v_t0 := clock_timestamp();

  if v_unit = 'finalize' then
    v_fp := public.mi_rollup_fingerprint();
    if v_fp is distinct from b.fingerprint then
      update public.mi_rollup_builds set status = 'failed', last_error = 'source changed during the build; a fresh build starts next tick',
             finished_at = now(), updated_at = now() where build_id = b.build_id;
      update public.mi_rollup_sync_state set last_run_at = now(), last_result = 'source_changed', last_checked_at = null, updated_at = now() where key = 'nightly';
      return jsonb_build_object('build', b.build_id, 'failed', 'source_changed');
    end if;
    update public.mi_rollup_builds set status = 'superseded', updated_at = now() where status = 'ready' and build_id <> b.build_id;
    update public.mi_rollup_builds set status = 'ready', ready_at = now(), cursor = cursor + 1, ticks = ticks + 1, attempts = 0,
           last_unit = v_unit, last_unit_ms = floor(extract(epoch from clock_timestamp() - v_t0) * 1000)::int, updated_at = now()
     where build_id = b.build_id;
    update public.mi_rollup_sync_state set last_run_at = now(), last_result = 'up_to_date', last_checked_at = now(), last_skip_reason = null, updated_at = now() where key = 'nightly';
    return jsonb_build_object('build', b.build_id, 'ready', true);
  end if;

  if v_unit like 'c:%' then
    -- Keep the current build and the one before it (instant rollback); remove older ones.
    select max(build_id) into v_keep from public.mi_rollup_builds where status = 'superseded';
    if v_unit = 'c:period' then
      delete from public.mi_geo_period_rollup where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> b.build_id and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
    elsif v_unit = 'c:month' then
      delete from public.mi_geo_month_rollup where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> b.build_id and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
    else
      delete from public.mi_zip_geo where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> b.build_id and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      delete from public.mi_buyer_activity where build_id in (select r.build_id from public.mi_rollup_builds r where r.build_id <> b.build_id and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed'));
      delete from public.mi_rollup_builds r where r.build_id <> b.build_id and (r.build_id < coalesce(v_keep, 0) or r.status = 'failed');
    end if;
    get diagnostics v_rows = row_count;
    update public.mi_rollup_builds set cursor = cursor + 1, ticks = ticks + 1, last_unit = v_unit,
           finished_at = case when cursor + 1 >= cardinality(units) then now() else finished_at end, updated_at = now()
     where build_id = b.build_id;
    return jsonb_build_object('build', b.build_id, 'unit', v_unit, 'deleted', v_rows);
  end if;

  begin
    v_rows := public.mi_rollup_run_unit(b.build_id, v_unit, b.source_as_of);
    v_ms := floor(extract(epoch from clock_timestamp() - v_t0) * 1000)::int;
    update public.mi_rollup_builds set cursor = cursor + 1, attempts = 0, ticks = ticks + 1, rows_written = rows_written + v_rows,
           db_ms = db_ms + v_ms, last_unit = v_unit, last_unit_ms = v_ms, last_error = null, updated_at = now()
     where build_id = b.build_id;
  exception when query_canceled or others then
    -- The unit's writes are rolled back with this sub-transaction; the failure is recorded.
    -- query_canceled is trapped on purpose: the tick's 30 s statement cap must leave a record.
    update public.mi_rollup_builds set attempts = attempts + 1, ticks = ticks + 1,
           last_error = left(v_unit || ': ' || sqlerrm, 500),
           status = case when attempts + 1 >= 3 then 'failed' else status end,
           finished_at = case when attempts + 1 >= 3 then now() else finished_at end, updated_at = now()
     where build_id = b.build_id;
    update public.mi_rollup_sync_state set last_run_at = now(), last_skip_reason = 'unit_failed', updated_at = now() where key = 'nightly';
    return jsonb_build_object('build', b.build_id, 'unit', v_unit, 'error', sqlerrm);
  end;
  update public.mi_rollup_sync_state set last_run_at = now(), last_skip_reason = null,
         last_ms = floor(extract(epoch from clock_timestamp() - v_started) * 1000)::int, updated_at = now() where key = 'nightly';
  return jsonb_build_object('build', b.build_id, 'unit', v_unit, 'rows', v_rows, 'ms', v_ms, 'next', b.units[b.cursor + 2]);
end
$$;

-- Ops view of the summary (what the API's status reads).
create or replace function public.mi_rollup_status()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'ready', (select to_jsonb(r) - 'fingerprint' - 'units' from public.mi_rollup_builds r where r.status = 'ready' order by r.build_id desc limit 1),
    'building', (select jsonb_build_object('build_id', r.build_id, 'cursor', r.cursor, 'units', cardinality(r.units), 'next', r.units[r.cursor + 1],
                   'attempts', r.attempts, 'last_error', r.last_error, 'started_at', r.started_at, 'db_ms', r.db_ms)
                   from public.mi_rollup_builds r where r.status = 'building' limit 1),
    'sync', (select to_jsonb(s) from public.mi_rollup_sync_state s where s.key = 'nightly'))
$$;

do $fn_grants$
declare f text;
begin
  foreach f in array array['mi_rollup_load_ok()', 'mi_rollup_fingerprint()', 'mi_rollup_units()', 'mi_rollup_level_key(text)',
                           'mi_rollup_run_unit(bigint, text, date)', 'mi_rollup_tick(boolean)', 'mi_rollup_status()'] loop
    execute format('revoke all on function public.%s from public, anon, authenticated', f);
    execute format('grant execute on function public.%s to service_role', f);
  end loop;
end
$fn_grants$;

comment on table public.mi_geo_period_rollup is
  'Market Intelligence summary (projection of mv_map_market_sales): geography x period x asset, exact medians. Read only the latest build with mi_rollup_builds.status = ready.';
$mig$;

  r := public.mi_rollup_tick(true);                                  -- creates the build + runs 'prepare'
  IF r ->> 'unit' IS DISTINCT FROM 'prepare' OR r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at prepare: %', r; END IF;
  SELECT build_id INTO b FROM public.mi_rollup_builds WHERE status = 'building';
  SELECT count(*) INTO n FROM public.mi_zip_geo WHERE build_id = b;
  IF n < 1000 THEN RAISE EXCEPTION 'pretest FAILED: mi_zip_geo has % rows', n; END IF;

  r := public.mi_rollup_tick();                                      -- buyers
  IF r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at %: %', r ->> 'unit', r; END IF;
  r := public.mi_rollup_tick();                                      -- p:nation:1y
  IF r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at %: %', r ->> 'unit', r; END IF;
  r := public.mi_rollup_tick();                                      -- p:state:1y
  IF r ? 'error' THEN RAISE EXCEPTION 'pretest FAILED at %: %', r ->> 'unit', r; END IF;
  PERFORM public.mi_rollup_run_unit(b, 'p:zip:1y', (SELECT source_as_of FROM public.mi_rollup_builds WHERE build_id = b));
  PERFORM public.mi_rollup_run_unit(b, 'm:state', (SELECT source_as_of FROM public.mi_rollup_builds WHERE build_id = b));

  SELECT sale_count, median_price, investor_count, buyer_known_count, entity_owned_count INTO v
    FROM public.mi_geo_period_rollup WHERE build_id = b AND geo_level = 'zip' AND geo_key = '55411' AND period = '1y' AND asset = 'all';
  SELECT count(*) INTO n FROM public.mi_geo_month_rollup WHERE build_id = b AND geo_level = 'state';
  RAISE EXCEPTION 'pretest ok: build %, 55411/1y/all sales % median % investor % of % buyer-known, entity %; state month rows %; unmapped types %',
    b, v.sale_count, v.median_price, v.investor_count, v.buyer_known_count, v.entity_owned_count, n,
    (SELECT notes -> 'unmapped_types' FROM public.mi_rollup_builds WHERE build_id = b);
END
$pretest$;
