-- PRE-STEP for PROPOSED_20261005140000_market_intel_inferred_investor.sql. GENERATED by apps/api/scripts/market-intel-make-inferred-migration.py.
-- STATUS: PROPOSED — NOT APPLIED. Apply FIRST, before the pretest and the migration.
-- Run as ONE statement through execute_sql (or psql), NOT apply_migration: CREATE INDEX CONCURRENTLY
-- cannot run inside a transaction block. Outside 05:00-08:59 / 09:15-11:59 UTC. Builds without
-- blocking writes (two passes over the 516 MB heap; expected ~1-3 min, ~70 MB on disk).
-- WHY: the i:link slices need six owner columns of the sale's property. Read from the heap that is
-- one cold random 8 kB page per sale (shared_buffers 512 MB < heap 516 MB), which made a slice
-- 17-56 s. This covering index serves them as an ordered index-only range scan (the heap is
-- all-visible; it is static between owner-snapshot loads).
-- If a CONCURRENTLY build fails it leaves an INVALID index: drop it (below) and re-run.
-- ROLLBACK (after the migration's rollback): drop index concurrently if exists comp_private.comp_properties_mi_owner_cover;
create index concurrently if not exists comp_properties_mi_owner_cover
  on comp_private.comp_properties (property_id)
  include (last_observed_at, is_corporate_owner, is_trust, out_of_state_owner, owner_mailing_identity_key_v1);
