-- =============================================================================
-- campaign_target_graph covering index for property-keyed touch/phone reads.
-- STATUS: PROPOSED · OWNER-APPROVED 2026-10-05 for apply at/after 12:00 UTC (7 AM CT) · NOT APPLIED.
-- Pretest:  PROPOSED_20261005160000_ctg_property_touch_covering_index_pretest.sql
-- Rollback: PROPOSED_20261005160000_ctg_property_touch_covering_index_rollback.sql
--
-- APPLY METHOD (exact):
--   CREATE INDEX CONCURRENTLY cannot run inside a transaction block.
--   * Do NOT use MCP apply_migration (it wraps the file in a transaction).
--   * Run the pretest first (read-only).
--   * Then run the ONE statement below by itself with MCP execute_sql (or psql
--     autocommit), after:  SET statement_timeout = '0'; SET lock_timeout = '5s';
--     Expected build time: ~5–20 s (one heap scan of the 527 MB table plus the sort).
--     No write lock is taken. Graph writers (incremental cron */10, Composer
--     builds) keep running.
--   * Verify with the POSTCHECK at the bottom of the pretest file. If
--     indisvalid = false (a cancelled CONCURRENTLY build leaves an INVALID
--     index behind), run the rollback and retry.
--   * Then rename this file to 20261005160000_ctg_property_touch_covering_index.sql
--     and record it as applied.
--
-- WHY: every Map "Property universe" bucket, phone filter, phone count and tile
-- touch flag is keyed on campaign_target_graph.property_id and needs only
-- (never_contacted, canonical_e164). Today each of them seq-scans the 527 MB heap:
--   EXISTS(... never_contacted IS FALSE) over properties:  2,488 ms (Seq Scan 2,416 ms,
--   67,371 buffers read). Bucket previews: contacted 4.8–7.1 s, uncontacted 14–16 s,
--   has_phone 15.8 s. The new index makes these index-only scans.
--
-- SIZE: 169,797 entries × ~44 B (8 B header + ~11 B property_id + ~11 B e164 +
--   1 B bool, MAXALIGN 40 B + 4 B line pointer) / 0.90 fill ≈ 8.3 MB fresh,
--   ~10–14 MB after churn. For comparison, idx_campaign_target_graph_property_id
--   is 9.8 MB. That index becomes redundant (same leading key); drop it in a
--   later, separately approved step.
--
-- VISIBILITY MAP: the daily reconcile (05:00–08:59 UTC) UPDATEs every row. Until
--   autovacuum runs, index-only scans fall back to heap fetches, which are still
--   index-driven and far cheaper than a seq scan.
-- =============================================================================

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ctg_property_touch_phone
  ON public.campaign_target_graph (property_id)
  INCLUDE (canonical_e164, never_contacted);
