-- PROPOSED — NOT APPLIED. REQUIRES OWNER APPROVAL OF THE WORDING BEFORE APPLY.
--
-- Seller Autopilot S1–S4 v2 (owner brief 2026-10-06): 156 sms_templates rows.
--   * 8 NEW use cases × 16 languages: no_price_condition_probe, as_is_comp_anchor,
--     price_anchor_above_max (comps above our max: NO comp language), ownership_connection_clarifier
--     (one-time, after a bare "No" to the ownership question), capital_gains_creative_probe,
--     who_is_this_resume_ownership / _price / _condition.
--   * existing use cases with NO usable row in a language: price_works_confirm_basics (7),
--     price_high_condition_probe (7), who_is_this (14 — the 7 existing non-EN/ES rows are
--     statement-only, {{property_address}}-dependent, manual, and mistranslated).
--
-- SAFE TO APPLY EARLY: every row is INACTIVE (is_active = false) AND
-- safe_for_auto_reply = false. The auto-reply selector reads only
-- is_active AND safe_for_auto_reply rows, and only the SELLER_AUTOPILOT_V2
-- layer (env flag, default OFF) names these use cases. Nothing can send from
-- this migration alone.
--
-- After the owner approves wording (and a native speaker reviews rows flagged
-- metadata.native_review = true), activate per row:
--   update public.sms_templates set is_active = true, safe_for_auto_reply = true, updated_at = now()
--    where template_id in (...approved ids...);
--
-- {{offer_price}} is the only placeholder. It renders ONLY from the
-- authoritative, MAO-capped v2 amount (resolveAuthorizedOfferAmount re-checks
-- the ceiling). Anchor rows are NOT formal offers: each send is first written
-- to negotiation_quotes (PROPOSED_20261006120000) and fails closed without it.
--
-- Idempotent: inserts only template_ids that do not exist yet (sms_templates
-- has no unique constraint on template_id, so ON CONFLICT cannot be used).

begin;
set local lock_timeout = '5s';

insert into public.sms_templates (
  use_case, template_id, template_name, language, agent_persona, template_body,
  english_translation, variables, is_active, safe_for_auto_reply, reply_mode,
  identity_contact_mode, property_type_scope, stage_code, stage_label,
  is_first_touch, is_follow_up, fallback_rank, quarantine_state, metadata
)
select v.use_case, v.template_id, v.template_name, v.language, 'Alex', v.template_body,
       v.english_translation,
       case when v.template_body like '%{{offer_price}}%' then '{"offer_price": "authorized_offer"}'::jsonb else '{}'::jsonb end,
       false, false, 'auto',
       'neutral', 'Residential', v.stage_code, v.stage_label,
       false, false, 1, 'active',
       jsonb_build_object(
         'authored_by', 'seller_autopilot_v2_2026_10_06',
         'approval_status', 'proposed_pending_owner_approval',
         'proposal_kind', v.kind,
         'native_review', v.native_review,
         'flag', 'SELLER_AUTOPILOT_V2'
       )
from (values
  ('no_price_condition_probe', 'lc-ap2-npcp-en-1', 'no_price_condition_probe — English (seller autopilot v2)', 'English', 'No worries, I can run the numbers. What''s the condition of the property right now?', null, 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-es-1', 'no_price_condition_probe — Spanish (seller autopilot v2)', 'Spanish', 'No hay problema, yo puedo sacar los números. ¿En qué condición está la propiedad ahora?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-pt-1', 'no_price_condition_probe — Portuguese (seller autopilot v2)', 'Portuguese', 'Sem problema, eu posso fazer as contas. Em que condição está o imóvel agora?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-fr-1', 'no_price_condition_probe — French (seller autopilot v2)', 'French', 'Pas de souci, je peux faire les calculs. Dans quel état est la propriété en ce moment ?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-de-1', 'no_price_condition_probe — German (seller autopilot v2)', 'German', 'Kein Problem, ich kann die Zahlen durchrechnen. In welchem Zustand ist die Immobilie gerade?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-it-1', 'no_price_condition_probe — Italian (seller autopilot v2)', 'Italian', 'Nessun problema, posso fare io i conti. In che condizioni è l''immobile adesso?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-pl-1', 'no_price_condition_probe — Polish (seller autopilot v2)', 'Polish', 'Nie ma problemu, mogę to policzyć. W jakim stanie jest teraz nieruchomość?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-vi-1', 'no_price_condition_probe — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Không sao, tôi có thể tính toán. Hiện tại tình trạng căn nhà thế nào?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', false),
  ('no_price_condition_probe', 'lc-ap2-npcp-zh-1', 'no_price_condition_probe — Mandarin (seller autopilot v2)', 'Mandarin', '没问题，我可以先算一下。房子现在的状况怎么样？', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-ko-1', 'no_price_condition_probe — Korean (seller autopilot v2)', 'Korean', '괜찮습니다, 제가 계산해 볼게요. 지금 집 상태는 어떤가요?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-ja-1', 'no_price_condition_probe — Japanese (seller autopilot v2)', 'Japanese', '大丈夫です、こちらで計算してみます。物件の今の状態はいかがですか？', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-he-1', 'no_price_condition_probe — Hebrew (seller autopilot v2)', 'Hebrew', 'אין בעיה, אני יכול לעשות את החישוב. מה המצב של הנכס כרגע?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-ar-1', 'no_price_condition_probe — Arabic (seller autopilot v2)', 'Arabic', 'لا مشكلة، أستطيع حساب الأرقام. ما هي حالة العقار الآن؟', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-ru-1', 'no_price_condition_probe — Russian (seller autopilot v2)', 'Russian', 'Не проблема, я могу сам всё посчитать. В каком состоянии сейчас недвижимость?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-el-1', 'no_price_condition_probe — Greek (seller autopilot v2)', 'Greek', 'Κανένα πρόβλημα, μπορώ να κάνω τους υπολογισμούς. Σε τι κατάσταση είναι το ακίνητο τώρα;', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('no_price_condition_probe', 'lc-ap2-npcp-hi-1', 'no_price_condition_probe — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'कोई बात नहीं, मैं हिसाब लगा सकता हूँ। अभी प्रॉपर्टी की हालत कैसी है?', 'No worries, I can run the numbers. What''s the condition of the property right now?', 'S4', 'Stage 4 No-Price Condition', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-en-1', 'as_is_comp_anchor — English (seller autopilot v2)', 'English', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', null, 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-es-1', 'as_is_comp_anchor — Spanish (seller autopilot v2)', 'Spanish', 'Gracias por confirmar. Viendo los números, las ventas cercanas en su estado actual andan por {{offer_price}}. ¿Consideraría algo en ese rango?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-pt-1', 'as_is_comp_anchor — Portuguese (seller autopilot v2)', 'Portuguese', 'Obrigado por confirmar. Pelos números, as vendas próximas no estado atual estão em torno de {{offer_price}}. Você consideraria algo nessa faixa?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-fr-1', 'as_is_comp_anchor — French (seller autopilot v2)', 'French', 'Merci de confirmer. D''après les chiffres, les ventes en l''état dans le secteur tournent autour de {{offer_price}}. Envisageriez-vous quelque chose dans cet ordre ?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-de-1', 'as_is_comp_anchor — German (seller autopilot v2)', 'German', 'Danke für die Bestätigung. Laut den Zahlen liegen Verkäufe im aktuellen Zustand in der Nähe bei etwa {{offer_price}}. Wäre etwas in dieser Größenordnung denkbar?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-it-1', 'as_is_comp_anchor — Italian (seller autopilot v2)', 'Italian', 'Grazie della conferma. Guardando i numeri, le vendite vicine nello stato attuale sono intorno a {{offer_price}}. Considererebbe qualcosa in quella fascia?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-pl-1', 'as_is_comp_anchor — Polish (seller autopilot v2)', 'Polish', 'Dzięki za potwierdzenie. Z liczb wynika, że sprzedaże w obecnym stanie w okolicy są w granicach {{offer_price}}. Czy rozważyłbyś coś w tym przedziale?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-vi-1', 'as_is_comp_anchor — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Cảm ơn đã xác nhận. Theo số liệu, nhà bán nguyên trạng gần đó khoảng {{offer_price}}. Bạn có cân nhắc mức đó không?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', false),
  ('as_is_comp_anchor', 'lc-ap2-acanc-zh-1', 'as_is_comp_anchor — Mandarin (seller autopilot v2)', 'Mandarin', '谢谢确认。从数据看，附近按现状出售的房子大约在{{offer_price}}左右。您会考虑这个范围吗？', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-ko-1', 'as_is_comp_anchor — Korean (seller autopilot v2)', 'Korean', '확인 감사합니다. 수치를 보면 근처에서 현재 상태 그대로 팔린 집들이 {{offer_price}} 정도입니다. 그 정도 선이면 고려해 보시겠어요?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-ja-1', 'as_is_comp_anchor — Japanese (seller autopilot v2)', 'Japanese', 'ご確認ありがとうございます。数字を見ると、近くの現状渡しの売買は{{offer_price}}前後です。そのくらいの金額でご検討いただけますか？', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-he-1', 'as_is_comp_anchor — Hebrew (seller autopilot v2)', 'Hebrew', 'תודה על האישור. לפי המספרים, נכסים במצבם הנוכחי באזור נמכרים בסביבות {{offer_price}}. היית שוקל משהו בטווח הזה?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-ar-1', 'as_is_comp_anchor — Arabic (seller autopilot v2)', 'Arabic', 'شكراً للتأكيد. حسب الأرقام، العقارات القريبة تُباع بحالتها الحالية بحوالي {{offer_price}}. هل تفكر في شيء ضمن هذا النطاق؟', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-ru-1', 'as_is_comp_anchor — Russian (seller autopilot v2)', 'Russian', 'Спасибо, что подтвердили. По цифрам, объекты рядом в текущем состоянии продаются примерно за {{offer_price}}. Рассмотрели бы вы что-то в этом диапазоне?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-el-1', 'as_is_comp_anchor — Greek (seller autopilot v2)', 'Greek', 'Ευχαριστώ για την επιβεβαίωση. Με βάση τα νούμερα, οι πωλήσεις στην περιοχή στην τρέχουσα κατάσταση είναι γύρω στα {{offer_price}}. Θα το σκεφτόσασταν;', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('as_is_comp_anchor', 'lc-ap2-acanc-hi-1', 'as_is_comp_anchor — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'पुष्टि के लिए धन्यवाद। आंकड़ों के हिसाब से, आसपास की प्रॉपर्टी मौजूदा हालत में लगभग {{offer_price}} में बिक रही हैं। क्या आप इस रेंज में कुछ सोचेंगे?', 'Thanks for confirming. Looking at the numbers, as-is sales nearby are going for around {{offer_price}}. Would you consider something in that ballpark?', 'S5', 'Stage 5 As-Is Comp Anchor', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-en-1', 'price_anchor_above_max — English (seller autopilot v2)', 'English', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', null, 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-es-1', 'price_anchor_above_max — Spanish (seller autopilot v2)', 'Spanish', 'Según la propiedad y los números, tendríamos que estar alrededor de {{offer_price}} para que funcione. ¿Consideraría algo en ese rango?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-pt-1', 'price_anchor_above_max — Portuguese (seller autopilot v2)', 'Portuguese', 'Pelo imóvel e pelos números, precisaríamos ficar em torno de {{offer_price}} para dar certo. Você consideraria algo nessa faixa?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-fr-1', 'price_anchor_above_max — French (seller autopilot v2)', 'French', 'D''après la propriété et les chiffres, il faudrait être autour de {{offer_price}} pour que ça fonctionne. Envisageriez-vous quelque chose dans cet ordre ?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-de-1', 'price_anchor_above_max — German (seller autopilot v2)', 'German', 'Nach der Immobilie und den Zahlen müssten wir bei etwa {{offer_price}} liegen, damit es passt. Wäre etwas in dieser Größenordnung denkbar?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-it-1', 'price_anchor_above_max — Italian (seller autopilot v2)', 'Italian', 'In base all''immobile e ai numeri, dovremmo essere intorno a {{offer_price}} per farlo funzionare. Considererebbe qualcosa in quella fascia?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-pl-1', 'price_anchor_above_max — Polish (seller autopilot v2)', 'Polish', 'Biorąc pod uwagę nieruchomość i liczby, musielibyśmy być w okolicach {{offer_price}}, żeby to miało sens. Czy rozważyłbyś coś w tym przedziale?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-vi-1', 'price_anchor_above_max — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Dựa trên căn nhà và các con số, chúng tôi cần ở mức khoảng {{offer_price}} để thực hiện được. Bạn có cân nhắc mức đó không?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', false),
  ('price_anchor_above_max', 'lc-ap2-pama-zh-1', 'price_anchor_above_max — Mandarin (seller autopilot v2)', 'Mandarin', '根据房子的情况和数字，我们需要在{{offer_price}}左右才能做成。您会考虑这个范围吗？', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-ko-1', 'price_anchor_above_max — Korean (seller autopilot v2)', 'Korean', '집 상태와 수치를 보면 저희는 {{offer_price}} 정도여야 진행이 가능합니다. 그 정도 선이면 고려해 보시겠어요?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-ja-1', 'price_anchor_above_max — Japanese (seller autopilot v2)', 'Japanese', '物件と数字から見て、成立させるには{{offer_price}}前後になります。そのくらいの金額でご検討いただけますか？', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-he-1', 'price_anchor_above_max — Hebrew (seller autopilot v2)', 'Hebrew', 'לפי הנכס והמספרים, נצטרך להיות בסביבות {{offer_price}} כדי שזה יעבוד. היית שוקל משהו בטווח הזה?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-ar-1', 'price_anchor_above_max — Arabic (seller autopilot v2)', 'Arabic', 'بناءً على العقار والأرقام، سنحتاج أن نكون في حدود {{offer_price}} لكي ينجح الأمر. هل تفكر في شيء ضمن هذا النطاق؟', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-ru-1', 'price_anchor_above_max — Russian (seller autopilot v2)', 'Russian', 'Исходя из объекта и цифр, нам нужно быть в районе {{offer_price}}, чтобы сделка получилась. Рассмотрели бы вы такой вариант?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-el-1', 'price_anchor_above_max — Greek (seller autopilot v2)', 'Greek', 'Με βάση το ακίνητο και τα νούμερα, θα πρέπει να είμαστε γύρω στα {{offer_price}} για να βγει. Θα το σκεφτόσασταν;', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('price_anchor_above_max', 'lc-ap2-pama-hi-1', 'price_anchor_above_max — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'प्रॉपर्टी और आंकड़ों के हिसाब से, बात बनने के लिए हमें लगभग {{offer_price}} के आसपास रहना होगा। क्या आप इस रेंज में कुछ सोचेंगे?', 'Based on the property and the numbers, we''d need to be around {{offer_price}} to make it work. Would you consider something in that range?', 'S5', 'Stage 5 Anchor (comps above max — no comp claim)', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-en-1', 'ownership_connection_clarifier — English (seller autopilot v2)', 'English', 'Got it. Are you connected to the property, or do I have the wrong number?', null, 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-es-1', 'ownership_connection_clarifier — Spanish (seller autopilot v2)', 'Spanish', 'Entendido. ¿Tiene alguna relación con la propiedad, o tengo el número equivocado?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-pt-1', 'ownership_connection_clarifier — Portuguese (seller autopilot v2)', 'Portuguese', 'Entendi. Você tem alguma ligação com o imóvel, ou estou com o número errado?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-fr-1', 'ownership_connection_clarifier — French (seller autopilot v2)', 'French', 'Compris. Êtes-vous lié à la propriété, ou ai-je le mauvais numéro ?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-de-1', 'ownership_connection_clarifier — German (seller autopilot v2)', 'German', 'Verstanden. Haben Sie einen Bezug zu der Immobilie, oder habe ich die falsche Nummer?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-it-1', 'ownership_connection_clarifier — Italian (seller autopilot v2)', 'Italian', 'Capito. Ha un legame con l''immobile, o ho il numero sbagliato?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-pl-1', 'ownership_connection_clarifier — Polish (seller autopilot v2)', 'Polish', 'Rozumiem. Czy masz jakiś związek z tą nieruchomością, czy mam zły numer?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-vi-1', 'ownership_connection_clarifier — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Tôi hiểu. Bạn có liên quan đến bất động sản này không, hay tôi nhầm số?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', false),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-zh-1', 'ownership_connection_clarifier — Mandarin (seller autopilot v2)', 'Mandarin', '明白了。您和这处房产有关系吗，还是我打错号码了？', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-ko-1', 'ownership_connection_clarifier — Korean (seller autopilot v2)', 'Korean', '알겠습니다. 이 부동산과 관련이 있으신가요, 아니면 제가 번호를 잘못 알고 있나요?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-ja-1', 'ownership_connection_clarifier — Japanese (seller autopilot v2)', 'Japanese', '承知しました。この物件と関係はおありですか、それとも番号違いでしょうか？', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-he-1', 'ownership_connection_clarifier — Hebrew (seller autopilot v2)', 'Hebrew', 'הבנתי. יש לך קשר לנכס, או שיש לי מספר שגוי?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-ar-1', 'ownership_connection_clarifier — Arabic (seller autopilot v2)', 'Arabic', 'فهمت. هل لك علاقة بالعقار، أم أن الرقم خاطئ؟', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-ru-1', 'ownership_connection_clarifier — Russian (seller autopilot v2)', 'Russian', 'Понял. Вы как-то связаны с этой недвижимостью, или у меня неверный номер?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-el-1', 'ownership_connection_clarifier — Greek (seller autopilot v2)', 'Greek', 'Κατάλαβα. Έχετε κάποια σχέση με το ακίνητο ή έχω λάθος αριθμό;', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('ownership_connection_clarifier', 'lc-ap2-ocl-hi-1', 'ownership_connection_clarifier — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'समझ गया। क्या आपका इस प्रॉपर्टी से कोई संबंध है, या मेरे पास गलत नंबर है?', 'Got it. Are you connected to the property, or do I have the wrong number?', 'S1', 'Stage 1 Ownership Connection Clarifier', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-en-1', 'capital_gains_creative_probe — English (seller autopilot v2)', 'English', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', null, 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-es-1', 'capital_gains_creative_probe — Spanish (seller autopilot v2)', 'Spanish', 'Lo entiendo. ¿Estaría abierto a algo como financiamiento del dueño o un arrendamiento con opción a compra? A veces eso ayuda con los impuestos sobre la ganancia.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-pt-1', 'capital_gains_creative_probe — Portuguese (seller autopilot v2)', 'Portuguese', 'Entendo. Você estaria aberto a algo como financiamento pelo proprietário ou aluguel com opção de compra? Às vezes isso ajuda com o imposto sobre ganho de capital.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-fr-1', 'capital_gains_creative_probe — French (seller autopilot v2)', 'French', 'Je comprends. Seriez-vous ouvert à un financement par le vendeur ou une location avec option d''achat ? Cela peut parfois aider pour l''impôt sur la plus-value.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-de-1', 'capital_gains_creative_probe — German (seller autopilot v2)', 'German', 'Verstehe. Wären Sie offen für eine Verkäuferfinanzierung oder Miete mit Kaufoption? Das kann manchmal bei der Steuer auf den Gewinn helfen.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-it-1', 'capital_gains_creative_probe — Italian (seller autopilot v2)', 'Italian', 'Capisco. Sarebbe aperto a un finanziamento da parte del venditore o a un affitto con riscatto? A volte aiuta con le tasse sulla plusvalenza.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-pl-1', 'capital_gains_creative_probe — Polish (seller autopilot v2)', 'Polish', 'Rozumiem. Czy byłbyś otwarty na finansowanie przez sprzedającego albo najem z opcją kupna? Czasem to pomaga z podatkiem od zysku.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-vi-1', 'capital_gains_creative_probe — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Tôi hiểu. Bạn có cân nhắc hình thức người bán cho trả góp hoặc thuê có quyền mua không? Đôi khi cách đó giúp giảm thuế lãi vốn.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', false),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-zh-1', 'capital_gains_creative_probe — Mandarin (seller autopilot v2)', 'Mandarin', '理解。您愿意考虑卖方融资或带购买选择权的租赁吗？有时这样对资本利得税有帮助。', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-ko-1', 'capital_gains_creative_probe — Korean (seller autopilot v2)', 'Korean', '이해합니다. 매도인 금융이나 매입 옵션부 임대 같은 방식도 고려해 보시겠어요? 경우에 따라 양도소득세에 도움이 될 수 있습니다.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-ja-1', 'capital_gains_creative_probe — Japanese (seller autopilot v2)', 'Japanese', 'よく分かります。売主ファイナンスやリースオプションのような形はご検討いただけますか？場合によっては譲渡益の税金に役立ちます。', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-he-1', 'capital_gains_creative_probe — Hebrew (seller autopilot v2)', 'Hebrew', 'מבין. היית פתוח למשהו כמו מימון מצד המוכר או שכירות עם אופציה לרכישה? לפעמים זה עוזר עם מס שבח.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-ar-1', 'capital_gains_creative_probe — Arabic (seller autopilot v2)', 'Arabic', 'أتفهم ذلك. هل أنت منفتح على شيء مثل تمويل البائع أو الإيجار مع خيار الشراء؟ أحياناً يساعد ذلك في ضريبة الأرباح الرأسمالية.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-ru-1', 'capital_gains_creative_probe — Russian (seller autopilot v2)', 'Russian', 'Понимаю. Вы бы рассмотрели рассрочку от продавца или аренду с правом выкупа? Иногда это помогает с налогом на прирост капитала.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-el-1', 'capital_gains_creative_probe — Greek (seller autopilot v2)', 'Greek', 'Καταλαβαίνω. Θα ήσασταν ανοιχτός σε χρηματοδότηση από τον πωλητή ή μίσθωση με δικαίωμα αγοράς; Μερικές φορές βοηθά με τον φόρο υπεραξίας.', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('capital_gains_creative_probe', 'lc-ap2-cgcp-hi-1', 'capital_gains_creative_probe — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'समझ सकता हूँ। क्या आप सेलर फाइनेंसिंग या लीज़ ऑप्शन जैसी व्यवस्था पर विचार करेंगे? कभी-कभी इससे कैपिटल गेन्स टैक्स में मदद मिलती है।', 'Totally understand. Would you be open to something like seller financing or a lease option? That can sometimes help with capital gains.', 'S4C', 'Stage 4C Capital Gains Creative Probe', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-en-1', 'who_is_this_resume_ownership — English (seller autopilot v2)', 'English', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', null, 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-es-1', 'who_is_this_resume_ownership — Spanish (seller autopilot v2)', 'Spanish', 'Soy un inversionista de bienes raíces local. Le escribí por su propiedad. ¿Usted es el dueño?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-pt-1', 'who_is_this_resume_ownership — Portuguese (seller autopilot v2)', 'Portuguese', 'Sou um investidor imobiliário local. Entrei em contato sobre o seu imóvel. Você é o proprietário?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-fr-1', 'who_is_this_resume_ownership — French (seller autopilot v2)', 'French', 'Je suis un investisseur immobilier local. Je vous ai contacté au sujet de votre propriété. Êtes-vous le propriétaire ?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-de-1', 'who_is_this_resume_ownership — German (seller autopilot v2)', 'German', 'Ich bin ein lokaler Immobilieninvestor. Ich habe mich wegen Ihrer Immobilie gemeldet. Sind Sie der Eigentümer?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-it-1', 'who_is_this_resume_ownership — Italian (seller autopilot v2)', 'Italian', 'Sono un investitore immobiliare della zona. L''ho contattata per il suo immobile. È lei il proprietario?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-pl-1', 'who_is_this_resume_ownership — Polish (seller autopilot v2)', 'Polish', 'Jestem lokalnym inwestorem w nieruchomości. Piszę w sprawie Twojej nieruchomości. Czy jesteś właścicielem?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-vi-1', 'who_is_this_resume_ownership — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Tôi là nhà đầu tư bất động sản ở địa phương. Tôi liên hệ về bất động sản của bạn. Bạn có phải là chủ sở hữu không?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', false),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-zh-1', 'who_is_this_resume_ownership — Mandarin (seller autopilot v2)', 'Mandarin', '我是本地的房地产投资人，联系您是关于您的房产。请问您是业主吗？', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-ko-1', 'who_is_this_resume_ownership — Korean (seller autopilot v2)', 'Korean', '저는 지역 부동산 투자자입니다. 귀하의 부동산 때문에 연락드렸어요. 소유주이신가요?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-ja-1', 'who_is_this_resume_ownership — Japanese (seller autopilot v2)', 'Japanese', '地元の不動産投資家です。ご所有の物件についてご連絡しました。所有者の方でしょうか？', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-he-1', 'who_is_this_resume_ownership — Hebrew (seller autopilot v2)', 'Hebrew', 'אני משקיע נדל״ן מקומי. פניתי בקשר לנכס שלך. אתה הבעלים?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-ar-1', 'who_is_this_resume_ownership — Arabic (seller autopilot v2)', 'Arabic', 'أنا مستثمر عقاري محلي. تواصلت معك بخصوص عقارك. هل أنت المالك؟', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-ru-1', 'who_is_this_resume_ownership — Russian (seller autopilot v2)', 'Russian', 'Я местный инвестор в недвижимость. Пишу насчёт вашей недвижимости. Вы владелец?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-el-1', 'who_is_this_resume_ownership — Greek (seller autopilot v2)', 'Greek', 'Είμαι τοπικός επενδυτής ακινήτων. Επικοινώνησα για το ακίνητό σας. Είστε ο ιδιοκτήτης;', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_ownership', 'lc-ap2-wis1-hi-1', 'who_is_this_resume_ownership — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'मैं एक स्थानीय रियल एस्टेट निवेशक हूँ। मैंने आपकी प्रॉपर्टी के बारे में संपर्क किया था। क्या आप इसके मालिक हैं?', 'I''m a local real estate investor. I reached out about your property. Are you the owner?', 'SP', 'Identity Response (resume S1)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-en-1', 'who_is_this_resume_price — English (seller autopilot v2)', 'English', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', null, 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-es-1', 'who_is_this_resume_price — Spanish (seller autopilot v2)', 'Spanish', 'Soy un inversionista de bienes raíces local y le escribí por su propiedad. ¿Tiene un precio en mente?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-pt-1', 'who_is_this_resume_price — Portuguese (seller autopilot v2)', 'Portuguese', 'Sou um investidor imobiliário local e entrei em contato sobre o seu imóvel. Você tem um preço em mente?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-fr-1', 'who_is_this_resume_price — French (seller autopilot v2)', 'French', 'Je suis un investisseur immobilier local et je vous contacte au sujet de votre propriété. Avez-vous un prix en tête ?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-de-1', 'who_is_this_resume_price — German (seller autopilot v2)', 'German', 'Ich bin ein lokaler Immobilieninvestor und melde mich wegen Ihrer Immobilie. Haben Sie einen Preis im Kopf?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-it-1', 'who_is_this_resume_price — Italian (seller autopilot v2)', 'Italian', 'Sono un investitore immobiliare della zona e la contatto per il suo immobile. Ha un prezzo in mente?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-pl-1', 'who_is_this_resume_price — Polish (seller autopilot v2)', 'Polish', 'Jestem lokalnym inwestorem w nieruchomości i piszę w sprawie Twojej nieruchomości. Masz na myśli jakąś cenę?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-vi-1', 'who_is_this_resume_price — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Tôi là nhà đầu tư bất động sản ở địa phương, liên hệ về bất động sản của bạn. Bạn có giá nào trong đầu không?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', false),
  ('who_is_this_resume_price', 'lc-ap2-wis3-zh-1', 'who_is_this_resume_price — Mandarin (seller autopilot v2)', 'Mandarin', '我是本地的房地产投资人，联系您是关于您的房产。您心里有价位吗？', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-ko-1', 'who_is_this_resume_price — Korean (seller autopilot v2)', 'Korean', '저는 지역 부동산 투자자이고 귀하의 부동산 때문에 연락드렸어요. 생각하시는 가격이 있으신가요?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-ja-1', 'who_is_this_resume_price — Japanese (seller autopilot v2)', 'Japanese', '地元の不動産投資家で、ご所有の物件についてご連絡しました。ご希望の価格はありますか？', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-he-1', 'who_is_this_resume_price — Hebrew (seller autopilot v2)', 'Hebrew', 'אני משקיע נדל״ן מקומי ופניתי בקשר לנכס שלך. יש לך מחיר בראש?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-ar-1', 'who_is_this_resume_price — Arabic (seller autopilot v2)', 'Arabic', 'أنا مستثمر عقاري محلي وتواصلت معك بخصوص عقارك. هل لديك سعر في ذهنك؟', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-ru-1', 'who_is_this_resume_price — Russian (seller autopilot v2)', 'Russian', 'Я местный инвестор в недвижимость и пишу насчёт вашей недвижимости. У вас есть цена на примете?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-el-1', 'who_is_this_resume_price — Greek (seller autopilot v2)', 'Greek', 'Είμαι τοπικός επενδυτής ακινήτων και επικοινωνώ για το ακίνητό σας. Έχετε κάποια τιμή στο μυαλό σας;', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_price', 'lc-ap2-wis3-hi-1', 'who_is_this_resume_price — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'मैं एक स्थानीय रियल एस्टेट निवेशक हूँ और आपकी प्रॉपर्टी के बारे में संपर्क कर रहा हूँ। क्या आपके मन में कोई कीमत है?', 'I''m a local real estate investor reaching out about your property. Do you have a price in mind for it?', 'SP', 'Identity Response (resume S3)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-en-1', 'who_is_this_resume_condition — English (seller autopilot v2)', 'English', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', null, 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-es-1', 'who_is_this_resume_condition — Spanish (seller autopilot v2)', 'Spanish', 'Soy un inversionista de bienes raíces local y le escribí por su propiedad. ¿En qué condición está ahora?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-pt-1', 'who_is_this_resume_condition — Portuguese (seller autopilot v2)', 'Portuguese', 'Sou um investidor imobiliário local e entrei em contato sobre o seu imóvel. Em que condição ele está agora?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-fr-1', 'who_is_this_resume_condition — French (seller autopilot v2)', 'French', 'Je suis un investisseur immobilier local et je vous contacte au sujet de votre propriété. Dans quel état est-elle en ce moment ?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-de-1', 'who_is_this_resume_condition — German (seller autopilot v2)', 'German', 'Ich bin ein lokaler Immobilieninvestor und melde mich wegen Ihrer Immobilie. In welchem Zustand ist sie gerade?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-it-1', 'who_is_this_resume_condition — Italian (seller autopilot v2)', 'Italian', 'Sono un investitore immobiliare della zona e la contatto per il suo immobile. In che condizioni è adesso?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-pl-1', 'who_is_this_resume_condition — Polish (seller autopilot v2)', 'Polish', 'Jestem lokalnym inwestorem w nieruchomości i piszę w sprawie Twojej nieruchomości. W jakim jest teraz stanie?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-vi-1', 'who_is_this_resume_condition — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Tôi là nhà đầu tư bất động sản ở địa phương, liên hệ về bất động sản của bạn. Hiện tại tình trạng của nó thế nào?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', false),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-zh-1', 'who_is_this_resume_condition — Mandarin (seller autopilot v2)', 'Mandarin', '我是本地的房地产投资人，联系您是关于您的房产。房子现在的状况怎么样？', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-ko-1', 'who_is_this_resume_condition — Korean (seller autopilot v2)', 'Korean', '저는 지역 부동산 투자자이고 귀하의 부동산 때문에 연락드렸어요. 지금 집 상태는 어떤가요?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-ja-1', 'who_is_this_resume_condition — Japanese (seller autopilot v2)', 'Japanese', '地元の不動産投資家で、ご所有の物件についてご連絡しました。物件の今の状態はいかがですか？', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-he-1', 'who_is_this_resume_condition — Hebrew (seller autopilot v2)', 'Hebrew', 'אני משקיע נדל״ן מקומי ופניתי בקשר לנכס שלך. מה המצב שלו כרגע?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-ar-1', 'who_is_this_resume_condition — Arabic (seller autopilot v2)', 'Arabic', 'أنا مستثمر عقاري محلي وتواصلت معك بخصوص عقارك. ما هي حالته الآن؟', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-ru-1', 'who_is_this_resume_condition — Russian (seller autopilot v2)', 'Russian', 'Я местный инвестор в недвижимость и пишу насчёт вашей недвижимости. В каком она сейчас состоянии?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-el-1', 'who_is_this_resume_condition — Greek (seller autopilot v2)', 'Greek', 'Είμαι τοπικός επενδυτής ακινήτων και επικοινωνώ για το ακίνητό σας. Σε τι κατάσταση είναι τώρα;', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('who_is_this_resume_condition', 'lc-ap2-wis4-hi-1', 'who_is_this_resume_condition — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'मैं एक स्थानीय रियल एस्टेट निवेशक हूँ और आपकी प्रॉपर्टी के बारे में संपर्क कर रहा हूँ। अभी उसकी हालत कैसी है?', 'I''m a local real estate investor reaching out about your property. What''s the condition of it right now?', 'SP', 'Identity Response (resume S4)', 'new_use_case', true),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-fr-1', 'price_works_confirm_basics — French (seller autopilot v2)', 'French', 'Ce prix devrait nous convenir. Juste pour confirmer, la propriété est-elle vacante ou occupée en ce moment ?', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', false),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-de-1', 'price_works_confirm_basics — German (seller autopilot v2)', 'German', 'Der Preis sollte für uns passen. Nur zur Bestätigung: Steht die Immobilie gerade leer oder ist sie bewohnt?', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', false),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-ru-1', 'price_works_confirm_basics — Russian (seller autopilot v2)', 'Russian', 'Эта цена должна нам подойти. Просто уточню: сейчас объект пустует или в нём кто-то живёт?', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', true),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-ja-1', 'price_works_confirm_basics — Japanese (seller autopilot v2)', 'Japanese', 'その価格なら対応できそうです。念のため、物件は今空き家ですか、それとも誰か住んでいますか？', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', true),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-ar-1', 'price_works_confirm_basics — Arabic (seller autopilot v2)', 'Arabic', 'هذا السعر يناسبنا على الأرجح. فقط للتأكيد، هل العقار شاغر أم مسكون حالياً؟', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', true),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-el-1', 'price_works_confirm_basics — Greek (seller autopilot v2)', 'Greek', 'Αυτή η τιμή μάλλον μας κάνει. Απλώς για επιβεβαίωση, το ακίνητο είναι άδειο ή κατοικείται τώρα;', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', true),
  ('price_works_confirm_basics', 'lc-ap2-pwcb-hi-1', 'price_works_confirm_basics — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'यह कीमत हमारे लिए ठीक रहनी चाहिए। बस पुष्टि के लिए, क्या प्रॉपर्टी अभी खाली है या उसमें कोई रहता है?', 'That price should work for us. Just to confirm, is the property vacant or occupied right now?', 'S4A', 'Stage 4A Confirm Basics', 'missing_language', true),
  ('price_high_condition_probe', 'lc-ap2-phcp-fr-1', 'price_high_condition_probe — French (seller autopilot v2)', 'French', 'Compris. La propriété est-elle rénovée, ou a-t-elle besoin de travaux ?', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', false),
  ('price_high_condition_probe', 'lc-ap2-phcp-de-1', 'price_high_condition_probe — German (seller autopilot v2)', 'German', 'Verstanden. Ist die Immobilie renoviert, oder braucht sie Arbeit?', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', false),
  ('price_high_condition_probe', 'lc-ap2-phcp-ru-1', 'price_high_condition_probe — Russian (seller autopilot v2)', 'Russian', 'Понял. Объект в хорошем состоянии или требует ремонта?', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', true),
  ('price_high_condition_probe', 'lc-ap2-phcp-ja-1', 'price_high_condition_probe — Japanese (seller autopilot v2)', 'Japanese', '承知しました。物件はリフォーム済みですか、それとも手直しが必要ですか？', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', true),
  ('price_high_condition_probe', 'lc-ap2-phcp-ar-1', 'price_high_condition_probe — Arabic (seller autopilot v2)', 'Arabic', 'فهمت. هل العقار مُجدَّد أم يحتاج إلى إصلاحات؟', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', true),
  ('price_high_condition_probe', 'lc-ap2-phcp-el-1', 'price_high_condition_probe — Greek (seller autopilot v2)', 'Greek', 'Κατάλαβα. Το ακίνητο είναι ανακαινισμένο ή χρειάζεται δουλειά;', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', true),
  ('price_high_condition_probe', 'lc-ap2-phcp-hi-1', 'price_high_condition_probe — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'समझ गया। क्या प्रॉपर्टी अपडेटेड है, या उसमें काम की ज़रूरत है?', 'Got it. Is the property updated, or does it need work?', 'S4B', 'Stage 4B Price High Condition Probe', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-fr-1', 'who_is_this — French (seller autopilot v2)', 'French', 'Je suis un investisseur de la région. Je vous ai contacté au sujet de votre propriété. Seriez-vous ouvert à une proposition ?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', false),
  ('who_is_this', 'lc-ap2-wis2-de-1', 'who_is_this — German (seller autopilot v2)', 'German', 'Ich bin ein Investor hier aus der Gegend. Ich habe mich wegen Ihrer Immobilie gemeldet. Wären Sie offen für ein Angebot?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', false),
  ('who_is_this', 'lc-ap2-wis2-ru-1', 'who_is_this — Russian (seller autopilot v2)', 'Russian', 'Я местный инвестор. Я написал насчёт вашей недвижимости. Вы были бы открыты к предложению?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-ja-1', 'who_is_this — Japanese (seller autopilot v2)', 'Japanese', 'この地域の投資家です。ご所有の物件についてご連絡しました。ご提案をお聞きいただけますか？', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-ar-1', 'who_is_this — Arabic (seller autopilot v2)', 'Arabic', 'أنا مستثمر محلي في المنطقة. تواصلت معك بخصوص عقارك. هل أنت منفتح على عرض؟', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-el-1', 'who_is_this — Greek (seller autopilot v2)', 'Greek', 'Είμαι επενδυτής από την περιοχή. Επικοινώνησα για το ακίνητό σας. Θα ήσασταν ανοιχτός σε μια πρόταση;', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-hi-1', 'who_is_this — Indian (Hindi or Other) (seller autopilot v2)', 'Indian (Hindi or Other)', 'मैं इसी इलाके का एक स्थानीय निवेशक हूँ। मैंने आपकी प्रॉपर्टी के बारे में संपर्क किया था। क्या आप किसी प्रस्ताव के लिए तैयार होंगे?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-pt-1', 'who_is_this — Portuguese (seller autopilot v2)', 'Portuguese', 'Sou um investidor da região. Entrei em contato sobre o seu imóvel. Você estaria aberto a uma proposta?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', false),
  ('who_is_this', 'lc-ap2-wis2-it-1', 'who_is_this — Italian (seller autopilot v2)', 'Italian', 'Sono un investitore della zona. L''ho contattata per il suo immobile. Sarebbe aperto a una proposta?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', false),
  ('who_is_this', 'lc-ap2-wis2-pl-1', 'who_is_this — Polish (seller autopilot v2)', 'Polish', 'Jestem inwestorem z okolicy. Piszę w sprawie Twojej nieruchomości. Czy byłbyś otwarty na propozycję?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', false),
  ('who_is_this', 'lc-ap2-wis2-vi-1', 'who_is_this — Vietnamese (seller autopilot v2)', 'Vietnamese', 'Tôi là nhà đầu tư ở khu vực này. Tôi liên hệ về bất động sản của bạn. Bạn có sẵn sàng nghe một đề xuất không?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', false),
  ('who_is_this', 'lc-ap2-wis2-zh-1', 'who_is_this — Mandarin (seller autopilot v2)', 'Mandarin', '我是本地的投资人，联系您是关于您的房产。您愿意听听我们的报价吗？', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-ko-1', 'who_is_this — Korean (seller autopilot v2)', 'Korean', '저는 이 지역 투자자입니다. 귀하의 부동산 때문에 연락드렸어요. 제안을 한번 들어보시겠어요?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true),
  ('who_is_this', 'lc-ap2-wis2-he-1', 'who_is_this — Hebrew (seller autopilot v2)', 'Hebrew', 'אני משקיע מהאזור. פניתי בקשר לנכס שלך. היית פתוח להצעה?', 'I''m a local investor here in the area. I reached out about your property. Would you be open to a proposal on it?', 'SP', 'Identity Response', 'missing_language', true)
) as v(use_case, template_id, template_name, language, template_body, english_translation, stage_code, stage_label, kind, native_review)
where not exists (
  select 1 from public.sms_templates t where t.template_id = v.template_id
);

commit;

-- POSTCHECK (read-only):
--   select use_case, count(*), count(*) filter (where is_active) active, count(*) filter (where safe_for_auto_reply) safe
--     from public.sms_templates where metadata->>'authored_by' = 'seller_autopilot_v2_2026_10_06' group by 1 order by 1;
--   -- expect 156 rows total, 0 active, 0 safe
