-- PRE-STEP 2 for PROPOSED_20261005140000_market_intel_inferred_investor.sql. GENERATED by apps/api/scripts/market-intel-make-inferred-migration.py.
-- STATUS: PROPOSED — NOT APPLIED. Apply after PRE-STEP 1 (_pre_index.sql) and before the pretest.
-- ONE statement through execute_sql (or psql), NOT apply_migration (CONCURRENTLY cannot run in a transaction).
-- Outside 05:00-08:59 / 09:15-11:59 UTC. ~60 MB; expected well under a minute.
-- WHY (EXPLAIN ANALYZE BUFFERS, 2026-10-07 12:15Z, cold): one i:link slice reads its 1/8 of the sales as a
-- bitmap heap scan of mv_map_market_sales, which is NOT ordered by property_id, so 83K sales touch
-- 16,290-19,169 of the MV's ~23K heap pages (80-85% of the slice's reads; slice 0 5.2 s and slice 7 6.8 s
-- read side, vs 1,184 pages for the owner columns via the covering index). Every slice re-reads ~the
-- whole MV; more slices do not help (a 1/12 slice still touches ~92% of the pages). This index serves the
-- columns the link reads through mi_rollup_sales_v as an ordered index-only range scan.
-- Cost to others: REFRESH MATERIALIZED VIEW rebuilds it (a few seconds more per refresh). Index-only needs
-- the MV all-visible: the existing cron vacuum_map_market_sales (10:37 UTC) runs before the nightly ticks.
-- ROLLBACK (after the migration's rollback): drop index concurrently if exists public.mv_map_market_sales_mi_link_cover;
create index concurrently if not exists mv_map_market_sales_mi_link_cover
  on public.mv_map_market_sales (property_id)
  include (comp_id, sold_on, state, zip, city, property_type, units, buyer_kind, is_investor, buyer);
