-- PROPOSED — NOT APPLIED. REQUIRES OWNER APPROVAL OF THE WORDING
-- (tmp/conversation-v3/EN_ES_COPY_REVIEW.md, section "No-response follow-ups").
--
-- NO-RESPONSE FOLLOW-UPS (owner 2026-10-06): 42 sms_templates rows, EN + ES,
-- 7 use cases × 2 languages × 3 variants (A/B with the seller's first name, N without).
--   s2_no_response_fu1 / _fu2 / _nurture       S2 interest question unanswered (+24h / +72h / +30d)
--   offer_no_response_fu1 / _fu2 / _nurture    offer unanswered (+24h / +72h / +30d; nurture quotes no number)
--   offer_no_response_no_number                ambiguous or above-max offer: no number quoted
--
-- SAFE TO APPLY EARLY: every row is INACTIVE and safe_for_auto_reply = false.
-- Only no-response-followup.js names these use cases, and it runs only when
-- system_control.followup_no_response_mode = 'live'. Nothing can send from this file.
--
-- Activate per row after approval:
--   update public.sms_templates set is_active = true, safe_for_auto_reply = true, updated_at = now()
--    where template_id in (...approved ids...);
-- Idempotent: inserts only template_ids that do not exist yet.

begin;
set local lock_timeout = '5s';

insert into public.sms_templates (
  use_case, template_id, template_name, language, agent_persona, template_body,
  english_translation, variables, is_active, safe_for_auto_reply, reply_mode,
  identity_contact_mode, property_type_scope, allowed_property_groups, stage_code, stage_label,
  is_first_touch, is_follow_up, minimal_fallback, fallback_rank, quarantine_state, metadata
)
select v.use_case, v.template_id, v.template_name, v.language, 'Alex', v.template_body,
       v.english_translation, '{}'::jsonb, false, false, 'auto',
       'neutral', 'Any Residential', array['sfr','duplex','triplex','fourplex','small_multifamily','multifamily_5_plus']::text[], v.stage_code, v.stage_label,
       false, true, v.minimal_fallback, v.fallback_rank, 'active',
       jsonb_build_object(
         'authored_by', 'no_response_followup_2026_10_06',
         'approval_status', 'proposed_pending_owner_approval',
         'variant', v.variant,
         'fires', v.fires,
         'gate', 'system_control.followup_no_response_mode'
       )
from (values
  ('s2_no_response_fu1', 'lc-nr-s2fu1-en-a', 's2_no_response_fu1 — English A (no-response follow-up)', 'English', 'Hey {{seller_first_name}}, are you still interested in selling the property?', null, 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'A', '24h after our S2 interest question (templated or typed) with no reply.'),
  ('s2_no_response_fu1', 'lc-nr-s2fu1-en-b', 's2_no_response_fu1 — English B (no-response follow-up)', 'English', 'Hey {{seller_first_name}}, just checking back. Would you be open to an offer on the property?', null, 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'B', '24h after our S2 interest question (templated or typed) with no reply.'),
  ('s2_no_response_fu1', 'lc-nr-s2fu1-en-n', 's2_no_response_fu1 — English N (no-response follow-up)', 'English', 'Hey, are you still interested in selling the property?', null, 'S2F', 'Stage 2 No-Response Follow-Up', true, 9, 'N', '24h after our S2 interest question (templated or typed) with no reply.'),
  ('s2_no_response_fu1', 'lc-nr-s2fu1-es-a', 's2_no_response_fu1 — Spanish A (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, ¿todavía le interesa vender la propiedad?', 'Hey {{seller_first_name}}, are you still interested in selling the property?', 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'A', '24h after our S2 interest question (templated or typed) with no reply.'),
  ('s2_no_response_fu1', 'lc-nr-s2fu1-es-b', 's2_no_response_fu1 — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, solo para darle seguimiento. ¿Estaría abierto a una oferta por la propiedad?', 'Hey {{seller_first_name}}, just checking back. Would you be open to an offer on the property?', 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'B', '24h after our S2 interest question (templated or typed) with no reply.'),
  ('s2_no_response_fu1', 'lc-nr-s2fu1-es-n', 's2_no_response_fu1 — Spanish N (no-response follow-up)', 'Spanish', 'Hola, ¿todavía le interesa vender la propiedad?', 'Hey, are you still interested in selling the property?', 'S2F', 'Stage 2 No-Response Follow-Up', true, 9, 'N', '24h after our S2 interest question (templated or typed) with no reply.'),
  ('s2_no_response_fu2', 'lc-nr-s2fu2-en-a', 's2_no_response_fu2 — English A (no-response follow-up)', 'English', '{{seller_first_name}}, following up one more time. If the price made sense, would you consider selling?', null, 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'A', '72h after FU1 with no reply. Different wording from FU1.'),
  ('s2_no_response_fu2', 'lc-nr-s2fu2-en-b', 's2_no_response_fu2 — English B (no-response follow-up)', 'English', 'Hi {{seller_first_name}}, I''m still interested in the property. Is selling something you''d consider?', null, 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'B', '72h after FU1 with no reply. Different wording from FU1.'),
  ('s2_no_response_fu2', 'lc-nr-s2fu2-en-n', 's2_no_response_fu2 — English N (no-response follow-up)', 'English', 'Following up one more time. If the price made sense, would you consider selling the property?', null, 'S2F', 'Stage 2 No-Response Follow-Up', true, 9, 'N', '72h after FU1 with no reply. Different wording from FU1.'),
  ('s2_no_response_fu2', 'lc-nr-s2fu2-es-a', 's2_no_response_fu2 — Spanish A (no-response follow-up)', 'Spanish', '{{seller_first_name}}, le escribo una vez más. Si el precio tuviera sentido, ¿consideraría vender?', '{{seller_first_name}}, following up one more time. If the price made sense, would you consider selling?', 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'A', '72h after FU1 with no reply. Different wording from FU1.'),
  ('s2_no_response_fu2', 'lc-nr-s2fu2-es-b', 's2_no_response_fu2 — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, sigo interesado en la propiedad. ¿Es algo que consideraría vender?', 'Hi {{seller_first_name}}, I''m still interested in the property. Is selling something you''d consider?', 'S2F', 'Stage 2 No-Response Follow-Up', false, 1, 'B', '72h after FU1 with no reply. Different wording from FU1.'),
  ('s2_no_response_fu2', 'lc-nr-s2fu2-es-n', 's2_no_response_fu2 — Spanish N (no-response follow-up)', 'Spanish', 'Le escribo una vez más. Si el precio tuviera sentido, ¿consideraría vender la propiedad?', 'Following up one more time. If the price made sense, would you consider selling the property?', 'S2F', 'Stage 2 No-Response Follow-Up', true, 9, 'N', '72h after FU1 with no reply. Different wording from FU1.'),
  ('s2_no_response_nurture', 'lc-nr-s2nur-en-a', 's2_no_response_nurture — English A (no-response follow-up)', 'English', 'Hi {{seller_first_name}}, this is {{agent_name}} again. Any chance you''d consider selling the property now?', null, 'S2F', 'Stage 2 No-Response Nurture', false, 1, 'A', '30 days after FU2 with no reply. Last touch of the chain.'),
  ('s2_no_response_nurture', 'lc-nr-s2nur-en-b', 's2_no_response_nurture — English B (no-response follow-up)', 'English', 'Hey {{seller_first_name}}, checking back in. If the timing is better now, would you be open to an offer on the property?', null, 'S2F', 'Stage 2 No-Response Nurture', false, 1, 'B', '30 days after FU2 with no reply. Last touch of the chain.'),
  ('s2_no_response_nurture', 'lc-nr-s2nur-en-n', 's2_no_response_nurture — English N (no-response follow-up)', 'English', 'Checking back in on the property. If the timing is better now, would you be open to an offer?', null, 'S2F', 'Stage 2 No-Response Nurture', true, 9, 'N', '30 days after FU2 with no reply. Last touch of the chain.'),
  ('s2_no_response_nurture', 'lc-nr-s2nur-es-a', 's2_no_response_nurture — Spanish A (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, soy {{agent_name}} otra vez. ¿Consideraría vender la propiedad ahora?', 'Hi {{seller_first_name}}, this is {{agent_name}} again. Any chance you''d consider selling the property now?', 'S2F', 'Stage 2 No-Response Nurture', false, 1, 'A', '30 days after FU2 with no reply. Last touch of the chain.'),
  ('s2_no_response_nurture', 'lc-nr-s2nur-es-b', 's2_no_response_nurture — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, le escribo de nuevo. Si ahora es mejor momento, ¿estaría abierto a una oferta por la propiedad?', 'Hey {{seller_first_name}}, checking back in. If the timing is better now, would you be open to an offer on the property?', 'S2F', 'Stage 2 No-Response Nurture', false, 1, 'B', '30 days after FU2 with no reply. Last touch of the chain.'),
  ('s2_no_response_nurture', 'lc-nr-s2nur-es-n', 's2_no_response_nurture — Spanish N (no-response follow-up)', 'Spanish', 'Le escribo de nuevo sobre la propiedad. Si ahora es mejor momento, ¿estaría abierto a una oferta?', 'Checking back in on the property. If the timing is better now, would you be open to an offer?', 'S2F', 'Stage 2 No-Response Nurture', true, 9, 'N', '30 days after FU2 with no reply. Last touch of the chain.'),
  ('offer_no_response_fu1', 'lc-nr-offu1-en-a', 'offer_no_response_fu1 — English A (no-response follow-up)', 'English', 'Hey {{seller_first_name}}, does {{offer_price}} work for you to move forward, or did you have a different price in mind?', null, 'S5', 'Offer No-Response Follow-Up', false, 1, 'A', '24h after an offer we sent (automated or typed) with no reply. Quotes exactly the number we sent; never above the engine max.'),
  ('offer_no_response_fu1', 'lc-nr-offu1-en-b', 'offer_no_response_fu1 — English B (no-response follow-up)', 'English', 'Hi {{seller_first_name}}, just following up. Would {{offer_price}} work for you, or is there a number you had in mind?', null, 'S5', 'Offer No-Response Follow-Up', false, 1, 'B', '24h after an offer we sent (automated or typed) with no reply. Quotes exactly the number we sent; never above the engine max.'),
  ('offer_no_response_fu1', 'lc-nr-offu1-en-n', 'offer_no_response_fu1 — English N (no-response follow-up)', 'English', 'Hey, does {{offer_price}} work for you to move forward, or did you have a different price in mind?', null, 'S5', 'Offer No-Response Follow-Up', true, 9, 'N', '24h after an offer we sent (automated or typed) with no reply. Quotes exactly the number we sent; never above the engine max.'),
  ('offer_no_response_fu1', 'lc-nr-offu1-es-a', 'offer_no_response_fu1 — Spanish A (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, ¿le funciona {{offer_price}} para seguir adelante, o tenía otro precio en mente?', 'Hey {{seller_first_name}}, does {{offer_price}} work for you to move forward, or did you have a different price in mind?', 'S5', 'Offer No-Response Follow-Up', false, 1, 'A', '24h after an offer we sent (automated or typed) with no reply. Quotes exactly the number we sent; never above the engine max.'),
  ('offer_no_response_fu1', 'lc-nr-offu1-es-b', 'offer_no_response_fu1 — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, solo para darle seguimiento. ¿Le sirve {{offer_price}}, o hay alguna cifra que tenga en mente?', 'Hi {{seller_first_name}}, just following up. Would {{offer_price}} work for you, or is there a number you had in mind?', 'S5', 'Offer No-Response Follow-Up', false, 1, 'B', '24h after an offer we sent (automated or typed) with no reply. Quotes exactly the number we sent; never above the engine max.'),
  ('offer_no_response_fu1', 'lc-nr-offu1-es-n', 'offer_no_response_fu1 — Spanish N (no-response follow-up)', 'Spanish', 'Hola, ¿le funciona {{offer_price}} para seguir adelante, o tenía otro precio en mente?', 'Hey, does {{offer_price}} work for you to move forward, or did you have a different price in mind?', 'S5', 'Offer No-Response Follow-Up', true, 9, 'N', '24h after an offer we sent (automated or typed) with no reply. Quotes exactly the number we sent; never above the engine max.'),
  ('offer_no_response_fu2', 'lc-nr-offu2-en-a', 'offer_no_response_fu2 — English A (no-response follow-up)', 'English', '{{seller_first_name}}, checking back on my {{offer_price}} offer. Is that workable, or where would you need to be?', null, 'S5', 'Offer No-Response Follow-Up', false, 1, 'A', '72h after the offer FU1 with no reply. Same number, different wording.'),
  ('offer_no_response_fu2', 'lc-nr-offu2-en-b', 'offer_no_response_fu2 — English B (no-response follow-up)', 'English', 'Hi {{seller_first_name}}, I''m still at {{offer_price}}. Would that work, or what number would get it done for you?', null, 'S5', 'Offer No-Response Follow-Up', false, 1, 'B', '72h after the offer FU1 with no reply. Same number, different wording.'),
  ('offer_no_response_fu2', 'lc-nr-offu2-en-n', 'offer_no_response_fu2 — English N (no-response follow-up)', 'English', 'Checking back on my {{offer_price}} offer. Is that workable, or where would you need to be?', null, 'S5', 'Offer No-Response Follow-Up', true, 9, 'N', '72h after the offer FU1 with no reply. Same number, different wording.'),
  ('offer_no_response_fu2', 'lc-nr-offu2-es-a', 'offer_no_response_fu2 — Spanish A (no-response follow-up)', 'Spanish', '{{seller_first_name}}, le doy seguimiento a mi oferta de {{offer_price}}. ¿Le funciona, o en qué cifra tendría que estar?', '{{seller_first_name}}, checking back on my {{offer_price}} offer. Is that workable, or where would you need to be?', 'S5', 'Offer No-Response Follow-Up', false, 1, 'A', '72h after the offer FU1 with no reply. Same number, different wording.'),
  ('offer_no_response_fu2', 'lc-nr-offu2-es-b', 'offer_no_response_fu2 — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, sigo en {{offer_price}}. ¿Le funcionaría, o qué cifra le haría cerrar el trato?', 'Hi {{seller_first_name}}, I''m still at {{offer_price}}. Would that work, or what number would get it done for you?', 'S5', 'Offer No-Response Follow-Up', false, 1, 'B', '72h after the offer FU1 with no reply. Same number, different wording.'),
  ('offer_no_response_fu2', 'lc-nr-offu2-es-n', 'offer_no_response_fu2 — Spanish N (no-response follow-up)', 'Spanish', 'Le doy seguimiento a mi oferta de {{offer_price}}. ¿Le funciona, o en qué cifra tendría que estar?', 'Checking back on my {{offer_price}} offer. Is that workable, or where would you need to be?', 'S5', 'Offer No-Response Follow-Up', true, 9, 'N', '72h after the offer FU1 with no reply. Same number, different wording.'),
  ('offer_no_response_nurture', 'lc-nr-ofnur-en-a', 'offer_no_response_nurture — English A (no-response follow-up)', 'English', 'Hi {{seller_first_name}}, this is {{agent_name}} again. Are you still open to selling the property? Happy to take another look at the numbers.', null, 'S5', 'Offer No-Response Nurture', false, 1, 'A', '30 days after the offer FU2. NEVER re-quotes a 30-day-old number.'),
  ('offer_no_response_nurture', 'lc-nr-ofnur-en-b', 'offer_no_response_nurture — English B (no-response follow-up)', 'English', 'Hey {{seller_first_name}}, checking back on the property. If you''re still thinking about selling, I''d be glad to revisit my offer.', null, 'S5', 'Offer No-Response Nurture', false, 1, 'B', '30 days after the offer FU2. NEVER re-quotes a 30-day-old number.'),
  ('offer_no_response_nurture', 'lc-nr-ofnur-en-n', 'offer_no_response_nurture — English N (no-response follow-up)', 'English', 'Checking back on the property. If you''re still thinking about selling, I''d be glad to revisit my offer.', null, 'S5', 'Offer No-Response Nurture', true, 9, 'N', '30 days after the offer FU2. NEVER re-quotes a 30-day-old number.'),
  ('offer_no_response_nurture', 'lc-nr-ofnur-es-a', 'offer_no_response_nurture — Spanish A (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, soy {{agent_name}} otra vez. ¿Todavía estaría abierto a vender la propiedad? Con gusto reviso los números de nuevo.', 'Hi {{seller_first_name}}, this is {{agent_name}} again. Are you still open to selling the property? Happy to take another look at the numbers.', 'S5', 'Offer No-Response Nurture', false, 1, 'A', '30 days after the offer FU2. NEVER re-quotes a 30-day-old number.'),
  ('offer_no_response_nurture', 'lc-nr-ofnur-es-b', 'offer_no_response_nurture — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, le escribo sobre la propiedad. Si todavía piensa vender, con gusto reviso mi oferta.', 'Hey {{seller_first_name}}, checking back on the property. If you''re still thinking about selling, I''d be glad to revisit my offer.', 'S5', 'Offer No-Response Nurture', false, 1, 'B', '30 days after the offer FU2. NEVER re-quotes a 30-day-old number.'),
  ('offer_no_response_nurture', 'lc-nr-ofnur-es-n', 'offer_no_response_nurture — Spanish N (no-response follow-up)', 'Spanish', 'Le escribo de nuevo sobre la propiedad. Si todavía piensa vender, con gusto reviso mi oferta.', 'Checking back on the property. If you''re still thinking about selling, I''d be glad to revisit my offer.', 'S5', 'Offer No-Response Nurture', true, 9, 'N', '30 days after the offer FU2. NEVER re-quotes a 30-day-old number.'),
  ('offer_no_response_no_number', 'lc-nr-ofnn-en-a', 'offer_no_response_no_number — English A (no-response follow-up)', 'English', 'Hey {{seller_first_name}}, does the offer work for you to move forward, or did you have a different price in mind?', null, 'S5', 'Offer No-Response Follow-Up (no number)', false, 1, 'A', 'Offer FU1/FU2 when the sent offer had several numbers / a range / no clean amount, or the amount is above the engine max. Quotes no number.'),
  ('offer_no_response_no_number', 'lc-nr-ofnn-en-b', 'offer_no_response_no_number — English B (no-response follow-up)', 'English', 'Hi {{seller_first_name}}, just following up on my offer. Would it work for you, or is there a number you had in mind?', null, 'S5', 'Offer No-Response Follow-Up (no number)', false, 1, 'B', 'Offer FU1/FU2 when the sent offer had several numbers / a range / no clean amount, or the amount is above the engine max. Quotes no number.'),
  ('offer_no_response_no_number', 'lc-nr-ofnn-en-n', 'offer_no_response_no_number — English N (no-response follow-up)', 'English', 'Hey, does the offer work for you to move forward, or did you have a different price in mind?', null, 'S5', 'Offer No-Response Follow-Up (no number)', true, 9, 'N', 'Offer FU1/FU2 when the sent offer had several numbers / a range / no clean amount, or the amount is above the engine max. Quotes no number.'),
  ('offer_no_response_no_number', 'lc-nr-ofnn-es-a', 'offer_no_response_no_number — Spanish A (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, ¿le funciona la oferta para seguir adelante, o tenía otro precio en mente?', 'Hey {{seller_first_name}}, does the offer work for you to move forward, or did you have a different price in mind?', 'S5', 'Offer No-Response Follow-Up (no number)', false, 1, 'A', 'Offer FU1/FU2 when the sent offer had several numbers / a range / no clean amount, or the amount is above the engine max. Quotes no number.'),
  ('offer_no_response_no_number', 'lc-nr-ofnn-es-b', 'offer_no_response_no_number — Spanish B (no-response follow-up)', 'Spanish', 'Hola {{seller_first_name}}, solo para darle seguimiento a mi oferta. ¿Le funciona, o hay alguna cifra que tenga en mente?', 'Hi {{seller_first_name}}, just following up on my offer. Would it work for you, or is there a number you had in mind?', 'S5', 'Offer No-Response Follow-Up (no number)', false, 1, 'B', 'Offer FU1/FU2 when the sent offer had several numbers / a range / no clean amount, or the amount is above the engine max. Quotes no number.'),
  ('offer_no_response_no_number', 'lc-nr-ofnn-es-n', 'offer_no_response_no_number — Spanish N (no-response follow-up)', 'Spanish', 'Hola, ¿le funciona la oferta para seguir adelante, o tenía otro precio en mente?', 'Hey, does the offer work for you to move forward, or did you have a different price in mind?', 'S5', 'Offer No-Response Follow-Up (no number)', true, 9, 'N', 'Offer FU1/FU2 when the sent offer had several numbers / a range / no clean amount, or the amount is above the engine max. Quotes no number.')
) as v(use_case, template_id, template_name, language, template_body, english_translation, stage_code, stage_label, minimal_fallback, fallback_rank, variant, fires)
where not exists (select 1 from public.sms_templates t where t.template_id = v.template_id);

commit;

-- POSTCHECK (read-only):
--   select use_case, language, count(*) from public.sms_templates
--    where metadata->>'authored_by' = 'no_response_followup_2026_10_06' group by 1, 2 order by 1, 2;   -- 14 groups × 3
