/**
 * Structured reason-code vocabulary for the IC8 comp micro-market challenger.
 * Every included AND excluded comp carries one or more of these codes with an
 * optional numeric/categorical `detail`. Codes only; never prose.
 */
export const REASON = Object.freeze({
  // Hard gates (exclusions)
  NOT_PRIOR_TO_AS_OF: 'NOT_PRIOR_TO_AS_OF',
  SAME_PROPERTY: 'SAME_PROPERTY',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  NO_COORDINATES: 'NO_COORDINATES',
  SALE_INVALID: 'SALE_INVALID',
  ASSET_FAMILY_MISMATCH: 'ASSET_FAMILY_MISMATCH',
  UNIT_COUNT_NOT_CREDIBLE: 'UNIT_COUNT_NOT_CREDIBLE',
  UNIT_BAND_MISMATCH: 'UNIT_BAND_MISMATCH',
  IMPROVED_VS_VACANT: 'IMPROVED_VS_VACANT',
  CONDO_VS_DETACHED: 'CONDO_VS_DETACHED',
  SIZE_UNKNOWN: 'SIZE_UNKNOWN',
  SIZE_INCOMPATIBLE: 'SIZE_INCOMPATIBLE',
  STALE_SALE: 'STALE_SALE',

  // Geography / selection (exclusions)
  OUTSIDE_ADAPTIVE_RADIUS: 'OUTSIDE_ADAPTIVE_RADIUS',
  OTHER_MICRO_MARKET: 'OTHER_MICRO_MARKET',
  ACROSS_DISCONTINUITY: 'ACROSS_DISCONTINUITY',
  LOWER_TIER_NOT_NEEDED: 'LOWER_TIER_NOT_NEEDED',
  RANK_BELOW_CUTOFF: 'RANK_BELOW_CUTOFF',
  PRICE_OUTLIER_WITHIN_REGIME: 'PRICE_OUTLIER_WITHIN_REGIME',
  REGIME_EVIDENCE_INSUFFICIENT: 'REGIME_EVIDENCE_INSUFFICIENT',

  // Inclusions: which fallback tier admitted the comp
  SAME_MICRO_MARKET: 'SAME_MICRO_MARKET',
  ADJACENT_SIMILAR_MICRO_MARKET: 'ADJACENT_SIMILAR_MICRO_MARKET',
  OTHER_MICRO_MARKET_NO_BARRIER: 'OTHER_MICRO_MARKET_NO_BARRIER',
  MICRO_MARKET_UNKNOWN: 'MICRO_MARKET_UNKNOWN',
  CROSS_DISCONTINUITY_FALLBACK: 'CROSS_DISCONTINUITY_FALLBACK',
  ADAPTIVE_RADIUS_EXTENDED: 'ADAPTIVE_RADIUS_EXTENDED',
  LOCATION_ADJUSTED: 'LOCATION_ADJUSTED',

  // Sale regime (every comp that passed the gates)
  REGIME_RETAIL: 'REGIME_RETAIL',
  REGIME_INVESTOR: 'REGIME_INVESTOR',
  REGIME_UNKNOWN: 'REGIME_UNKNOWN',

  // Value-level flags
  HEADLINE_RETAIL: 'HEADLINE_RETAIL',
  HEADLINE_FROM_UNKNOWN_REGIME: 'HEADLINE_FROM_UNKNOWN_REGIME',
  HEADLINE_FROM_INVESTOR_REGIME: 'HEADLINE_FROM_INVESTOR_REGIME',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  LOW_SUPPORT: 'LOW_SUPPORT',
  SUBJECT_SIZE_UNKNOWN: 'SUBJECT_SIZE_UNKNOWN',
  SUBJECT_FAMILY_UNSUPPORTED: 'SUBJECT_FAMILY_UNSUPPORTED',
  SUBJECT_MICRO_MARKET_UNKNOWN: 'SUBJECT_MICRO_MARKET_UNKNOWN',
  CROSS_DISCONTINUITY_EVIDENCE_USED: 'CROSS_DISCONTINUITY_EVIDENCE_USED',
});

export const INCLUSION_TIER_CODES = Object.freeze([
  REASON.SAME_MICRO_MARKET,
  REASON.ADJACENT_SIMILAR_MICRO_MARKET,
  REASON.OTHER_MICRO_MARKET_NO_BARRIER,
  REASON.MICRO_MARKET_UNKNOWN,
  REASON.CROSS_DISCONTINUITY_FALLBACK,
]);

const KNOWN = new Set(Object.values(REASON));

export function reason(code, detail = undefined) {
  if (!KNOWN.has(code)) throw new Error(`unknown_reason_code:${code}`);
  return detail === undefined ? { code } : { code, detail };
}

export function isKnownReasonCode(code) {
  return KNOWN.has(code);
}
