import ENV from "./env.js";

export const FEATURE_FLAGS = {
  ENABLE_DEALS_AUTOPILOT: ENV.ENABLE_DEALS_AUTOPILOT,
  ENABLE_LIVE_SENDING: ENV.ENABLE_LIVE_SENDING,
  ENABLE_AI_ASSIST: ENV.ENABLE_AI_ASSIST,

  ENABLE_QUEUE_RUNNER: true,
  ENABLE_RETRY_RUNNER: true,
  ENABLE_DELIVERY_WEBHOOK_UPDATES: true,
  ENABLE_INBOUND_BRAIN_UPDATES: true,
  ENABLE_TEMPLATE_STATS_SYNC: true,

  ENABLE_AUTO_OFFER_FLOW: ENV.ENABLE_AUTO_OFFER_FLOW,
  ENABLE_AUTO_CONTRACT_FLOW: ENV.ENABLE_AUTO_CONTRACT_FLOW,
  ENABLE_AUTO_CONTRACT_SEND: ENV.ENABLE_AUTO_CONTRACT_SEND,
  ENABLE_AUTO_TITLE_ROUTING: ENV.ENABLE_AUTO_TITLE_ROUTING,
  ENABLE_AUTO_TITLE_COMPANY_ASSIGNMENT: ENV.ENABLE_AUTO_TITLE_COMPANY_ASSIGNMENT,
  ENABLE_AUTO_TITLE_INTRO: ENV.ENABLE_AUTO_TITLE_INTRO,
  ENABLE_AUTO_CLOSING_FLOW: ENV.ENABLE_AUTO_CLOSING_FLOW,
  ENABLE_AUTO_BUYER_MATCH: ENV.ENABLE_AUTO_BUYER_MATCH,
  ENABLE_AUTO_BUYER_BLAST: ENV.ENABLE_AUTO_BUYER_BLAST,
  ENABLE_AUTO_REVENUE_SYNC: ENV.ENABLE_AUTO_REVENUE_SYNC,

  ENABLE_PODIO_HOOKS: true,
  ENABLE_TEXTGRID_WEBHOOKS: true,
};

export function isFeatureEnabled(flag) {
  return Boolean(FEATURE_FLAGS[flag]);
}

export default FEATURE_FLAGS;
